#! /bin/sh
# Dezyne --- Dezyne command line tools
#
# Copyright © 2020 Johri van Eerd <vaneerd.johri@gmail.com>
# Copyright © 2023 Jan (janneke) Nieuwenhuizen <janneke@gnu.org>
#
# This file is part of Dezyne.
#
# Dezyne is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Dezyne is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with Dezyne.  If not, see <http://www.gnu.org/licenses/>.
#
set -ex
pwd
dir=$1
base=$(basename $dir)
mkdir -p $dir/out/c++
dzn code --calling-context=exception_context --language=c++-exception-wrappers -o $dir/out/c++ $dir/$base.dzn
WARN_FLAGS=-Wno-all
export WARN_FLAGS
run $dir
