#! /bin/sh

gaiag/bin/gdzn code -l scheme -o  build/verification/scheme services/scripts/verification-scm.dzn
classes=$(grep -Eo 'define-class <[^ ]+>' build/verification/scheme/dzn/*.scm services/scripts/dzn/*scm | grep -Eo '<[^ ]+>' | sed 's@^@            @')
accessors=$(grep -Eo '#:accessor +[^ ]+' build/verification/scheme/dzn/*.scm services/scripts/dzn/*scm | grep -Eo ' [^ ]+$' | sed 's@^@            @' | sort -u)
cat <<EOF > build/verification/scheme/code.scm
(define-module (code)
  #:use-module (ice-9 optargs)
  #:use-module (ice-9 popen)
  #:use-module (ice-9 rdelim)
  #:use-module (ice-9 receive)
  #:use-module (oop goops)
  #:use-module (dzn runtime)
  #:export (
$classes
$accessors
           ))
EOF
set -x
cat services/scripts/async.scm build/verification/scheme/dzn/*.scm services/scripts/dzn/*scm >> build/verification/scheme/code.scm
GUILE_LOAD_PATH=$PWD/gaiag/runtime/scheme:$GUILE_LOAD_PATH
GUILE_LOAD_PATH=$PWD/build/verification/scheme:$GUILE_LOAD_PATH
export GUILE_LOAD_PATH
export GUILE_AUTO_COMPILE=0
guild compile -o gaiag/runtime/scheme/dzn/runtime.go gaiag/runtime/scheme/dzn/runtime.scm
guild compile -o build/verification/scheme/code.go build/verification/scheme/code.scm
