#! /bin/sh
# -*- scheme -*-
set -x
test=$(dirname $0)/../..
dzn=$(readlink -f $(command -v dzn))
dzn=$(dirname $dzn)/../dzn
exec ${GUILE-guile} --no-auto-compile -L $test/../dzn -L $dzn  -C $test/../dzn -C $dzn -L $test/all/dzn-glue -e '(run)' -s "$0" ${1+"$@"}
!#

(define-module (run)
  #:use-module (srfi srfi-1)
  #:use-module (srfi srfi-26)
  #:use-module (ice-9 receive)
  #:use-module (ice-9 curried-definitions)
  #:use-module (json)
  #:use-module (dzn shell-util)
  #:use-module (ice-9 popen)
  #:use-module (ice-9 rdelim)
  #:use-module (gash job)
  #:use-module (gash pipe)
  #:export (main))

(define global-status 0)

(define (logf port string . rest)
  (apply format (cons* port string rest))
  (force-output port)
  #t)

(define (stderr string . rest)
  (apply logf (cons* (current-error-port) string rest)))

(define (stdout string . rest)
  (apply logf (cons* (current-output-port) string rest)))

(define (pke . stuff)
  (newline (current-error-port))
  (display ";;; " (current-error-port))
  (write stuff (current-error-port))
  (newline (current-error-port))
  (car (last-pair stuff)))

(define (handle-error job error)
  (let ((status (wait job)))
    (when (not (zero? status))
      (stderr "ERROR: exit: ~a: ~a" status error)
      (set! global-status (1+ global-status))
      (throw 'pipe status error ))
    status))

(define (assert-pipe . commands)
  (stdout "~a\n" (string-join (car commands)))
  (stderr "~a\n" (string-join (car commands)))
  (receive (job ports)
      (apply pipeline+ #f commands)
    (set-port-encoding! (car ports) "ISO-8859-1")
    (let ((text (read-string (car ports)))
          (error (read-string (cadr ports))))
      (handle-error job error)
      text)))

(define ((asd->dzn dzn out version) dm-file)
  (assert-pipe `(,dzn "--session=100" "-v" "convert" "--globals" "--glue" "--system" "--map" "--output" ,out ,dm-file)))

(define ((dzn->code dzn dir out version language model map-files) dzn-file)
  (assert-pipe `(,dzn
                 "code" "-l" ,language
                 "-I" ,out ;; FIXME:  dzn bug
                 "--glue=dzn"
                 "-o" ,(string-append out "/" language)
                 "-m" ,model
                 ,dzn-file
                 ,@map-files)))

(define (convert dzn dir out version)
  (let* ((dir (string-append dir "/"))
         (im-files (find-files dir ".*[.]im$"))
         (dm-files (find-files dir ".*[.]dm$")))
    (format #t "dir:~s\n" dir)
    (format #t "im-files:~s\n" im-files)
    (format #t "dm-files:~s\n" dm-files)

    (for-each (asd->dzn dzn out version) im-files)
    (for-each (asd->dzn dzn out version) dm-files)

    ;; FIXME: fail silently, skip trying to get past opaque build3.oban failure
    ;;(delete-file (string-append out "/console.dzn"))
    (assert-pipe `("rm" "-f" ,(string-append out "/glue_console.dzn")))))

(define (code test dzn model dir out version language)
  (let* ((dzn-files (find-files out ".*[.]dzn$"))
         (map-files (find-files out ".*[.]map$")))
    (for-each (dzn->code dzn dir out version language model map-files) dzn-files)
    (assert-pipe
    `("make"
      ,(string-append "DZN=" dzn)
      ,(string-append "MODEL=" model)
      ,(string-append "DIR=" out)
      ,(string-append "LANGUAGE=" language)
      "IN=foobar"
      ,(string-append "OUT=" out "/" language)
      "-f"
      ,(string-append test "/lib/code.make")
      "runtime"))))

(define (build test model dir out version language)
  (assert-pipe
   `("make"
     ,(string-append "DIR=" dir)
     ,(string-append "LANGUAGE=" language)
     ,(string-append "OUT=" out "/" language)
     ,(string-append "INCLUDES=" out "/" language)
     ,(string-append "IN=" dir "/" language)
     "-f" ,(string-append test "/lib/build." language ".make"))))

(define (execute dir out version language)
  (assert-pipe (list (string-append out "/" language "/test"))))

(define (with-result-and-output thunk)
  (let* ((result 'foo)
         (output (with-output-to-string
                   (lambda ()
                     (let ((status (catch #t
                                     (lambda ()
                                       (thunk)
                                       'OK)
                                     (lambda (key . args)
                                       (stderr "~s\n" args)
                                       (format #t "error executing: ~a\n" args)
                                       'FAILED))))
                       (set! result status))))))
    (cons result output)))

(define (results->json . results)
  (scm->json-string
   (append (let loop ((results results))
             (if (null? (cdr results)) (car results)
                 (alist-append (car results)
                               (loop (cdr results)))))
           (list (cons "order" (list
                                "convert"
                                "parse"
                                "verify"
                                "traces"
                                "code"
                                "build"
                                "execute"
                                "run"
                                "triangle"
                                "table"
                                "view"
                                ))))))

(define (alist-append a b)
  (let ((keys (map car a)))
    (map (lambda (key a b) (cons key (append a b))) keys (map cdr a) (map cdr b))))

(define (stage->alist stage versions languages results)
  `((status . ((,stage . ,(if (null? languages) (car results)
                              (map (lambda (version)
                                     (cons version
                                           (map (lambda (language result) (cons language result))
                                                languages (map car (assoc-ref results version)))))
                                   versions)))))
    (output . ,(if (null? languages) (list (cons stage (cdr results)))
                   (append-map (lambda (version)
                                 (map (lambda (language output)
                                        (cons (string-append stage "-" version "-" language) output))
                                      languages (map cdr (assoc-ref results version))))
                               versions)))))

(define (main args)
  (let* ((dir (dirname (car args)))
         (foo (stderr "dir: ~a\n" dir))
         (test ((compose dirname dirname) dir))
         (foo (stderr "test: ~a\n" test))
         (development (if (equal? test ".") ".." (dirname test)))
         (foo (stderr "development: ~a\n" development))
         (dzn (or (getenv "DZN") (string-append development "/dzn/bin/dzn")))
         (model "alarm")
         (out (string-append "out/" (substring dir (1+ (string-rindex dir #\/)))))
         (languages '("c++" "c++03"))
         (versions '("development")))

    (when (file-exists? out) (delete-file-recursively out))
    (mkdir-p out)
    (let ((json (results->json
                 (stage->alist "convert" '() '()
                               (with-result-and-output (lambda () (convert dzn dir out (car versions)))))
                 (stage->alist "code" versions languages
                               (map (lambda (version)
                                      (cons version
                                            (map (lambda (language)
                                              (with-result-and-output (lambda () (code test dzn model dir out version language))))
                                            languages)))
                                    versions))
                 (stage->alist "build" versions languages
                               (map (lambda (version)
                                      (cons version
                                            (map (lambda (language)
                                              (with-result-and-output (lambda () (build test model dir out version language))))
                                            languages)))
                                    versions))
                 (stage->alist "execute" versions languages
                               (map (lambda (version)
                                      (cons version
                                            (map (lambda (language)
                                              (with-result-and-output (lambda () (execute dir out version language))))
                                            languages)))
                                    versions)))))
      (with-output-to-file (string-append out "/outcome.json")
        (cut display json)))

    (stderr "~a" (if (zero? global-status) "[PASS]" "[FAIL]"))
    (exit global-status)))

;; REPL
;; (define dir "all/dzn-glue")
;; (define dzn "../dzn/bin/dzn")
;; (define model "alarm")
;; (define out (string-append "out/" (substring dir (1+ (string-index dir #\/)))))
;; (define languages '("c++" "c++03"))
