// Generated by dzn code from test/all/shell_injected/shell_injected.dzn
// -*-java-*-
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading;

class main {

  static void connect_ports (dzn.container<shell_injected> c)
  {
    c.system.r.inport.e = () => {
      dzn.Runtime.traceIn(c.system.r.dzn_meta, "e");
      c.match("r.e");
      String tmp = c.match_return();
      dzn.Runtime.traceOut(c.system.r.dzn_meta, tmp.Split('.')[1]);
      return ;
    };c.system.p.outport.f = () => {
      c.match("p.f");
      c.dzn_runtime.call_out(c, () => {
        if(c.flush) c.dzn_runtime.queue(c).Enqueue(() => {
          if(c.dzn_runtime.queue(c).Count == 0) {
            Console.Error.WriteLine("p.<flush>");
            c.match("p.<flush>");
          }
        });
      }, c.system.p.dzn_meta, "f");
    };
  }

  static Dictionary<String, Action> event_map (dzn.container<shell_injected> c)
  {
    c.system.p.dzn_meta.requires.component = c;
    c.system.p.dzn_meta.requires.meta = c.dzn_meta;
    c.system.p.dzn_meta.requires.name = "p";
    c.system.r.dzn_meta.provides.component = c;
    c.system.r.dzn_meta.provides.meta = c.dzn_meta;
    c.system.r.dzn_meta.provides.name = "r";

    Dictionary<String, Action> lookup = new Dictionary<String, Action>();
    lookup.Add("illegal",()=>{Console.Error.WriteLine("illegal"); Environment.Exit(0);});
    lookup.Add("p.e",()=>{c.system.p.inport.e(); c.match("p.return");});
    lookup.Add("r.f",()=>{Thread.Sleep(1000); c.system.r.outport.f(); });
    lookup.Add("r.<flush>",()=>{System.Console.Error.WriteLine("r.<flush>");
      c.dzn_runtime.flush(c);
    });

    return lookup;
  }

  public static void Main(String[] args)
  {
    if(Array.Exists(args, s => s == "--debug")) {
      Debug.Listeners.Add(new TextWriterTraceListener(Console.Error));
      Debug.AutoFlush = true;
    }
    bool flush = Array.Exists(args, s => s == "--flush");
    using(dzn.container<shell_injected> c = new dzn.container<shell_injected>((loc,name)=>{return new shell_injected(loc,name);}, flush)) {
      connect_ports (c);
      c.run(event_map (c), new List<String> {"r"});
    }
  }
}
//version: 2.12.0.rc2.8-3d547
