// Gaiag --- Guile in Asd In Asd in Guile.
//
// This file is part of Gaiag.
//
// Copyright © 2014 Rutger van Beusekom <rutger.van.beusekom@verum.com>
// Copyright © 2014 Jan Nieuwenhuizen <janneke@gnu.org>
//
// Gaiag is free software: you can redistribute it and/or modify it
// under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// Gaiag is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public
// License along with Gaiag.  If not, see <http://www.gnu.org/licenses/>.
//
// Commentary:
//
// Code:

// /////////////////////////////////////////////////////////////////////////////
// 
// File generated by   : Verum ASD:Suite Release 4, version 9.2.6.52369
// Language            : cpp
// 
// Model name          : AlarmSystem
// Model file          : AlarmSystem.im
// Model last updated  : 2014-Aug-20 12:09:48
// Model fingerprint   : 625E5F8C
// 
// Version             : 1.0
// Project             : 
// Author              : Peter van de Velde
// Execution model     : Single-threaded
// Broadcasting        : No
// 
// /////////////////////////////////////////////////////////////////////////////
// 
// Verification result  : outdated
// 
// /////////////////////////////////////////////////////////////////////////////
// 
// Alarm system that can be switched on/off by one key. If sensor is activated it can sense activity; if it does it trips the alarm. In case of alarm the siren will make noise.
// 
// /////////////////////////////////////////////////////////////////////////////
// 
// TAGS:
// 
// tag: Tag
// Description
// 
// /////////////////////////////////////////////////////////////////////////////


#ifndef __ALARMSYSTEM_INTERFACE_H__
#define __ALARMSYSTEM_INTERFACE_H__

#include <boost/shared_ptr.hpp>

#ifdef ASD_HAVE_CONFIG_H
  #include "asdConfig.h"
#else
  #include "asdDefConfig.h"
#endif

#include "asdPassByValue.h"
#include "asdInterfaces.h"



class IAlarmSystem
{
public:
  enum PseudoStimulus {
    
    /// <summary>
    /// The VoidReply event indicates that the processing of the API call has been completed
    /// and the call can return when appropriate.
    /// </summary>
    VoidReply,
    Ok,
    Failed
  };
  virtual ~IAlarmSystem() {}

  /// <summary>
  /// Switch on the alarm system
  /// </summary>
  virtual IAlarmSystem::PseudoStimulus SwitchOn() = 0;

  /// <summary>
  /// Switch off the alarm system; asynchronous: SwitchedOff notifies completion
  /// </summary>
  virtual void SwitchOff() = 0;
protected:
  IAlarmSystem() {}
private:
  IAlarmSystem& operator = (const IAlarmSystem& other);
  IAlarmSystem(const IAlarmSystem& other);
};

class IAlarmSystem_NI
{
public:
  virtual ~IAlarmSystem_NI() {}

  /// <summary>
  /// Alarm system has detected movement
  /// </summary>
  virtual void Tripped() = 0;

  /// <summary>
  /// Notification that SwitchOff has completed
  /// </summary>
  virtual void SwitchedOff() = 0;
protected:
  IAlarmSystem_NI() {}
private:
  IAlarmSystem_NI& operator = (const IAlarmSystem_NI& other);
  IAlarmSystem_NI(const IAlarmSystem_NI& other);
};

class AlarmSystemInterface
{
public:
  virtual ~AlarmSystemInterface() {}
  virtual void GetAPI(boost::shared_ptr<IAlarmSystem>* api) = 0;
  virtual void RegisterCB(boost::shared_ptr<IAlarmSystem_NI> cb) = 0;
  virtual void RegisterCB(boost::shared_ptr<asd::channels::ISingleThreaded> cb) = 0;
protected:
  AlarmSystemInterface() {}
private:
  AlarmSystemInterface& operator = (const AlarmSystemInterface& other);
  AlarmSystemInterface(const AlarmSystemInterface& other);
};

#endif

// /////////////////////////////////////////////////////////////////////////////
// 
// Verum audit trail signature : 1wELZVYbdNXyUhNPdaqKh3w3eKJo+yIVhGrVeDhjgSWzKcZkdqoSZ2o818kqDCSGwPb3ixF8aIbscSMNQlo3n4BqxH7C28jzymGfx1Pw8b0q1+R9EC95Rt+1qe/EinvoDC4TJtFm00JPsjq5IyqoCg3jFgklaXFOOP7nnuaEtLGob7+X+RR89Azm02ChkVD83m9VtmxuDFRVT50dFrKbrLNFfLroTW+t2yDTSGAW/ZfeSdh9vuU3k9JtDFWUT80UMSyku5uPnVdCTyxADNsduBON+I62jV9UfS+UNMN6O2rnU2D5nTK5rNrRsYuRLFHvatWgdnFw2PO2UqTEiaXnow==
// 
// /////////////////////////////////////////////////////////////////////////////
// 
// ---------- End of file ------------------------------------------------------
// 
// /////////////////////////////////////////////////////////////////////////////
