;;; Dezyne --- Dezyne command line tools
;;;
;;; Copyright © 2015 Jan Nieuwenhuizen <janneke@gnu.org>
;;;
;;; This file is part of Dezyne.
;;;
;;; Dezyne is free software: you can redistribute it and/or modify it
;;; under the terms of the GNU Affero General Public License as
;;; published by the Free Software Foundation, either version 3 of the
;;; License, or (at your option) any later version.
;;;
;;; Dezyne is distributed in the hope that it will be useful, but
;;; WITHOUT ANY WARRANTY; without even the implied warranty of
;;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
;;; Affero General Public License for more details.
;;;
;;; You should have received a copy of the GNU Affero General Public
;;; License along with Dezyne.  If not, see <http://www.gnu.org/licenses/>.
;;; 
;;; Commentary:
;;; 
;;; Code:

(define relaxed? #t)

(define (drop-prefix string prefix)
  (if (string-prefix? prefix string)
      (substring string (string-length prefix))
      string))

(define (consume_synchronous_out_events event-alist)
  (read-line)
  (let loop ((line (read-line)))
    (and-let* ((line line) 
               ((not (eof-object? line)))
               (event (assoc-ref event-alist (string->symbol line))))
              (event)
              (loop (read-line)))
    line))

(define (log-in prefix event event-alist)
  (stderr "~a~a\n" prefix event)
  (when (not relaxed?)
    (consume_synchronous_out_events event-alist)
    (stderr "~a~a\n" prefix 'return))
  #f)

(define (log-out prefix event event-alist)
  (stderr "~a~a\n" prefix event)
  #f)

(define (log-valued prefix event event-alist string->value value->symbol)
  (stderr "~a~a\n" prefix event)
  (if (not relaxed?)
      (let* ((s (consume_synchronous_out_events event-alist))
             (r (string->value s)))
        (if r
            (and (stderr "~a~a\n" prefix (value->symbol r))
                 r)
            0))
      0))

(define (fill-event-alist o)
  (let ((e `(
             (ctrl.calibrate . ,(.calibrate (.in (.ctrl o))))
             (ctrl.stop . ,(.stop (.in (.ctrl o))))
             (ctrl.operate . ,(.operate (.in (.ctrl o)))))))
          (set! (.calibrated (.out (.ctrl o)))
       (lambda (. args)
      (log-out "ctrl." 'calibrated e)))
      (set! (.finished (.out (.ctrl o)))
       (lambda (. args)
      (log-out "ctrl." 'finished e)))
      (set! (.move (.in (.brick1_aA o)))
       (lambda (. args)
      (log-in "brick1_aA." 'move e)))
      (set! (.run (.in (.brick1_aA o)))
       (lambda (. args)
      (log-in "brick1_aA." 'run e)))
      (set! (.stop (.in (.brick1_aA o)))
       (lambda (. args)
      (log-in "brick1_aA." 'stop e)))
      (set! (.coast (.in (.brick1_aA o)))
       (lambda (. args)
      (log-in "brick1_aA." 'coast e)))
      (set! (.zero (.in (.brick1_aA o)))
       (lambda (. args)
      (log-in "brick1_aA." 'zero e)))
      (set! (.position (.in (.brick1_aA o)))
       (lambda (. args)
      (log-in "brick1_aA." 'position e)))
      (set! (.at (.in (.brick1_aA o)))
       (lambda (. args)
    (log-valued "brick1_aA." 'at e (lambda (s) (assoc-ref imotor-result_t-alist (string->symbol (drop-prefix s "brick1_aA.result_t_")))) (lambda (r) (symbol-append 'result_t_ (assoc-xref imotor-result_t-alist r))))))
      (set! (.move (.in (.brick1_aB o)))
       (lambda (. args)
      (log-in "brick1_aB." 'move e)))
      (set! (.run (.in (.brick1_aB o)))
       (lambda (. args)
      (log-in "brick1_aB." 'run e)))
      (set! (.stop (.in (.brick1_aB o)))
       (lambda (. args)
      (log-in "brick1_aB." 'stop e)))
      (set! (.coast (.in (.brick1_aB o)))
       (lambda (. args)
      (log-in "brick1_aB." 'coast e)))
      (set! (.zero (.in (.brick1_aB o)))
       (lambda (. args)
      (log-in "brick1_aB." 'zero e)))
      (set! (.position (.in (.brick1_aB o)))
       (lambda (. args)
      (log-in "brick1_aB." 'position e)))
      (set! (.at (.in (.brick1_aB o)))
       (lambda (. args)
    (log-valued "brick1_aB." 'at e (lambda (s) (assoc-ref imotor-result_t-alist (string->symbol (drop-prefix s "brick1_aB.result_t_")))) (lambda (r) (symbol-append 'result_t_ (assoc-xref imotor-result_t-alist r))))))
      (set! (.move (.in (.brick1_aC o)))
       (lambda (. args)
      (log-in "brick1_aC." 'move e)))
      (set! (.run (.in (.brick1_aC o)))
       (lambda (. args)
      (log-in "brick1_aC." 'run e)))
      (set! (.stop (.in (.brick1_aC o)))
       (lambda (. args)
      (log-in "brick1_aC." 'stop e)))
      (set! (.coast (.in (.brick1_aC o)))
       (lambda (. args)
      (log-in "brick1_aC." 'coast e)))
      (set! (.zero (.in (.brick1_aC o)))
       (lambda (. args)
      (log-in "brick1_aC." 'zero e)))
      (set! (.position (.in (.brick1_aC o)))
       (lambda (. args)
      (log-in "brick1_aC." 'position e)))
      (set! (.at (.in (.brick1_aC o)))
       (lambda (. args)
    (log-valued "brick1_aC." 'at e (lambda (s) (assoc-ref imotor-result_t-alist (string->symbol (drop-prefix s "brick1_aC.result_t_")))) (lambda (r) (symbol-append 'result_t_ (assoc-xref imotor-result_t-alist r))))))
      (set! (.detect (.in (.brick1_s1 o)))
       (lambda (. args)
    (log-valued "brick1_s1." 'detect e (lambda (s) (assoc-ref itouch-status-alist (string->symbol (drop-prefix s "brick1_s1.status_")))) (lambda (r) (symbol-append 'status_ (assoc-xref itouch-status-alist r))))))
      (set! (.detect (.in (.brick1_s2 o)))
       (lambda (. args)
    (log-valued "brick1_s2." 'detect e (lambda (s) (assoc-ref itouch-status-alist (string->symbol (drop-prefix s "brick1_s2.status_")))) (lambda (r) (symbol-append 'status_ (assoc-xref itouch-status-alist r))))))
      (set! (.detect (.in (.brick1_s3 o)))
       (lambda (. args)
    (log-valued "brick1_s3." 'detect e (lambda (s) (assoc-ref itouch-status-alist (string->symbol (drop-prefix s "brick1_s3.status_")))) (lambda (r) (symbol-append 'status_ (assoc-xref itouch-status-alist r))))))
      (set! (.detect (.in (.brick1_s4 o)))
       (lambda (. args)
    (log-valued "brick1_s4." 'detect e (lambda (s) (assoc-ref itouch-status-alist (string->symbol (drop-prefix s "brick1_s4.status_")))) (lambda (r) (symbol-append 'status_ (assoc-xref itouch-status-alist r))))))
      (set! (.move (.in (.brick2_aA o)))
       (lambda (. args)
      (log-in "brick2_aA." 'move e)))
      (set! (.run (.in (.brick2_aA o)))
       (lambda (. args)
      (log-in "brick2_aA." 'run e)))
      (set! (.stop (.in (.brick2_aA o)))
       (lambda (. args)
      (log-in "brick2_aA." 'stop e)))
      (set! (.coast (.in (.brick2_aA o)))
       (lambda (. args)
      (log-in "brick2_aA." 'coast e)))
      (set! (.zero (.in (.brick2_aA o)))
       (lambda (. args)
      (log-in "brick2_aA." 'zero e)))
      (set! (.position (.in (.brick2_aA o)))
       (lambda (. args)
      (log-in "brick2_aA." 'position e)))
      (set! (.at (.in (.brick2_aA o)))
       (lambda (. args)
    (log-valued "brick2_aA." 'at e (lambda (s) (assoc-ref imotor-result_t-alist (string->symbol (drop-prefix s "brick2_aA.result_t_")))) (lambda (r) (symbol-append 'result_t_ (assoc-xref imotor-result_t-alist r))))))
      (set! (.move (.in (.brick2_aB o)))
       (lambda (. args)
      (log-in "brick2_aB." 'move e)))
      (set! (.run (.in (.brick2_aB o)))
       (lambda (. args)
      (log-in "brick2_aB." 'run e)))
      (set! (.stop (.in (.brick2_aB o)))
       (lambda (. args)
      (log-in "brick2_aB." 'stop e)))
      (set! (.coast (.in (.brick2_aB o)))
       (lambda (. args)
      (log-in "brick2_aB." 'coast e)))
      (set! (.zero (.in (.brick2_aB o)))
       (lambda (. args)
      (log-in "brick2_aB." 'zero e)))
      (set! (.position (.in (.brick2_aB o)))
       (lambda (. args)
      (log-in "brick2_aB." 'position e)))
      (set! (.at (.in (.brick2_aB o)))
       (lambda (. args)
    (log-valued "brick2_aB." 'at e (lambda (s) (assoc-ref imotor-result_t-alist (string->symbol (drop-prefix s "brick2_aB.result_t_")))) (lambda (r) (symbol-append 'result_t_ (assoc-xref imotor-result_t-alist r))))))
      (set! (.detect (.in (.brick2_s2 o)))
       (lambda (. args)
    (log-valued "brick2_s2." 'detect e (lambda (s) (assoc-ref itouch-status-alist (string->symbol (drop-prefix s "brick2_s2.status_")))) (lambda (r) (symbol-append 'status_ (assoc-xref itouch-status-alist r))))))
      (set! (.detect (.in (.brick2_s3 o)))
       (lambda (. args)
    (log-valued "brick2_s3." 'detect e (lambda (s) (assoc-ref itouch-status-alist (string->symbol (drop-prefix s "brick2_s3.status_")))) (lambda (r) (symbol-append 'status_ (assoc-xref itouch-status-alist r))))))
      (set! (.detect (.in (.brick2_s4 o)))
       (lambda (. args)
    (log-valued "brick2_s4." 'detect e (lambda (s) (assoc-ref itouch-status-alist (string->symbol (drop-prefix s "brick2_s4.status_")))) (lambda (r) (symbol-append 'status_ (assoc-xref itouch-status-alist r))))))
      (set! (.move (.in (.brick3_aA o)))
       (lambda (. args)
      (log-in "brick3_aA." 'move e)))
      (set! (.run (.in (.brick3_aA o)))
       (lambda (. args)
      (log-in "brick3_aA." 'run e)))
      (set! (.stop (.in (.brick3_aA o)))
       (lambda (. args)
      (log-in "brick3_aA." 'stop e)))
      (set! (.coast (.in (.brick3_aA o)))
       (lambda (. args)
      (log-in "brick3_aA." 'coast e)))
      (set! (.zero (.in (.brick3_aA o)))
       (lambda (. args)
      (log-in "brick3_aA." 'zero e)))
      (set! (.position (.in (.brick3_aA o)))
       (lambda (. args)
      (log-in "brick3_aA." 'position e)))
      (set! (.at (.in (.brick3_aA o)))
       (lambda (. args)
    (log-valued "brick3_aA." 'at e (lambda (s) (assoc-ref imotor-result_t-alist (string->symbol (drop-prefix s "brick3_aA.result_t_")))) (lambda (r) (symbol-append 'result_t_ (assoc-xref imotor-result_t-alist r))))))
      (set! (.move (.in (.brick3_aC o)))
       (lambda (. args)
      (log-in "brick3_aC." 'move e)))
      (set! (.run (.in (.brick3_aC o)))
       (lambda (. args)
      (log-in "brick3_aC." 'run e)))
      (set! (.stop (.in (.brick3_aC o)))
       (lambda (. args)
      (log-in "brick3_aC." 'stop e)))
      (set! (.coast (.in (.brick3_aC o)))
       (lambda (. args)
      (log-in "brick3_aC." 'coast e)))
      (set! (.zero (.in (.brick3_aC o)))
       (lambda (. args)
      (log-in "brick3_aC." 'zero e)))
      (set! (.position (.in (.brick3_aC o)))
       (lambda (. args)
      (log-in "brick3_aC." 'position e)))
      (set! (.at (.in (.brick3_aC o)))
       (lambda (. args)
    (log-valued "brick3_aC." 'at e (lambda (s) (assoc-ref imotor-result_t-alist (string->symbol (drop-prefix s "brick3_aC.result_t_")))) (lambda (r) (symbol-append 'result_t_ (assoc-xref imotor-result_t-alist r))))))
      (set! (.turnon (.in (.brick3_s1 o)))
       (lambda (. args)
      (log-in "brick3_s1." 'turnon e)))
      (set! (.turnoff (.in (.brick3_s1 o)))
       (lambda (. args)
      (log-in "brick3_s1." 'turnoff e)))
      (set! (.detect (.in (.brick3_s1 o)))
       (lambda (. args)
    (log-valued "brick3_s1." 'detect e (lambda (s) (assoc-ref ilight-status-alist (string->symbol (drop-prefix s "brick3_s1.status_")))) (lambda (r) (symbol-append 'status_ (assoc-xref ilight-status-alist r))))))
      (set! (.detect (.in (.brick3_s2 o)))
       (lambda (. args)
    (log-valued "brick3_s2." 'detect e (lambda (s) (assoc-ref itouch-status-alist (string->symbol (drop-prefix s "brick3_s2.status_")))) (lambda (r) (symbol-append 'status_ (assoc-xref itouch-status-alist r))))))
      (set! (.detect (.in (.brick3_s3 o)))
       (lambda (. args)
    (log-valued "brick3_s3." 'detect e (lambda (s) (assoc-ref itouch-status-alist (string->symbol (drop-prefix s "brick3_s3.status_")))) (lambda (r) (symbol-append 'status_ (assoc-xref itouch-status-alist r))))))
      (set! (.move (.in (.brick4_aA o)))
       (lambda (. args)
      (log-in "brick4_aA." 'move e)))
      (set! (.run (.in (.brick4_aA o)))
       (lambda (. args)
      (log-in "brick4_aA." 'run e)))
      (set! (.stop (.in (.brick4_aA o)))
       (lambda (. args)
      (log-in "brick4_aA." 'stop e)))
      (set! (.coast (.in (.brick4_aA o)))
       (lambda (. args)
      (log-in "brick4_aA." 'coast e)))
      (set! (.zero (.in (.brick4_aA o)))
       (lambda (. args)
      (log-in "brick4_aA." 'zero e)))
      (set! (.position (.in (.brick4_aA o)))
       (lambda (. args)
      (log-in "brick4_aA." 'position e)))
      (set! (.at (.in (.brick4_aA o)))
       (lambda (. args)
    (log-valued "brick4_aA." 'at e (lambda (s) (assoc-ref imotor-result_t-alist (string->symbol (drop-prefix s "brick4_aA.result_t_")))) (lambda (r) (symbol-append 'result_t_ (assoc-xref imotor-result_t-alist r))))))
      (set! (.move (.in (.brick4_aB o)))
       (lambda (. args)
      (log-in "brick4_aB." 'move e)))
      (set! (.run (.in (.brick4_aB o)))
       (lambda (. args)
      (log-in "brick4_aB." 'run e)))
      (set! (.stop (.in (.brick4_aB o)))
       (lambda (. args)
      (log-in "brick4_aB." 'stop e)))
      (set! (.coast (.in (.brick4_aB o)))
       (lambda (. args)
      (log-in "brick4_aB." 'coast e)))
      (set! (.zero (.in (.brick4_aB o)))
       (lambda (. args)
      (log-in "brick4_aB." 'zero e)))
      (set! (.position (.in (.brick4_aB o)))
       (lambda (. args)
      (log-in "brick4_aB." 'position e)))
      (set! (.at (.in (.brick4_aB o)))
       (lambda (. args)
    (log-valued "brick4_aB." 'at e (lambda (s) (assoc-ref imotor-result_t-alist (string->symbol (drop-prefix s "brick4_aB.result_t_")))) (lambda (r) (symbol-append 'result_t_ (assoc-xref imotor-result_t-alist r))))))
      (set! (.move (.in (.brick4_aC o)))
       (lambda (. args)
      (log-in "brick4_aC." 'move e)))
      (set! (.run (.in (.brick4_aC o)))
       (lambda (. args)
      (log-in "brick4_aC." 'run e)))
      (set! (.stop (.in (.brick4_aC o)))
       (lambda (. args)
      (log-in "brick4_aC." 'stop e)))
      (set! (.coast (.in (.brick4_aC o)))
       (lambda (. args)
      (log-in "brick4_aC." 'coast e)))
      (set! (.zero (.in (.brick4_aC o)))
       (lambda (. args)
      (log-in "brick4_aC." 'zero e)))
      (set! (.position (.in (.brick4_aC o)))
       (lambda (. args)
      (log-in "brick4_aC." 'position e)))
      (set! (.at (.in (.brick4_aC o)))
       (lambda (. args)
    (log-valued "brick4_aC." 'at e (lambda (s) (assoc-ref imotor-result_t-alist (string->symbol (drop-prefix s "brick4_aC.result_t_")))) (lambda (r) (symbol-append 'result_t_ (assoc-xref imotor-result_t-alist r))))))
      (set! (.detect (.in (.brick4_s1 o)))
       (lambda (. args)
    (log-valued "brick4_s1." 'detect e (lambda (s) (assoc-ref itouch-status-alist (string->symbol (drop-prefix s "brick4_s1.status_")))) (lambda (r) (symbol-append 'status_ (assoc-xref itouch-status-alist r))))))
      (set! (.detect (.in (.brick4_s2 o)))
       (lambda (. args)
    (log-valued "brick4_s2." 'detect e (lambda (s) (assoc-ref itouch-status-alist (string->symbol (drop-prefix s "brick4_s2.status_")))) (lambda (r) (symbol-append 'status_ (assoc-xref itouch-status-alist r))))))
      (set! (.detect (.in (.brick4_s3 o)))
       (lambda (. args)
    (log-valued "brick4_s3." 'detect e (lambda (s) (assoc-ref itouch-status-alist (string->symbol (drop-prefix s "brick4_s3.status_")))) (lambda (r) (symbol-append 'status_ (assoc-xref itouch-status-alist r))))))
      e))

(define (main . args)
  (let* ((print-illegal (lambda () (stderr "illegal\n") (exit 0)))
         (locator (make <locator>))
         (runtime (make <runtime> :illegal print-illegal))
         (sut (make <LegoBallSorter> :locator (set locator runtime) :name 'sut))
         (event-alist (fill-event-alist sut)))
    (while (and-let*
            ((line (read-line))
             ((not (eof-object? line))))
            (or (and-let* ((event (assoc-ref event-alist (string->symbol line))))
                          (event))
                #t)))))
