// Dezyne --- Dezyne command line tools
//
// Copyright © 2017 Jan Nieuwenhuizen <janneke@gnu.org>
//
// This file is part of Dezyne.
//
// Dezyne is free software: you can redistribute it and/or modify it
// under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// Dezyne is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public
// License along with Dezyne.  If not, see <http://www.gnu.org/licenses/>.
//
// Commentary:
//
// Code:

// /////////////////////////////////////////////////////////////////////////////
// 
// File generated by   : Verum ASD:Suite Release <by hand>
//
// /////////////////////////////////////////////////////////////////////////////

#ifndef __SIRENSIRENSIRENSIREN_INTERFACE_H__
#define __SIRENSIRENSIRENSIREN_INTERFACE_H__

#include <boost/shared_ptr.hpp>

#ifdef ASD_HAVE_CONFIG_H
  #include "asdConfig.h"
#else
  #include "asdDefConfig.h"
#endif

#include "asdPassByValue.h"
#include "asdInterfaces.h"



namespace siren
{
  class siren_api
  {
  public:
    enum PseudoStimulus {
      
      /// <summary>
      /// The VoidReply event indicates that the processing of the API call has been completed
      /// and the call can return when appropriate.
      /// </summary>
      VoidReply
    };
    virtual ~siren_api() {}
    virtual void reset() = 0;
    virtual void off() = 0;
    virtual void on() = 0;
  protected:
    siren_api() {}
  private:
    siren_api& operator = (const siren_api& other);
    siren_api(const siren_api& other);
  };

  class sirenInterface
  {
  public:
    virtual ~sirenInterface() {}
    virtual void GetAPI(boost::shared_ptr<siren_api>* api) = 0;
  protected:
    sirenInterface() {}
  private:
    sirenInterface& operator = (const sirenInterface& other);
    sirenInterface(const sirenInterface& other);
  };
}

#endif
