// Generated by dzn code from test/all/async_calling_context/async_calling_context.dzn
#include <dzn/container.hh>

#include "async_calling_context.hh"

#include <algorithm>
#include <cstring>

int to_int(std::string s){return std::stoi (s);}
bool to_bool(std::string s){return s == "true";}
void to_void(std::string){}

calling_context dzn_cc;

void
connect_ports (dzn::container< async_calling_context, std::function<void()>>& c)
{
  c.system.p.out.world = [&] (calling_context&, std::string s) {
    c.match("p.world");
    return dzn::call_out(&c, [&]{
      if(c.flush) c.dzn_rt.queue(&c).push([&]{
        if(c.dzn_rt.queue(&c).empty()) {
          std::clog << "p.<flush>" << std::endl;
          c.match("p.<flush>");
        }
      });}, c.system.p.meta, "world");};}

std::map<std::string,std::function<void()> >
event_map (dzn::container< async_calling_context, std::function<void()>>& c)
{
  c.system.p.meta.require.address = &c;
  c.system.p.meta.require.meta = &c.meta;
  c.system.p.meta.require.port = "p";

  return {{"illegal", []{std::clog << "illegal" << std::endl;}}
    ,{"error", []{std::clog << "sut.error -> sut.error" << std::endl; std::exit(0);}}
    , {"p.hello",[&]{
        std::string s;
        c.system.p.in.hello(dzn_cc, s);
        c.match("p.return");
      }}
    , {"a.ack",[&]{
       std::string s;
        c.system.a.out.ack(dzn_cc, s);
      }}
  };
}

int
main(int argc, char* argv[])
{
  bool flush = argv + argc != std::find_if(argv + 1, argv + argc, [](const char* s){return std::strcmp(s,"--flush") == 0;});
  if(argv + argc != std::find_if(argv + 1, argv + argc, [](const char* s){return std::strcmp(s,"--debug") == 0;})) dzn::debug.rdbuf(std::clog.rdbuf());
  dzn::container< async_calling_context, std::function<void()>> c(flush);

  connect_ports (c);
  c(event_map (c), {});
}
//version: 2.12.0.rc2.8-3d547
