;; This file is part of Gaiag, Guile in Asd In Asd in Guile.
;;
;; Copyright © 2014, 2015 Jan Nieuwenhuizen <janneke@gnu.org>
;; Copyright © 2015 Rutger van Beusekom <rutger.van.beusekom@verum.com>
;;
;; Gaiag is free software: you can redistribute it and/or modify
;; it under the terms of the GNU Affero General Public License as
;; published by the Free Software Foundation, either version 3 of the
;; License, or (at your option) any later version.
;;
;; Gaiag is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU Affero General Public License for more details.
;;
;; You should have received a copy of the GNU Affero General Public License
;; along with Gaiag.  If not, see <http://www.gnu.org/licenses/>.

(read-set! keywords 'prefix)

(define-module (gaiag run)
  :use-module (ice-9 curried-definitions)
  :use-module (ice-9 getopt-long)
  :use-module (ice-9 optargs)
  :use-module (ice-9 and-let-star)
  :use-module (srfi srfi-1)

  :use-module (gaiag list match)
  :use-module (language dezyne location)

  :use-module (gaiag gaiag)
  :use-module (gaiag json-trace)
  :use-module (gaiag misc)
  :use-module (gaiag evaluate)

  :use-module (gaiag pretty-print)
  :use-module (gaiag reader)

  :use-module (gaiag resolve)
  ;;  :use-module (gaiag wfc)

  :use-module (gaiag ast)

  :export (ast->
           explore-space
           mangle-traces
           walk-trail
           symbol->trigger
           ->symbol
           run:om))

(define MAX-ITERATIONS 400000)
(define (debug . x) #t)
(define (debug-pretty . x) #t)
(define (debug-state . x) #t)

(define (ast-> ast)
  (let ((name (and=> (option-ref (parse-opts (command-line)) 'model #f)
                     string->symbol))
        (json? (option-ref (parse-opts (command-line)) 'json #f)))
    (or (and-let* ((om ((om:register run:om) ast #t))
                   (models (filter (lambda (x) (or (is-a? x <interface>)
                                                   (is-a? x <component>)))
                                   (.elements om)))
                   (models (null-is-#f (filter .behaviour models)))
                   (models (if name (filter (om:named name) models) models))
                   (c-i (append (filter (is? <component>) models) models))
                   ((pair? c-i)))
                  (run-model (car c-i)))
        (if json? '()
            ""))))

(define (run:import name)
  (om:import name run:om))

(define (run:om ast)
  ((compose ;;ast:wfc
    ast:resolve ast->om) ast))

(define i 0)
(define *state-space* '(()))
(define *component* #f)  ;; FIXME

(define (run-model model)
  (stderr "\n\n>>>running: ~a ~a {~a}\n" (ast-name model) (.name model) (map ->string (om:find-triggers model)))
  (and-let* ((((is? <component>) model))
             (interfaces (map run:import
                              (map .type ((compose .elements .ports) model))))))
  (set! *component* ((is? <component>) model))
  (let* ((trail (option-ref (parse-opts (command-line)) 'trail #f))
         (traces (if trail
                     (walk-trail model (with-input-from-string trail read))
                     (explore-space model)))
         (traces (sort-traces traces))
         (trace (if (pair? traces) (car traces) '())))
    (pretty-print (mangle-traces model traces)))
  (newline)
  (stderr "state space: ~a\n" (length *state-space*))
  "")

(define (explore-space model)
  (run-trail model))

(define (walk-trail model trail)
  (run-trail model (next-info-trail-walker) trail))

(define* (run-trail model :optional (next-info next-info-space-explorer) (trail '()))
  (set! *state-space* '(()))
  (set! *component* ((is? <component>) model))
  (set! i 0)
  (let* ((ports (if (is-a? model <interface>) '() ((compose .elements .ports) model)))
         (state-alist (map (lambda (port) (cons (.name port) (state-vector (run:import (.type port))))) ports))
         (info (make <info> :trail trail :state (state-vector model) :state-alist state-alist)))
    (let loop ((info info) (trace '()))
      (debug "trail: <-- ~a\n" (.trail info))
      (debug-state model info)
      (if (or (null? (.trail info))
              (.error info))
          (let* ((eligible (if (.error info) '((eligible))
                               (list (eligible model info))))
                 (remaining (.trail info))
                 (error (if (not (.error info)) '()
                            (list (cons 'error remaining))))
                 (matched (drop-right trail (length remaining)))
                 (matched (if (not (eq? (.error info) 'illegal)) matched
                              (append (drop-right matched 1) (list (.error info)))))
                 (matched (list (cons 'matched matched))))
            (list (append trace error eligible matched)))
          (let* ((info (next-info model info))
                 (trail (.trail info)))
            (let* ((infos (run-trigger model info #f #t))
                   (infos (prune infos))
                   (infos (delete-duplicates infos equal?)))
              (append-map
               (lambda (info)
                 (let ((trail (list (cons 'trail (.trail info)))))
                   (loop info (append trace (.trace info) trail)))) infos)))))))

(define* (run-trigger model info :optional (flushing? #f) (top? #f))

  (define (run-modeling model info)
    (let* ((triggers (modeling-triggers model info)))
      (append-map (lambda (t) (prune ((run model t flushing? top?) info) info)) triggers)))

  (define (modeling-triggers model info)
    (let* ((trigger (symbol->trigger (car (.trail info))))
           (port (.port trigger))
           (triggers (map .event (om:find-triggers model)))
           (inevitable (and (member 'inevitable triggers) 'inevitable))
           (optional (and (member 'optional triggers) 'optional)))
      (map (lambda (event) (make <trigger> :port port :event event))
           (filter identity (list inevitable optional)))))

  (define (run-trigger-from-trail info)
    (let* ((info (next-trigger model info flushing?))
           (trigger (.return info))
           (info (if (not (and *component* (is-a? model <interface>))) info
                     (skip-trail info (.port trigger))))
           (info (clone info :return 'return))
           (triggers (if (or (and (is-a? model <interface>) (trigger? model trigger))
                             (not (and *component* (is-a? model <interface>)))) (list trigger)
                             (modeling-triggers model info))))
      (prune (append-map (lambda (t) ((run model t flushing? #t) info)) triggers))))

  (define (run-from-trail info)
    (let* ((trigger (symbol->trigger (car (.trail info))))
           (i-info (clone info :trace '()))
           (i-infos (run-interface model trigger i-info #f #t))
           (i-success (filter success? i-infos))
           (i-infos (if (pair? i-success) i-success i-infos))
           (foo (and (pair? i-infos) (debug-pretty (map trace-location (.trace (car i-infos))) (current-error-port))))
           (infos (if (pair? i-success) i-infos
                      (map (set-fields :error #f) i-infos)))
           (infos (if (and (is-a? model <component>)
                           (required-out? model trigger))
                      (append-map (flush model) infos)
                      (append-map run-trigger-from-trail infos)))
           (infos (if (or (null? i-infos) (pair? i-success)) infos
                      (map (set-fields :error (.error (car i-infos))) infos))))
      (if (and (is-a? model <component>)
               (required-out? model trigger))
          infos
          (map
           (lambda (i-info info)
             ((set-trace (append (.trace i-info) (.trace info))) info))
           i-infos infos))))

  (debug "\n\nrun-trigger[~a, ~a]: flushing?:~a top:~a\n" (.name model) (->symbol (car (.trail info))) flushing? top?)
  (debug-state model info)
  (debug "trigger: ~a\n" (->string (car (.trail info))))
  (let* ((ast ((compose .statement .behaviour) model))
         (info (clone info :ast ast))
         (trigger (symbol->trigger (car (.trail info))))
         (infos (if (and (is-a? model <component>) (not flushing?)) (run-from-trail info)
                    (run-trigger-from-trail info))))
    (if (is-a? model <component>) infos
        (let* ((trigger (symbol->trigger (car (.trail info))))
               (run-modeling?
                (and top?
                     (or (not *component*)
                         (eq? (.direction (om:port *component* (.port trigger))) 'requires)))))
          (if (not run-modeling?) infos
              (append infos (run-modeling model info)))))))

(define* ((run model trigger :optional (flushing? #f) (top? #f)) info)
  (define (trigger-matches? t)
    (let ((r (if (is-a? model <interface>) (eq? (.event t) (.event trigger))
                 (and (eq? (.port t) (.port trigger))
                      (eq? (.event t) (.event trigger))))))
      (debug "MATCH?: ~a == ~a ==> ~a\n" (->symbol t) (->symbol trigger) r)
      r))
  (debug "\nrun[~a, ~a]: ~a trail:~a\n" (.name model) (->symbol trigger) (ast-name (.ast info)) (map ->symbol (.trail info)))
  (debug "flushing: ~a, top: ~a, q: ~a\n" flushing? top? (.q info))
  (debug-state model info)
  (debug-pretty (map trace-location (.trace info)) (current-error-port))
  (set! i (1+ i))
  (if (> i MAX-ITERATIONS)
      (throw 'break (format #f "too many iterations: ~a, state space: ~a\n" i
                            (length *state-space*))))
  (let* ((ast (.ast info))
         (info+ast ((cons-trace ast) info))
         (orig-states (copy-tree (.state-alist info)))
         (port (.port trigger))
         (state (.state info))
         (trace (.trace info)))
    (match (.ast info)
      ((and ('compound statements ...) (? om:declarative?))
       (let loop ((statements statements) (loop-infos '()))
         (if (null? statements)
             (let* ((loop-infos (prune loop-infos)))
               loop-infos)
             (let* ((statement (car statements))
                    (info (clone info :ast statement :trace '()))
                    (infos ((run model trigger flushing? top?) info))
                    (infos (prune infos)))
               (if (pair? infos)
                   (append-map (lambda (info) (loop (cdr statements) (cons info loop-infos))) infos)
                   (loop (cdr statements) loop-infos))))))
      (($ <guard> expression statement)
       (if (eval-expression model state expression)
           (let* ((g-info (clone info :ast statement :trace '()))
                  (infos ((run model trigger flushing? top?) g-info))
                  (infos (prune infos))
                  (infos (map (append-trace (cons ast trace)) infos)))
             infos)
           '()))
      (($ <on> ('triggers triggers ...) statement)
       (debug "on[~a, ~a]: ~a, ~a\n" (.name model) (->symbol (car triggers)) (->symbol trigger) (.trail info))
       (if (not (find trigger-matches? triggers)) '()
           (let* ((on-info (clone info :ast statement :trace '()))
                  (info+ast ((cons-trace ast) ((cons-trace trigger) info)))
                  (infos
                   (cond
                    ((is-a? model <interface>)
                     ((run model trigger flushing? top?) on-info))
                    ((and flushing? (eq? (.direction (om:port model port)) 'requires))
                     (let* ((infos ((run model trigger flushing? top?) on-info)))
                       ;; FIXME: mark this info+ast with a NULL trigger
                       ;; so that it will be omitted from the ouput trail.
                       ;; We do want the AST, however, in the trace output.
                       (set! info+ast ((cons-trace ast) ((cons-trace (make <trigger>)) info)))
                       (append-map (flush model) infos)))
                    (else
                     (let* ((infos ((run model trigger flushing? top?) on-info)))
                       (append-map (flush model) infos)))))
                  (infos (prune infos))
                  (infos (if (and *component*
                                  (is-a? model <interface>)
                                  (eq? (.direction (om:port *component* port)) 'requires)) infos
                          (map (handle-return model trigger trigger ast) infos))))
             (map
              (lambda (info)
                ((set-trace (reverse (append
                                      (reverse (.trace info))
                                      (.trace info+ast)))) info))
              infos))))
      (('compound statements ...)
       (debug "ENTER IMPERATIVE[~a, ~a]: ~a\n" (.name model) (length statements) (and (pair? statements) (ast-name (car statements))))
       (let loop ((statements statements) (loop-info info+ast) (frame 0))
         (if (or (null? statements)
                 (and
                  (.error loop-info)
                  (debug "BAILING COMPOUND[~a]: ~a\n" (.name model) (if (null? statements) '()  (car statements)))))
             (list (clone loop-info :ast '() :state (drop (.state loop-info) frame)))
             (let ((statement (car statements)))
               (let* ((foo (debug "IMPERATIVE[~a, ~a]: ~a\n" (.name model) (length statements) (ast-name statement)))
                      (state (if (is-a? statement <variable>)
                                 (acons (.name statement)
                                        #f (.state loop-info)) (.state loop-info)))
                      (frame (if (is-a? statement <variable>)
                                 (1+ frame) frame))
                      (info (clone loop-info :ast statement :state state :trace '()))
                      (infos ((run model trigger flushing?) info))
                      (infos (prune infos))
                      (infos (map (append-trace (.trace loop-info)) infos)))
                 (append-map (lambda (info) (loop (cdr statements) info frame)) infos))))))
      (('compound) (list info+ast))
      (($ <action> action)
       (debug "action[~a, ~a]: ~a\n" (.name model) (->symbol action) (.trail info))
       (let* ((infos
               (if (is-a? model <interface>)
                   (cond
                    ((not *component*)
                     (list (next-action model info trigger action)))
                    ((eq? (.direction (om:port *component* port)) 'requires)
                     (let ((info (next-queue? model info trigger action)))
                       (if (.error info) '()
                           (let* ((info (enq model info (.return info)))
                                  (q-trigger (.return info))
                                  (synth-ast (rsp ast (make <action> :trigger q-trigger)))
                                  (q (.q info))
                                  (info ((cons-trace `((q ,q-trigger))) info))
                                  (info (if (null? (.q info)) info
                                            ((cons-trace synth-ast) info)))

                                  (port (or port (.name (om:port *component*))))
                                  (info (skip-trail info port)))
                             (list info)))))
                    (else
                     (let* ((info (next-action model info trigger action))
                            (port (or (.port trigger) (.name (om:port *component*))))
                            (info (skip-trail info port)))
                       (list info))))
                   ;; else: component
                   (let* ((action-port (.port action))
                          (on-dir (.direction (om:port model port)))
                          (action-dir (.direction (om:port model action-port)))
                          (action-info (clone info :trace '()))
                          (info (next-action model info trigger action))
                          (infos
                           (if (or (eq? on-dir action-dir 'provides)
                                   (and (eq? on-dir 'requires)
                                        (eq? action-dir 'provides)
                                        (not (modeling-triggered? model action))))
                               (list info)
                               (let* ((action-info-TODO (clone info :trace '())))
                                 (run-interface-action model action action-info-TODO flushing?)))))
                     (map (handle-return model trigger action ast) infos)))))
         (map (lambda (info)
                ((set-trace (reverse (append (reverse (.trace info))
                                             (.trace info+ast)))) info))
              infos)))
      (($ <assign> identifier expression)
       (debug "assign[~a, ~a]: ~a\n" (.name model) identifier (.trail info))
       (let* ((infos (eval-function-expression model trigger (clone info :ast expression)))
              (set-var (lambda (info)
                         (debug "  assign var[~a]: ~a := ~a\n" (.name model) identifier (.return info))
                         (var! (.state info) identifier (.return info))))
              (infos (map (modify-field :state set-var) infos))
              (infos (map cons-state infos))
              (infos (map (cons-trace ast) infos)))
         infos))
      (($ <call> function ('arguments arguments ...))
       (debug "void call[~a, ~a]: ~a\n" (.name model) function (.trail info))
       (let ((infos (eval-function-expression model trigger info+ast)))
         infos))
      (($ <if> expression then #f)
       (let ((info info+ast)
             (value (eval-expression model state expression)))
         (debug "<if>[~a] at: ~a\n" (.name model) (trace-location ast))
         (debug "expr ~a ==> ~a\n" expression value)
         (if value
             ((run model trigger flushing?) (clone info :ast then))
             (list info))))
      (($ <if> expression then else)
       (let ((info info+ast)
             (value (eval-expression model state expression)))
         (debug "<if>[~a] at: ~a\n" (.name model) (trace-location ast))
         (debug "expr ~a ==> ~a\n" expression value)
         (if value
             ((run model trigger flushing?) (clone info :ast then))
             ((run model trigger flushing?) (clone info :ast else)))))
      (($ <illegal>)
       (let ((info (clone (next-illegal model info+ast))))
         (list info)))
      (($ <reply> expression)
       (let* ((reply (eval-expression model state expression)))
         (debug "reply[~a]: ~a\n" (.name model) reply)
         (list (clone info+ast :reply reply))))
      (($ <return> expression)
       (let ((return (eval-expression model state expression)))
         (debug "return[~a, ~a]: ~a\n" (.name model) expression (.trail info))
         (list (clone info+ast :return return))))
      (($ <variable> identifier type expression)
       (debug "variable[~a, ~a]: ~a\n" (.name model) identifier (.trail info))
       (let* ((infos (eval-function-expression model trigger (clone info :ast expression)))
              (set-var (lambda (info)
                         (debug "  init var[~a]: ~a := ~a\n" (.name model) identifier (.return info))
                         (var! (.state info) identifier (.return info))))
              (infos (map (modify-field :state set-var) infos))
              (infos (map cons-state infos))
              (infos (map (cons-trace ast) infos)))
         infos))
      (#f '())
      (() (debug "NULL AST?!") '()))))

(define (eval-function-expression model trigger info)
  (let* ((members (om:member-names model))
         (expression (.ast info)))
    (match expression
      (($ <call>) (=> failure)
       (if (or (pair? (.trail info)) (eq? next-trail-empty next-trail-empty-reject)) (failure)
           (and (debug "BAIL RECURSION\n") (list info))))
      (($ <call> function ('arguments arguments ...))
       (debug "valued call[~a, ~a]: ~a\n" (.name model) function (.trail info))
       (let* ((f (om:function model function))
              (formals (map .name ((compose .elements .formals .signature) f)))
              (statement (.statement f))
              (pairs (zip formals arguments))
              (state (.state info))
              (state (let loop ((pairs pairs) (state state))
                       (if (null? pairs) state
                           (loop (cdr pairs) (acons (caar pairs)
                                                    (eval-expression model state (cadar pairs)) state)))))
              (info (cons-state info))
              (info ((cons-trace f) info))
              (info (clone info :ast statement :state state))
              (infos ((run model trigger) info))
              (infos (prune infos))
              (drop-formals (lambda (info) (clone info :state (drop (.state info) (length formals)))))
              (infos (map drop-formals infos)))
         infos))
      (($ <action> action)
       (map (modify-field :return .reply) ((run model trigger) info)))
      (_ (let ((return (eval-expression model (.state info) expression)))
           (list (clone info :return return)))))))

(define ((extern? model) var) (om:extern model (.type var)))
(define (om:member-names model)
  (map .name (filter (negate (extern? model)) (om:variables model))))

(define* (run-interface model trigger component-info flushing? :optional (top? #f))
  (debug "run-interface[~a, ~a]\n" (.name model) (->symbol trigger))
  (let*
      ((port (.port trigger))
       (scope (.type (om:port model port)))
       (interface (run:import scope))
       (trace (.trace component-info))
       (i-state (get-state component-info port))
       (i-info (clone component-info :q '() :state i-state :trace '()))
       (i-infos (run-trigger interface i-info flushing? top?))
       (i-infos (map (modify-trace reverse) i-infos))
       (infos (map (transfer-interface-info model trigger component-info) i-infos))
       (infos (prune infos)))
    infos))

(define* (run-interface-action model trigger component-info flushing? :optional (top? #f))
  (debug "run-interface-action[~a, ~a]\n" (.name model) (->symbol trigger))
  (let*
      ((port (.port trigger))
       (scope (.type (om:port model port)))
       (interface (run:import scope))
       (trace (.trace component-info))
       (i-state (get-state component-info port))
       (i-info (clone component-info :q '() :state i-state :trace '()))
       ;;
       (i-info (clone i-info :trail (cons (->symbol trigger) (.trail i-info))))
       (i-infos (run-trigger interface i-info flushing? top?))
       (i-infos (map (modify-trace reverse) i-infos))
       (infos (map (transfer-interface-info model trigger component-info) i-infos))
       ;;(infos (map (lambda (info) (next-action model info trigger trigger)) infos))
       (infos (prune infos)))
    infos))

(define ((transfer-interface-info model trigger component-info) i-info)
  (let* ((port (.port trigger))
         (scope (.type (om:port model port)))
         ;; Strip any events in Q from component trail.
         (trail (let loop ((q (.q i-info)) (trail (.trail component-info)))
                  (if (or (null? q) (null? trail)) trail
                      (let ((a (->symbol (car q)))
                            (t (car trail)))
                        (if (eq? a t) (loop (cdr q) (cdr trail))
                            (loop q (cdr trail)))))))
         (component-info (clone component-info :trail trail))
         (q (append (.q component-info) (.q i-info)))
         (reply (.reply i-info))
         (reply (if (is-a? reply <literal>) reply
                    (make <literal> :field 'return)))
         (trace (.trace component-info))
         (trace (append trace (reverse (.trace i-info))))
         (info (clone component-info :trail trail :q q :reply (make <literal> :scope scope :type (.type reply) :field (.field reply)) :trace trace :error (.error i-info))))
    (set-state info port (.state i-info))))

(define ((flush model) component-info)
  (debug "flush: component-info: q: ~a\n" (.q component-info))
  (debug "flush: component-info: trail: ~a\n" (.trail component-info))
  (let loop ((info component-info))
    (debug "q: ~a\n" (.q info))
    (if (not (peeq info))
        (list info)
        (let* ((trigger (peeq info))
               (info (deq info))
               (port (.port trigger))
               (info (clone info :trail (cons (->symbol trigger) (.trail info)) :trace '()))
               (info (clone info :trace '()))
               (foo (debug "flush feeding: ~a\n" (.trail info)))
               (info (clone info :trace '() ))
               (infos (run-trigger model info #t))
               (infos (prune infos))
               (complete-trace (lambda (t) (append (.trace component-info) t)))
               (infos (map (modify-trace complete-trace) infos)))
          (append-map loop infos)))))

(define ((handle-return model trigger action ast) info)
  (let* ((port (.port action))
         (interface (if (is-a? model <interface>) model
                        (run:import (.type (om:port model port))))))
    (if (modeling-or-required-out? interface action)
        info
        (let* ((info (if (om:typed? model action)
                         (next-reply model info action)
                         (next-return model info action)))
               (return (->symbol (.return info)))
               (return (rsp ast (make <return> :expression return))))
          (if (or (.error info)
                  (and (.port action) (is-a? model <interface>)))
              ((set-trace (.trace info)) info)
              ((set-trace (append (.trace info) (list return))) info))))))

(define (eligible model info)
  (set! next-trail-empty next-trail-empty-allow)
  (let ((eligible
         (cons
          'eligible
          (if (.error info)
              '()
              (filter identity
                      (map
                       (lambda (trigger)
                         (let* ((infos (run-trigger model (clone info :trail (list (->symbol trigger)))))
                                (infos (prune infos info)))
                           (and (pair? infos) (->symbol trigger))))
                       (om:find-triggers model)))))))
    (set! next-trail-empty next-trail-empty-reject)
    eligible))

(define (eligible model info) '((eligible)))

(define (modeling? trigger) (member (.event trigger) '(inevitable optional)))

(define (action? model trigger)
  (if (is-a? model <interface>) (let ((triggers (map .event (om:find-triggers model))))
                                  (not (member (.event trigger) triggers)))
      (let* ((port (.port trigger))
             (scope (om:port model port))
             (interface (run:import (.type scope))))
        (find (lambda (event)
                (or (and (eq? (.name event) (.event trigger))
                         (and (eq? (.direction scope) 'provides)
                              (eq? (.direction event) 'out)))
                    (and (eq? (.name event) (.event trigger))
                         (and (eq? (.direction scope) 'requires)
                              (eq? (.direction event) 'in)))))
              ((compose .elements .events) interface)))))

(define (trigger? model trigger)
  (let* ((triggers (om:find-triggers model)))
    (if (is-a? model <interface>)
        (find (lambda (t) (eq? (.event t) (.event trigger))) triggers)
        (find (lambda (t) (trigger-equal? t trigger)) triggers))))

(define (required-out? model trigger)
  (let* ((port (.port trigger))
         (scope (om:port model port)))
    (and (eq? (.direction scope) 'requires)
         (and-let* ((interface (run:import (.type scope)))
                    (event (om:event interface (.event trigger))))
                   (eq? (.direction event) 'out)))))

(define (modeling-or-required-out? model trigger)
  (or (modeling? trigger)
      (if (is-a? model <interface>) (not (trigger? model trigger))
          (required-out? model trigger))))

(define (modeling-triggered? model trigger)
  (let* ((port (.port trigger))
         (scope (om:port model port))
         (interface (run:import (.type scope))))
    (null-is-#f (filter modeling? (triggers-for-action interface trigger)))))

(define (action-triggers o)
  (map .trigger ((collect (is? <action>)) o)))

(define (triggers-for-action model action)
  (let* ((ons ((collect (is? <on>)) model))
         (event (.event action))
         (on-actions (map (lambda (on) (cons ((compose car .elements .triggers) on) (map (compose .event .trigger) ((collect (is? <action>)) on)))) ons))
         (on-actions (filter (lambda (x) (member event (cdr x))) on-actions)))
    (map car on-actions)))

(define ((append-trace trace) info)
  (clone info :trace (append trace (.trace info))))
(define ((set-trace trace) info)
  (clone info :trace trace))
(define ((cons-trace trace) info)
  (clone info :trace (cons trace (.trace info))))
(define (cons-state info)
  ((cons-trace `(state ,(.state info))) info))
(define ((modify-trace modify) info)
  (clone info :trace (modify (.trace info))))
(define ((modify-field field modify) info)
  (clone info field (modify info)))
(define ((set-fields . args) info)
  (apply clone (cons info args)))
(define (trace? info) (null-is-#f (.trace info)))
(define (success? info) (not (.error info)))
(define* (prune infos :optional (info #f))
  (define (progress? i)
    (or (< (length (.trail i)) (length (.trail info)))
        (not (equal? (.state i) (.state info)))
        (if (is-a? info <interface>) #f
            (not (equal? (.state-alist i) (.state-alist info))))))
  (let* ((infos (filter trace? infos))
         (infos (if (not info) infos
                    (filter progress? infos)))
         (success (filter success? infos)))
    (if (pair? success) success infos)))

(define (sort-traces traces)
  (define (.error o) (assq 'error o))
  (define (error? o) (assoc-ref o 'error))
  (define (.trail o) (or (assq-ref o 'error) '()))
  (define (.trace o) o)
  (define success? (negate .error))
  (define (pessimist< a b)
    (cond
     ((not (eq? (and (error? a) #t) (and (error? b) #t)))
      (error? b))
     ((= (length (.trail a)) (length (.trail b)))
      (< (length (.trace a)) (length (.trace b))))
     ((!= (length (.trail a)) (length (.trail b)))
      (< (length (.trail a)) (length (.trail b))))
     (else
      (cond ((error? a) #t)
            ((error? b) #f)))))
  (let* ((traces (stable-sort traces pessimist<)))
    (if (or (null? traces) (error? (car traces))) traces
        (filter success? traces))))

(define (mangle-traces model traces)
  (let ((json? (option-ref (parse-opts (command-line)) 'json #f)))
    (if json?
        (append
         (list
          (json-init model)
          (json-state model (state-vector model)))
         (let ((trace (if (null? traces) '() (car traces)))) ;; FIXME JSON only gets 1st trace
           (json-trace model trace)))
        (if (null? traces)
            (debug "ERROR: no matching trace\n")
            (map demo-trace traces (iota (length traces)))))))

(define (trace-location ast)
  (or (and-let* ((loc (source-location ast))
                 (properties (source-location->user-source-properties loc)))
                (format #f "~a:~a:~a"
                        (assoc-ref properties 'filename)
                        (assoc-ref properties 'line)
                        (assoc-ref properties 'column)))
      ast))

(define <state> 'state)
(define (demo-trace trace count)
  (stderr "\n\nRESULT: ~a\n" count)
  (pretty-print trace (current-error-port))
  (pretty-print (map demo-tracepoint trace) (current-error-port))
  (stderr "END RESULT[~a]\n" count))

(define (demo-tracepoint step)
  (match step
    (($ <state> state ...) (state->string state))
    (($ <trigger>) (->symbol step))
    (_ (trace-location step))))

(define (symbol->trigger event)
  "if EVENT is of form [PORT.]TRIGGER, produce (trigger [PORT] EVENT)"
  (match (symbol-split event #\.)
    ((event) (make <trigger> :event event))
    ((#f event) (make <trigger> :event event))
    ((port event) (make <trigger> :port port :event event))
    (_ ;;(throw 'runtime-error (format #f "not a trigger: ~a\n" event))
     (debug "not a trigger: ~a\n" event)
     #f)))

(define (next-trigger model info flushing?)
  (let* ((trail (.trail info)))
    (if (null? trail)
        info
        (let* ((trigger (symbol->trigger (car trail)))
               (info (clone info :return trigger :trace (cons trigger (.trace info))))
               (modeling-or-required-out? (modeling-or-required-out? model trigger))
               (foo (debug "MODELING-OR-REQUIRED-OUT?[~a, ~a]: ~a\n" (.name model) (car trail) modeling-or-required-out?)))
          (if (and (is-a? model <interface>)
                   modeling-or-required-out?)
              info
              (clone info :trail (cdr (.trail info))))))))

(define (next-action model info trigger action)
  (let ((trail (.trail info)))
    (debug "next-action[~a ~a]: ~a\n" (.name model) action trail)
    (cond
     ((null? trail) (next-trail-empty model info 'action (->symbol action)))
     (else
      (let* ((next (symbol->trigger (car trail))))
        (debug "NEXT: ~a\n" next)
        (debug "EXPECT ACTION: ~a\n" action)
        (if (or (trigger-equal? next action)
                (and (is-a? action <trigger>)
                     (is-a? next <trigger>)
                     (not (.port action))
                     (eq? (.event action) (.event next))))
            (clone info :trail (cdr (.trail info)))
            (and
             (debug "REJECT-TRACE: ACTION[~a expect:~a]: next:~a\n" (.name model) action next)
             ((cons-trace
               (list 'reject 'action (.name model) 'next next 'expected action))
              (clone info :error #t)))))))))

(define (next-illegal model info)
  (let* ((trail (.trail info)))
    (debug "next-illegal[~a]: ~a\n" (.name model) trail)
    (if (null? trail)
        (next-trail-empty model info 'illegal 'illegal)
        (let* ((next (car trail)))
          (if (eq? next 'illegal)
              (clone info :trail (cdr trail) :return next :error #t) ;; FIXME: illegal was matched, is that an error?
              (and
               (debug "REJECT-TRACE: ILLEGAL[~a expect:~a]: next:~a\n" (.name model) 'illegal next)
               ((cons-trace
                 (list 'reject 'illegal (.name model) 'next next 'expected 'illegal))
                (clone info :error 'illegal))))))))

(define (trigger-equal? a b)
  (and (eq? (.port a) (.port b)) (eq? (.event a) (.event b))))

(define (next-queue? model info trigger action)
  (let ((trail (.trail info))
        (port (.port action))
        (event (.event action)))
    (debug "next-queue?[~a ~a]: ~a trail: ~a\n" (.name model) port (->symbol action) trail)
    (if (null? trail)
        (clone info :error #t)
        (let* ((next (symbol->trigger (car trail)))
               (n-port (.port next)))
          (if (and (eq? (.event next) event)
                   n-port
                   (eq? (.direction (om:port *component* n-port)) 'requires))
              (clone info :trail (cdr trail) :return next)
              (and
               (debug "NOT-Q-ABLE: QUEUE[~a expect:~a]: next:~a\n" (.name model) "??" next)
               (clone info :error #t)))))))

(define (next-reply model info trigger)
  "eat a 'RETURN or PORT.'RETURN from trail, or error"
  (debug "next-reply[~a]: ~a\n" (.name model) (.reply info))
  (debug "trail: ~a\n" (.trail info))
  (let* ((port (.port trigger))
         (trail (.trail info)))
    (if (null? trail)
        (next-trail-empty model info 'reply (->symbol trigger))
        (let* ((reply (.reply info))
               (next (symbol->literal model (car trail)))
               (port (and (is-a? model <component>) (.scope next)))
               (scope (and port (is-a? model <component>) (.type (om:port model port))))
               (reply (make <literal> :scope scope :type (.type reply) :field (.field reply)))
               (next-reply (make <literal> :scope scope :type (.type next) :field (.field next))))
          (if (and (is-a? model <component>) (not port))
              (throw 'runtime-error "component-reply-without-port"))
          (if (equal? next-reply reply)
              (clone info :trail (cdr trail) :return next :reply reply)
              (and
               (debug "REJECT-TRACE: REPLY[~a expect:~a]: next:~a\n" (.name model) reply next-reply)
               (debug "trace: ~a\n" (map trace-location (.trace info)))
               ((cons-trace
                 (list 'reject 'reply (.name model) 'next next-reply 'expected reply))
                (clone info :error #t))))))))

(define (next-return model info trigger)
  "eat a 'RETURN or PORT.'RETURN from trail, or error"
  (debug "next-return[~a]: ~a\n" (.name model) (.trail info))
  (let* ((event (.event trigger)))
    (if (modeling? trigger) info
        (let* ((port (.port trigger))
               (trail (.trail info))
               (port (and (is-a? model <component>) (.port trigger)))
               (return (make <trigger> :port port :event 'return))
               (port (.port trigger))
               (port (if (modeling? trigger) event port))
               (reply (make <trigger> :port port :event 'return)))
          (debug "next-return: trigger: ~a\n" (->symbol trigger))
          (if (null? trail)
              (next-trail-empty model info 'return (->symbol trigger))
              (let ((next (symbol->trigger (car trail))))
                (cond ((or (trigger-equal? next reply)
                           (and (not (.port reply))
                                (eq? (.event next) (.event reply))))
                       (clone info :trail (cdr trail) :return return))
                      ((and (eq? (car trail) 'illegal)
                            (is-a? model <component>))
                       ;; interface already matched illegal, we need a return!
                       (clone info :trail (cdr trail) :return return))
                      (else
                       (debug "REJECT-TRACE: RETURN[~a expect:~a] next: ~a\n" (.name model) reply next)
                       (debug "trail: ~a\n" (.trail info))
                       (debug "AT: ~a\n" (trace-location (.ast info)))
                       ((cons-trace
                         (list 'reject 'return (.name model) 'next next 'expected reply))
                        (clone info :reply (make <literal>) :error (or (.error info) #t)))))))))))

(define (next-value model info trigger action)
  "eat a ENUM_FIELD or PORT.ENUM_FIELD from trail, or error"
  (let* ((info (next-action model info trigger action))
         (trail (.trail info)))
    (debug "next-value[~a ~a]: ~a\n" (.name model) action trail)
    (if (null? trail)
        (next-trail-empty model info 'value (->symbol action))
        (let* ((value (car trail))
               (return (symbol->literal model value))
               (reply (if (and #f (is-a? model <interface>)) return
                          (let* ((port (.port action))
                                 (scope (.type (om:port model port))))
                            (make <literal> :scope scope :type (.type return) :field (.field return)))))
               (return (make <return> :expression return)))
          (debug "SETTING reply[~a]: ~a\n" (.name model) reply)
          (clone info :trail (cdr (.trail info)) :reply reply)))))

(define (next-trail-empty-reject model info name o)
  (debug "REJECT-TRACE ~a[~a]: ~a NULL\n" (.name model) name o)
  (clone info :error (or (.error info) name)))
(define (next-trail-empty-allow model info name o) info)
(define next-trail-empty next-trail-empty-reject)
;;(define next-trail-empty next-trail-empty-allow)

(define (symbol->literal model literal)
  (let* ((port-value (symbol-split literal #\.))
         (port (and (=2 (length port-value)) (car port-value)))
         (value (if (=2 (length port-value)) (cadr port-value) (car port-value)))
         (type-field (symbol-split value #\_))
         (type (and (=2 (length type-field)) (car type-field)))
         (field (if (=1 (length type-field)) (car type-field) (cadr type-field)))
         (port-def (and port (is-a? model <component>) (om:port model port)))
         (scope (or (and port-def (.name port-def)) port)))
    (make <literal> :scope scope :type type :field field)))

(define (skip-trail info port)
  (if (not port) barf-no-port)
  (let loop ((info info))
    (debug "SKIP-LOOP[~a]: ~a\n" port (.trail info))
    (let ((trail (.trail info)))
      (if (or (null? trail)
              (let ((trigger (symbol->trigger (car trail))))
                (or (not trigger)
                    (not (.port trigger))
                    (eq? (.port trigger) port))))
          info
          (loop (clone info :trail (cdr trail)))))))

(define (next-info-trail-walker)
  (lambda (model info)
    info))

(define (get-state info name)
  (assoc-ref (.state-alist info) name))

(define (set-state info name state)
  (clone info :state-alist (acons name state (filter (lambda (x) (not (eq? (car x) name))) (.state-alist info)))))

(define (state->string state)
  (comma-space-join (map (lambda (s) (->string (list (car s) "=" (cdr s)))) state)))

(define (clone o . args)
  (let-keywords
   args #f
   ((trail (.trail o))
    (ast (.ast o))
    (state (.state o))
    (q (.q o))
    (reply (.reply o))
    (return (.return o))
    (state-alist (.state-alist o))
    (trace (.trace o))
    (error (.error o)))
   (make <info> :trail trail :ast ast :state state :q q :reply reply :return return :state-alist state-alist :trace trace :error error)))

(define (enq model info trigger)
  (debug "ENQ!: ~a\n" trigger)
  (clone info :q (append (.q info) (list trigger))))

(define (deq info)
  (clone info :q (cdr (.q info))))

(define (peeq info)
  (and (pair? (.q info)) (car (.q info))))

(define (appendq info add)
  (clone info :q (append (.q info) (.q add))))

(define (->string h . t)
  (let ((src (if (pair? t) (cons h t) h)))
    (match src
      (#f "false")
      (#t "true")
      (($ <expression> expression) (->string expression))
      (($ <var> identifier) (symbol->string identifier))
      (($ <field> type field) (->string (list (->string type) "." field)))
      (($ <literal> scope type field) (->string (list (->string type) "_" (->string field))))
      (($ <trigger> #f event) (->string event))
      (($ <trigger> port event) (->string (list port "." event)))
      (('type name) (->string name))
      (($ <call> function ('arguments arguments ...)) (->string (list function "("  (comma-join arguments) ")" )))
      ((h ... t) (apply string-append (map ->string src)))
      (((h ... t)) (->string (car src)))
      (_ ((@ (gaiag misc) ->string) src)))))

(define (unspecified? x) (eq? x *unspecified*))
(define (->symbol src)
  (match src
    (#f 'false)
    (#t 'true)
    (($ <expression> expression) (->symbol expression))
    (($ <var> identifier) identifier)
    (($ <field> type field) (->symbol (list (->symbol type) "." field)))
    (($ <literal> #f type field) (->symbol (list (->symbol type) "_" (->symbol field))))
    (($ <literal> scope type field) (->symbol (list scope '. type '_  field)))
    (($ <trigger> #f event) (->symbol event))
    (($ <trigger> port event) (->symbol (list port "." event)))
    ((h ... t) (apply symbol-append (map ->symbol src)))
    (((h ... t)) (->symbol (car src)))
    ((? string?) (string->symbol src))
    ((? number?) (number->symbol src))
    ((? symbol?) src)
    ((h . t) (->symbol (list (->symbol h) '. (->symbol t))))
    ((h . t) 'URG-CONS-BUG)
    (() 'URG-NULL-BUG)
    ((? unspecified?) '*unspecfied*)
    ))

;; model checker...broken for now -- keep interface
(define (next-info-space-explorer model info)
  (lambda (model info)
    info))

(define (print-state model info)
  (stderr "state[~a]\n    ~a\n" (.name model) (string-sub ", " "\n     " (state->string (.state info))))
  (if (is-a? model <component>)
      (for-each (lambda (s) (stderr "  [~a]: ~a\n" (car s) (state->string (cdr s)))) (.state-alist info))))

(define debug-pretty pretty-print)
(define debug stderr)
(define debug-state print-state)
