#! /bin/sh
# -*- scheme -*-
self=$(readlink -f $(cut -d '' -f2 < /proc/$$/cmdline))
prefix=$(cd $(dirname $self) && pwd)
GUILE_LOAD_PATH="$prefix:$prefix/module:$GUILE_LOAD_PATH"
GUILE_LOAD_COMPILED_PATH="$prefix/ccache:$prefix/../build/ccache:$GUILE_LOAD_COMPILED_PATH"
export GUILE_LOAD_PATH GUILE_LOAD_COMPILED_PATH
spec=language/dezyne/spec
[ "$(basename $(cd $(dirname $0); pwd))" = "gaiag" ] && type guile-2.2 >/dev/null && GUILE=${GUILE-guile-2.2}
[ -f $prefix/ccache/$spec.go ] || ${GUILE-guile} $prefix/module/$spec.scm
exec ${GUILE-guile} --debug -e main -s $0 "$@"
!#
;; This file is part of Gaiag, Guile in Asd In Asd in Guile.

;;(format (current-error-port) "%load-path ~a\n" %load-path )
;;(format (current-error-port) "%load-compiled-path ~a\n" %load-compiled-path )
(define (main . args)
  ((@ (g gaiag) main) (command-line)))
