#! /bin/sh
# -*- scheme -*-
self=$(readlink -f $(cut -d '' -f2 < /proc/$$/cmdline))
prefix=$(cd $(dirname $self) && pwd)
GUILE_LOAD_PATH="$prefix:$prefix/module:$GUILE_LOAD_PATH"
GUILE_LOAD_COMPILED_PATH="$prefix/ccache:$GUILE_LOAD_COMPILED_PATH"
export GUILE_LOAD_PATH GUILE_LOAD_COMPILED_PATH
spec=language/dezyne/spec
[ -f $prefix/ccache/$spec.go ] || ${GUILE-guile} $prefix/module/$spec.scm
exec ${GUILE-guile} --debug -e main -s $0 "$@"
!#
;; This file is part of Gaiag, Guile in Asd In Asd in Guile.
;;
;; Copyright (C) 2014  Jan Nieuwenhuizen <janneke@gnu.org>
;;
;; Gaiag is free software: you can redistribute it and/or modify
;; it under the terms of the GNU Affero General Public License as
;; published by the Free Software Foundation, either version 3 of the
;; License, or (at your option) any later version.
;;
;; Gaiag is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU Affero General Public License for more details.
;;
;; You should have received a copy of the GNU Affero General Public License
;; along with Gaiag.  If not, see <http://www.gnu.org/licenses/>.

;;(format (current-error-port) "%load-path ~a\n" %load-path )
;;(format (current-error-port) "%load-compiled-path ~a\n" %load-compiled-path )
(define (main . args)
  ((@ (gaiag gaiag) main) (command-line)))
