
(define-class <#.interface .in> ()
#(map (declare-io model #{#'()
  (#name  :accessor .#name  :init-value ##f :init-keyword :#name)#})
  (filter gom:in? ((compose .elements .events) model))))
(define-class <#.interface .out> ()
#(map (declare-io model #{#'()
  (#name  :accessor .#name  :init-value ##f :init-keyword :#name)#})
  (filter gom:out? ((compose .elements .events) model))))
(define-class <#.interface > (<interface>))
