// Dezyne --- Dezyne command line tools
//
// Copyright © 2018 Rutger van Beusekom <rutger.van.beusekom@verum.com>
//
// This file is part of Dezyne.
//
// Dezyne is free software: you can redistribute it and/or modify it
// under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// Dezyne is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public
// License along with Dezyne.  If not, see <http://www.gnu.org/licenses/>.
//
// Commentary:
//
// Code:

// /////////////////////////////////////////////////////////////////////////////
//
// File generated by   : Verum ASD:Suite Release <by hand>
//
// /////////////////////////////////////////////////////////////////////////////

#ifndef __ALARMALARMALARMALARM_INTERFACE_H__
#define __ALARMALARMALARMALARM_INTERFACE_H__

#define alarm unix_alarm

#include <boost/shared_ptr.hpp>

#ifdef ASD_HAVE_CONFIG_H
  #include "asdConfig.h"
#else
  #include "asdDefConfig.h"
#endif

#include "asdPassByValue.h"
#include "asdInterfaces.h"
#include "asdSingleThreaded.h"

#undef alarm

//namespace alarm
//{
  class console_api
  {
  public:
    enum PseudoStimulus {

      /// <summary>
      /// The VoidReply event indicates that the processing of the API call has been completed
      /// and the call can return when appropriate.
      /// </summary>
      VoidReply
    };
    virtual ~console_api() {}
    virtual void arm() = 0;
    virtual void disarm() = 0;
  protected:
    console_api() {}
  private:
    console_api& operator = (const console_api& other);
    console_api(const console_api& other);
  };

  class console_cb
  {
  public:
    enum PseudoStimulus {

      /// <summary>
      /// The VoidReply event indicates that the processing of the API call has been completed
      /// and the call can return when appropriate.
      /// </summary>
      VoidReply
    };
    virtual ~console_cb() {}
    virtual void detected() = 0;
    virtual void deactivated() = 0;
  protected:
    console_cb() {}
  private:
    console_cb& operator = (const console_cb& other);
    console_cb(const console_cb& other);
  };

  class alarmInterface
  {
  public:
    virtual ~alarmInterface() {}
    virtual void GetAPI(boost::shared_ptr<console_api>* api) = 0;
    virtual void RegisterCB(boost::shared_ptr<console_cb> cb) = 0;
    virtual void RegisterCB(boost::shared_ptr<asd::channels::ISingleThreaded> cb) = 0;
  protected:
    alarmInterface() {}
  private:
    alarmInterface& operator = (const alarmInterface& other);
    alarmInterface(const alarmInterface& other);
  };
//}

#endif
