// Dezyne --- Dezyne command line tools
//
// Copyright © 2018 Rutger van Beusekom <rutger.van.beusekom@verum.com>
//
// This file is part of Dezyne.
//
// Dezyne is free software: you can redistribute it and/or modify it
// under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// Dezyne is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public
// License along with Dezyne.  If not, see <http://www.gnu.org/licenses/>.
//
// Commentary:
//
// Code:

// /////////////////////////////////////////////////////////////////////////////
//
// File generated by   : Verum ASD:Suite Release <by hand>
//
// /////////////////////////////////////////////////////////////////////////////

#ifndef __SENSORSENSORSENSORSENSOR_INTERFACE_H__
#define __SENSORSENSORSENSORSENSOR_INTERFACE_H__

#include <boost/shared_ptr.hpp>

#ifdef ASD_HAVE_CONFIG_H
  #include "asdConfig.h"
#else
  #include "asdDefConfig.h"
#endif

#include "asdPassByValue.h"
#include "asdInterfaces.h"
#include "asdSingleThreaded.h"


//namespace sensor
//{
  class sensor_api
  {
  public:
    enum PseudoStimulus {

      /// <summary>
      /// The VoidReply event indicates that the processing of the API call has been completed
      /// and the call can return when appropriate.
      /// </summary>
      VoidReply
    };
    virtual ~sensor_api() {}
    virtual void reset() = 0;
    virtual void enable() = 0;
    virtual void disable() = 0;
  protected:
    sensor_api() {}
  private:
    sensor_api& operator = (const sensor_api& other);
    sensor_api(const sensor_api& other);
  };

  class sensor_cb
  {
  public:
    enum PseudoStimulus {

      /// <summary>
      /// The VoidReply event indicates that the processing of the API call has been completed
      /// and the call can return when appropriate.
      /// </summary>
      VoidReply
    };
    virtual ~sensor_cb() {}
  protected:
    sensor_cb() {}
  private:
    sensor_cb& operator = (const sensor_cb& other);
    sensor_cb(const sensor_cb& other);
  };

  class sensorInterface
  {
  public:
    virtual ~sensorInterface() {}
    virtual void GetAPI(boost::shared_ptr<sensor_api>* api) = 0;
    virtual void RegisterCB(boost::shared_ptr<sensor_cb> cb) = 0;
    virtual void RegisterCB(boost::shared_ptr<asd::channels::ISingleThreaded> cb) = 0;
  protected:
    sensorInterface() {}
  private:
    sensorInterface& operator = (const sensorInterface& other);
    sensorInterface(const sensorInterface& other);
  };
//}

#endif
