// Dezyne --- Dezyne command line tools
//
// Copyright © 2018 Rutger van Beusekom <rutger.van.beusekom@verum.com>
// Copyright © 2018 Paul Hoogendijk <paul.hoogendijk@verum.com>
//
// This file is part of Dezyne.
//
// Dezyne is free software: you can redistribute it and/or modify it
// under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// Dezyne is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public
// License along with Dezyne.  If not, see <http://www.gnu.org/licenses/>.
//
// Commentary:
//
// Code:

// /////////////////////////////////////////////////////////////////////////////
//
// File generated by   : Verum ASD:Suite Release <by hand>
//
// /////////////////////////////////////////////////////////////////////////////

#ifndef __SENSOR_COMPONENT_H__
#define __SENSOR_COMPONENT_H__

#include "sensorInterface.h"

#include <boost/enable_shared_from_this.hpp>

class sensorComponent: public sensorInterface
                     , public sensor_api
                     , public boost::enable_shared_from_this<sensorComponent>
{
public:
  static boost::shared_ptr<sensor_cb> cb;
  static boost::shared_ptr<asd::channels::ISingleThreaded> st;
  void RegisterCB(boost::shared_ptr<sensor_cb> cb) { this->cb = cb;}
  void RegisterCB(boost::shared_ptr<asd::channels::ISingleThreaded> st) { this->st = st;}
  void GetAPI(boost::shared_ptr<sensor_api>* api) { *api = boost::static_pointer_cast<sensor_api> (shared_from_this()); }
  void reset(){}
  void enable(){}
  void disable(){}

  static boost::shared_ptr<sensorInterface> GetInstance();
  static void ReleaseInstance();

  static void triggered();
  static void disabled();
};

#endif
