;;; Dezyne --- Dezyne command line tools
;;;
;;; Copyright © 2017 Jan Nieuwenhuizen <janneke@gnu.org>
;;; Copyright © 2017 Rutger van Beusekom <rutger.van.beusekom@verum.com>
;;;
;;; This file is part of Dezyne.
;;;
;;; Dezyne is free software: you can redistribute it and/or modify it
;;; under the terms of the GNU Affero General Public License as
;;; published by the Free Software Foundation, either version 3 of the
;;; License, or (at your option) any later version.
;;;
;;; Dezyne is distributed in the hope that it will be useful, but
;;; WITHOUT ANY WARRANTY; without even the implied warranty of
;;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
;;; Affero General Public License for more details.
;;;
;;; You should have received a copy of the GNU Affero General Public
;;; License along with Dezyne.  If not, see <http://www.gnu.org/licenses/>.
;;; 
;;; Commentary:
;;; 
;;; Code:

;; This file is part of Gaiag, Guile in Asd In Asd in Guile.

(define-module (gaiag deprecated code)
  #:use-module (ice-9 curried-definitions)
  #:use-module (ice-9 getopt-long)
  #:use-module (ice-9 match)
  #:use-module (ice-9 and-let-star)
  #:use-module (ice-9 optargs)
  #:use-module (ice-9 peg)
  #:use-module (ice-9 peg codegen)
  #:use-module (ice-9 pretty-print)
  #:use-module (srfi srfi-1)
  #:use-module (srfi srfi-26)

  #:use-module (gaiag lexicals)
  #:use-module ((oop goops) #:renamer (lambda (x) (if (member x '(<port> <foreign>)) (symbol-append 'goops: x) x)))
  #:use-module (gaiag ast2om)
  #:use-module (gaiag goops)
  #:use-module (gaiag om)
  #:use-module (gaiag util)

  #:use-module (gaiag deprecated animate)
  #:use-module (gaiag annotate)
  #:use-module (gaiag code)
  #:use-module (gaiag command-line)
  #:use-module (gaiag compare)
  #:use-module (gaiag indent)
  #:use-module (gaiag misc)
  #:use-module (gaiag norm-event)
  #:use-module (gaiag reader)
  #:use-module (gaiag resolve)
  #:use-module (gaiag xpand)

  #:export (ast:code
           code:identifier?
           code:->code
           code:signature-equal?
           code:signature-types-equal?
           code:animate-file
           enum-type
           ->code
           binding-name
           declare-enum
           declare-io
           declare-interface-event
           declare-integer
           declare-replies
           define-function
           define-helper
           define-reply
           define-on
           define-on+
           connect-ports
           enum-to-string
           expression->string
           string-to-enum
           include-component
           include-interface
           init-bind
           init-instance
           init-member
           init-async-port
           init-port
           injected-binding
           injected-binding?
           injected-bindings
           injected-instance-interface
           injected-instance-name
           injected-instance-port
           injected-instance-type
           locals
           local-lexicals
           injected-instances
           non-injected-instances
           join
           expression->string
           return-type
           sep
           statements.event
           statements.port
           string-if

           animate-pairs
           ))

(define (ast:code ast)
  (let ((om ((om:register code:om #t) ast)))
    (ast:set-scope
     om
     (parameterize ((template-dir (append (prefix-dir) `(templates ,(language)))))
                   (map dump (filter (negate om:imported?) ((om:filter:p <model>) om)))
                   (dump-header))))
  "")

(define (om:data-member-names model)
  (map .name (filter (lambda (x) (as ((om:type model) (.type x)) <extern>)) (om:variables model))))

(define (transform-formals-shadow-member model formals)
  (define (rename formal)
    (make <formal> #:name (symbol-append 'dzn_ (.name formal)) #:type (.type formal) #:direction (.direction formal)))
  (let* ((members (om:data-member-names model))
         (transform (lambda (f) (if (member (.name f) members) (rename f)
                                    f))))
    (map transform formals)))

(define (wrap-compound statement) (make <compound> #:elements (list statement)))
(define join (make-parameter (->join ", ")))
(define sep (make-parameter ","))

(define* (code:->code model src #:optional (blocking? #f) (locals '()) (indent 1) (compound? #t))
  (parameterize ((template-dir (append (prefix-dir) `(templates ,(language)))))
    (->code model src blocking? locals indent compound?)))

(define statements.port (make-parameter #f))
(define statements.event (make-parameter #f))

(define* (->code model src #:optional (blocking? #f) (locals '()) (indent 1) (compound? #t))
  (let ((statement (->code- model src blocking? locals indent compound?)))
    (if (eq? statement '$empty-statement$)
        ""
        (->string statement))))

(define (unspecified? x) (eq? x *unspecified*))

(define* (->code- model src #:optional (blocking? #f) (locals '()) (indent 1) (compound? #t))
  (define (enum? identifier)
    (debug "ENUM?[~a] ==> ~a\n" identifier (om:enum model identifier))
    (om:enum model identifier))
  (define (extern? identifier) (om:extern model identifier))
  (define (int? identifier)
    (debug "INT?[~a] ==> ~a\n" identifier (om:integer model identifier))
    (om:integer model identifier))
  (define (local? identifier) (assoc-ref locals identifier))
  (define (member? identifier) (and (not (local? identifier))
                                    (om:variable model identifier)))
  (define (var? identifier) (or (member? identifier) (local? identifier)))
  (define (formal? identifier) (and=> (var? identifier) (is? <formal>)))
  (define (identifier-snippet identifier)
    (cond ((member? identifier)
            (snippet 'member `((identifier ,identifier))))
          ((formal? identifier)
           (snippet 'formal-identifier
                    `((identifier ,identifier)
                      (out? ,(om:out-or-inout? (formal? identifier)))
                      (argument #f))))
          ((local? identifier)
           (snippet 'local `((identifier ,identifier) (argument #f))))
          (else identifier)))

  (define (reply-port port)
    (or port
        (and=> (or (and (statements.port) (om:provides? (statements.port)) (statements.port))
                   (car (filter om:provides? (om:ports model))))
               .name)))

  (let ((port (statements.port))
        (event (statements.event))
        (space (make-string (* indent (if (eq? (language) 'python) 4 2)) #\space)))

    (match src
      (() "")
      ('$empty-statement$ (snippet 'empty `((space ,space))))
      (($ <guard> expression ($ <compound> (statements ...)))
       (let* ((statement (.statement src))
              (statement (->code- model statement blocking? locals (1+ indent)))
              (statement (if (eq? statement '$empty-statement$)
                             (->code model statement blocking? locals (1+ indent))
                             statement)))
         (string-append
          (snippet 'guard
                   `((space ,space)
                     (clause ,(expr->clause model src expression))
                     (statement ,statement)))
          (if (not (om:last-guard? model src)) ""
              (snippet 'else-illegal `((space ,space)
                                       (illegal ,(snippet 'illegal `((space ,space))))))))))
      (($ <guard> expression statement)
       (let* ((statement (wrap-compound statement))
              (statement (->code- model statement blocking? locals (1+ indent)))
              (statement (if (eq? statement '$empty-statement$)
                             (->code model statement blocking? locals (1+ indent))
                             statement)))
         (string-append
          (snippet 'guard
                   `((space ,space)
                     (clause ,(expr->clause model src expression))
                     (statement ,statement)))
          (if (not (om:last-guard? model src)) ""
              (snippet 'else-illegal `((space ,space)
                                       (illegal ,(snippet 'illegal `((space ,space))))))))))
      (($ <if> expression then #f)
       (snippet 'if-then
                `((space ,space)
                  (expression ,(expression->string model expression locals))
                  (then ,(->code model then blocking? locals (1+ indent))))))
      (($ <if> expression (and ($ <if> e t) (get! then)) else)
       (->code- model (make <if> #:expression expression #:then (wrap-compound (then)) #:else else) blocking? locals indent))
      (($ <if> expression then else)
       (snippet 'if-then-else
                `((space ,space)
                  (expression ,(expression->string model expression locals))
                  (then ,(->code model then blocking? locals (1+ indent)))
                  (else ,(->code model else blocking? locals (1+ indent))))))
      (($ <assign> variable (and ($ <action>) (get! action)))
        (snippet 'assign
                 `((space ,space)
                   (identifier ,(identifier-snippet (.name variable)))
                   (expression ,(expression->string model (action) locals)))))
      (($ <assign> variable (and ($ <call>) (get! call)))
         (snippet 'assign
                  `((space ,space)
                    (identifier ,(identifier-snippet (.name variable)))
                    (expression ,(expression->string model (call) locals)))))
      (($ <assign> variable expression)
       (snippet 'assign
                `((space ,space)
                  (identifier ,(identifier-snippet (.name variable)))
                  (expression ,(expression->string model expression locals)))))
      (($ <blocking> statement)
       (->code- model statement #t locals indent))
      (($ <on> triggers (and ($ <if> e t #f) (get! statement)))
       (->code- model (make <on> #:triggers triggers #:statement (wrap-compound (statement))) blocking? locals indent))
      (($ <on> triggers statement)
       (or (and-let* ((signature (transform-signature (.signature event) src))
                      (trigger (car (.elements triggers))))
             (let* ((blocking? (pair? ((om:collect <blocking>) statement)))
                    (statement (->code model statement blocking? locals indent compound?))
                    (statement (if (or (not blocking?) (and port (eq? (.direction port) 'requires))) statement
                                   `(,(snippet 'block
                                               `((space ,space)
                                                 (statement ,statement)
                                                 (port ,(.port.name trigger))))))))
               statement))
           '$empty-statement$))
      (($ <call> function-name ($ <arguments> ()))
       (snippet 'call `((space ,space) (function ,function-name))))
      (($ <call> function-name ($ <arguments> (arguments ...)))
       (let* ((formals ((compose .elements .formals .signature) (.function src)))
              (formals (if (calling-context)
                           (cons (make <formal> #:name 'cc__ #:type (calling-context)) formals)
                           formals))
              (arguments (if (calling-context)
                             (cons 'cc__ arguments)
                             arguments))
              (arguments ((join)
                          (map (lambda (e p)
                                 (let ((out? (member (.direction p) '(inout out))))
                                   (snippet 'argument `((expression ,(expression->string model e locals (if out? 'out 'in)))
                                                        (out? ,(member (.direction p) '(inout out)))))))
                               arguments formals))))
         (snippet 'call-arguments
                  `((space ,space) (function ,function-name) (arguments ,arguments)))))
      (($ <arguments> (arguments ...))
       ((join)
        (map (lambda (o) (expression->string model o locals)) arguments)))
      (($ <compound> ())
       (snippet 'compound-empty `((space ,space))))
      (($ <compound> (statements ...))
       (snippet
        (symbol-append
         (if compound? 'compound 'statements)
         (if (is-a? (car statements) <guard>) '-guarded (string->symbol "")))
        `((space ,space)
          (statements
           ,(let loop ((statements statements) (locals locals))
              (if (null? statements)
                  '()
                  (let* ((statement (car statements))
                         (variable? (as statement <variable>))
                         (locals (if variable? (acons (.name statement) statement locals)
                                     locals)))
                    (let ((statement (->code model (car statements) blocking? locals indent))
                          (continuation (loop (cdr statements) locals)))
                      (if variable?
                          (list (snippet 'context `((space ,space)
                                                    (statement ,statement)
                                                    (continuation ,continuation))))
                          (cons statement continuation))))))))))
      (($ <illegal>) (snippet 'illegal `((space ,space))))
      ((and ($ <action>) (= .port.name port-name) (= .event event) (= .arguments ($ <arguments> (arguments ...))))
       (let* ((port (.port src))
              (name (.type port))
              (event-name (.name event))
              (interface (.type port))
              (direction (.direction event))
              (comma (if (pair? arguments) (sep) ""))
              (comma-space (if (pair? arguments) `(,(sep) " ") ""))
              (number (number->string (length arguments)))
              (formals ((compose .elements .formals .signature) event))
              (formals (if (calling-context) (cons (make <formal> #:name 'cc__ #:type (calling-context)) formals)
                           formals))
              (arguments (if (calling-context)
                             (cons 'cc__ arguments)
                             arguments))
              (arguments ((join)
                          (map (lambda (e p)
                                 (let ((out? (member (.direction p) '(inout out))))
                                   (snippet 'argument `((expression ,(expression->string model e locals (if out? 'out 'in)))
                                                        (out? ,(member (.direction p) '(inout out)))))))
                               arguments formals))))
         (snippet (symbol-append 'action- direction)
                  `((space ,space)
                    (port ,port-name)
                    (direction ,direction)
                    (event ,event-name)
                    (arguments ,arguments)
                    (number ,number)
                    (comma ,comma)
                    (comma-space ,comma-space)))))
      (($ <reply> (and ($ <literal> type field) (get! expression)) port)
       ;;(stderr "reply0: ~a\n" (expression))
       (let ((port (reply-port port))
             (port-name (or (and=> (as port <port>) .name) port))
             (scope ((compose om:scope .name) type))
             (name ((compose om:name .name) type)))
         (->string
          (list (snippet 'reply
                         `((space ,space)
                           (scope ,scope)
                           (name ,name)
                           (expression ,(expression->string
                                         model (expression) locals))))
                (if (om:blocking? model)  (snippet 'release
                                                   `((space ,space)
                                                     (scope ,scope)
                                                     (name ,name)
                                                     (port ,port-name))))))))
      (($ <reply> (and ($ <var>) (= .variable.name name) (get! expression)) port)
       (let* ((var (var? name))
              (type (.type var))
              (port (reply-port port))
              (port-name (or (and=> (as port <port>) .name) port)))
         (->string (list
                    (snippet 'reply
                             `((space ,space)
                               (scope ,(om:scope type))
                               (name ,(om:name type))
                               (expression ,(expression->string
                                             model (expression) locals))))
                    (if (om:blocking? model) (snippet 'release
                                                      `((space ,space)
                                                        (scope ,(om:scope type))
                                                        (name ,(om:name type))
                                                        (port ,port-name))))))))
      (($ <reply> (and ($ <value> (? unspecified?)) (get! expression)) port)
       ;;(stderr "reply2: ~a\n" (expression))
       (let ((port (reply-port port))
             (port-name (or (and=> (as port <port>) .name) port)))
         (if (om:blocking? model) (snippet 'release
                                           `((space ,space)
                                             (port ,port-name))))))
      (($ <reply>) (=> failure)
       ;;(stderr "reply3: ~a\n" (.expression src))
       (let* ((expression (.expression src))
              (expression (match expression
                            ((and ($ <value>) (= .value (? unspecified?))) (failure))
                            ((? unspecified?) (failure))
                            (_ expression)))
              (scope '())
              (type (om:type-name (ast:expression-type expression)))
              (port (reply-port (.port src)))
              (port-name (or (and=> (as port <port>) .name) port)))
         (->string (list (snippet 'reply
                                  `((space ,space)
                                    (scope ,scope)
                                    (name ,type)
                                    (expression ,(expression->string model expression locals))))
                         (if (om:blocking? model) (snippet 'release
                                                           `((space ,space)
                                                             (scope ,scope)
                                                             (name ,type)
                                                             (port ,port-name))))))))
      (($ <reply> expression port)
       ;;(stderr "reply4: ~a\n" expression)
       (let ((port (reply-port port))
             (port-name (or (and=> (as port <port>) .name) port)))
         (if (om:blocking? model) (snippet 'release
                                           `((space ,space)
                                             (port ,port-name))))))
      (($ <return> #f) (snippet 'return-void `((space ,space))))
      (($ <return> expression)
       (snippet 'return
                `((space ,space)
                  (expression ,(expression->string model expression locals)))))
      (($ <signature> type) (->code model type blocking? locals indent))
      (($ <scope.name>) (om:scope+name src))

      (($ <bool>) (snippet 'bool '()))
      (($ <extern>)
       (let ((value (.value src)))
         (snippet 'type-extern `((space ,space) (value ,value)))))
      (($ <enum>)
       (snippet 'type-enum `((space ,space) (scope-name ,(append (om:scope src) (list (om:name src)))) (scope ,(om:scope src)) (name ,(om:name src)))))
      (($ <int>)
       (snippet 'type-int `((space ,space) (scope-name ,(append (om:scope src) (list (om:name src)))) (scope ,(om:scope src)) (name ,(om:name src)))))
      (($ <void>) 'void)

      (($ <variable> name type (and ($ <action>) (get! action)))
       (snippet 'variable
                `((space ,space)
                  (name ,name)
                  (type ,(->code model type))
                  (expression ,(expression->string model (action) locals)))))
      (($ <variable> name type (and ($ <call>) (get! call)))
       (snippet 'variable
                `((space ,space)
                  (name ,name)
                  (type ,(->code model type))
                  (expression ,(expression->string model (call) locals)))))
      (($ <variable> name type expression)
       (snippet 'variable
                `((space ,space)
                  (name ,name)
                  (type ,(->code model type))
                  (expression ,(expression->string model expression locals)))))
      (($ <formals> (formals ...))
       ((join) (map (lambda (x) (->code model x)) formals)))
      ((and ($ <formal>) (= .name name) (= .type type) (= .direction direction))
       (snippet 'formal `((name ,name) (type ,(->code model type)) (out? ,(member direction '(inout out))))))
      ((and ($ <formal-binding>) (= .name name) (= .type type) (= .direction direction) (= .variable.name global))
       (let* ((var (var? global))
              (type (->code model (.type var))))
         (snippet 'out-binding `((formal ,name) (type ,type) (out? ,(member direction '(inout out))) (global ,global)))))
      (($ <data> value) value)
      ((and ($ <var>) (= .variable variable)) (.name variable))
      (($ <out-bindings>)
       (let ((statements (map (lambda (x) (->code model x)) (.elements src)))
             (assignments (map (lambda (formal-binding) (cons (.name formal-binding) (.variable.name formal-binding))) (.elements src))))
         (snippet 'out-bindings
                  `((port ,(.name port))
                    (statements ,statements)
                    (assignments ,assignments)))))
      ((? char?) (make-string 1 src))
      ((? string?) src)
      ('true (snippet 'true '()))
      ('false (snippet 'false '()))
      (#t (snippet 'true '()))
      (#f (snippet 'false '()))
      ((? symbol?) src)
      ((h t ...) (map (lambda (x) (->code model x blocking? locals indent)) src))
      ((? unspecified?) #f)
      (_ (throw 'match-error (format #f "~a:code:->code: no match: ~a\n" (current-source-location) src))))))

(define ((find-trigger port event) o)
  (match o
    (($ <blocking>) ((find-trigger port event) (.statement o)))
    (($ <on>)
     (find (lambda (t) (and (eq? (.port.name t) (.name port))
                            (eq? (.event.name t) (.name event))))
           ((compose .elements .triggers) o)))
    (($ <guard>) ((find-trigger port event) (.statement o)))
    (($ <compound> (statements ...))
     (null-is-#f (filter identity (map (find-trigger port event) statements))))
    (_ #f)))

(define ((is-trigger? port event) o)
  (match o
    (($ <on>)
     (let ((trigger ((compose car .elements .triggers) o)))
       (and (eq? (.port.name trigger) (.name port))
            (eq? (.event.name trigger) (.name event)) o)))
    (_ #f)))

(define (expr->clause model guard expression)
  (if (is-a? expression <otherwise>)
      (snippet 'clause-else '())
      (let* ((c-expression (expression->string model expression))
             (if-clause (snippet 'clause-if `((expression ,c-expression))))
             (else-if-clause (snippet 'clause-else-if `((expression ,c-expression)))))
        (->string (list (if (om:first-guard? model guard) if-clause else-if-clause))))))

(define (om:top-statements o)
  ((compose .elements .statement .behaviour) o))

(define (om:first-guard? model guard)
  (not
   (and-let* ((parent (om:parent model guard))
              ((not (is-a? parent <on>)))
              ((is-a? parent <compound>))
              (guards (null-is-#f (om:filter (is? <guard>) parent))))
     (not (eq? guard (car guards))))))

(define (om:last-guard? model guard)
  (not
   (and-let* ((parent (om:parent model guard))
              ((not (is-a? parent <on>)))
              ((is-a? parent <compound>))
              (guards (null-is-#f (om:filter (is? <guard>) parent))))
             (not (eq? guard (last guards))))))

(define* (expression->string model o #:optional (locals '()) (argument #f))

  (define (enum? identifier) (om:enum model identifier))
  (define (local? identifier) (assoc-ref locals identifier))
  (define (member? identifier) (and (not (local? identifier))
                                    (om:variable model identifier)))
  (define (local-variable? variable) (local? (.name variable)))
  (define (member-variable? variable) (member? (.name variable)))
  (define (var? v) (or (as v <variable>) (local? v) (member? v)))
  (define (formal? f) (or (as f <formal>) (and=> (var? f) (is? <formal>))))
  (define (unspecified? x) (eq? x *unspecified*))

  (define (enum-type o field)
    (or (and-let* ((var (var? o))
                   (type (.type var))
                   (literal (make <literal> #:type type #:field field)))
          (expression->string model literal locals))
        ""))

  (match o
    ((? unspecified?) *unspecified*)
    (($ <value> (? unspecified?)) *unspecified*)
    (($ <value>) (expression->string model (.value o) locals argument))
    ((and ($ <action>) (= .port.name port-name) (= .event event) (= .arguments ($ <arguments> (arguments ...))))
     (let* ((port (.port o))
            (name (.type port))
            (event-name (.name event))
            (interface (.type port))
            (direction (.direction event))
            (comma (if (pair? arguments) (sep) ""))
            (comma-space (if (pair? arguments) `(,(sep) " ") ""))
            (number (number->string (length arguments)))
            (formals ((compose .elements .formals .signature) event))
            (formals (if (calling-context) (cons (make <formal> #:name 'cc__ #:type (calling-context)) formals)
                         formals))
            (arguments (if (calling-context)
                           (cons 'cc__ arguments)
                           arguments))
            (arguments ((join)
                        (map (lambda (e p)
                               (let ((out? (member (.direction p) '(inout out))))
                                 (snippet 'argument `((expression ,(expression->string model e locals (if out? 'out 'in)))
                                                      (out? ,(member (.direction p) '(inout out)))))))
                             arguments formals))))
       (snippet 'action-expression
                `((port ,port-name)
                  (direction ,direction)
                  (event ,event-name)
                  (arguments ,arguments)
                  (number ,number)
                  (comma ,comma)
                  (comma-space ,comma-space)))))
    ((and ($ <var>) (= .variable.name (? member?)))
     (snippet 'member `((identifier ,((compose .name .variable) o)) (argument ,argument))))
    ((and ($ <var>) (= .variable.name (? formal?)))
     (snippet 'formal-identifier
              `((identifier ,((compose .name .variable) o))
                (out? ,(om:out-or-inout? (.variable o)))
                (argument ,argument))))
    ((and ($ <var>) (= .variable.name (? local?)))
     (snippet 'local `((identifier ,((compose .name .variable ) o)) (argument ,argument))))
    (($ <var>)
     ((compose .name .variable) o))
    (($ <field> (and (? member-variable?) (get! variable)) field)
     (snippet 'field-expression `((identifier ,(snippet 'member `((identifier ,(.name (variable))))))
                                  (expression ,(enum-type (variable) field)))))
    (($ <field> (and (? local-variable?) (get! variable)) field)
     (snippet 'field-expression `((identifier ,(snippet 'local `((identifier ,(.name (variable))) (argument ,argument))))
                                  (expression ,(enum-type (.name (variable)) field)))))
    (($ <field> variable field)
     (snippet 'field-expression `((identifier ,(.name variable))
                                  (expression ,(enum-type variable field)))))
    (($ <call> function-name ($ <arguments> ()))
     (snippet 'call-expression `((function ,function-name))))
    (($ <call> function-name ($ <arguments> (arguments ...)))
     (let* ((function (.function o))
            (formals ((compose .elements .formals .signature) function))
            (arguments (if (calling-context)
                           (cons 'cc__ arguments)
                           arguments))
            (arguments ((join)
                        (map (lambda (e p)
                               (let ((out? (member (.direction p) '(inout out))))
                                 (snippet 'argument `((expression ,(expression->string model e locals (if out? 'out 'in)))
                                                      (out? ,(member (.direction p) '(inout out)))))))
                             arguments formals))))
       (snippet 'call-arguments-expression
                `((function ,function-name) (arguments ,arguments)))))
    (($ <literal> type field)
     (snippet 'literal `((scope-name ,(om:scope+name (.name type))) (scope ,(.scope (.name type))) (name ,(.name (.name type))) (field ,field))))
    ((? number?) (number->string o))
    (($ <value> expression) (expression->string model expression locals))
    (($ <not> expression)
     (let ((expression (expression->string model expression locals)))
       (snippet 'not `((expression ,expression)))))
    (($ <group> expression)
     (snippet 'group `((expression ,(expression->string model expression locals))) ")"))
    ((or ($ <and>) ($ <or>) ($ <equal>) ($ <not-equal>))
     (let ((lhs (expression->string model (.left o) locals))
           (rhs (expression->string model (.right o) locals))
           (op (assoc-ref '((<and> . and)
                            (<equal> . ==)
                            (<not-equal> . !=)
                            (<or> . or))
                          (class-name (class-of o)))))
       (snippet op `((op ,op) (lhs ,lhs) (rhs ,rhs)))))
    ((? (is? <binary>))
     (let* ((lhs (expression->string model (.left o) locals))
            (rhs (expression->string model (.right o) locals))
            (op (.operator o)))
       (snippet 'op `((op ,op) (lhs ,lhs) (rhs ,rhs)))))
    (_ (->code model o #f locals 0))))

(define ((connect-ports model snippet) bind)
  (let* ((left (.left bind))
         (left-port (.port left))
         (right (.right bind))
         (right-port (.port right))
         (provided-required (if (om:provides? left-port)
                                (cons left right)
                                (cons right left)))
         (interface (.type left-port))
         (provided (binding-name model (car provided-required)))
         (required (binding-name model (cdr provided-required))))
    (animate snippet `((interface ,(.name interface)) (provided ,provided) (required ,required)))))

(define ((declare-enum model) enum)
  (let* ((fields ((compose .elements .fields) enum))
         (length (length fields))
         (asd? #f))
   (snippet 'declare-enum
            `((scope+name ,(om:scope+name enum)) (scope ,(om:scope enum)) (name ,(om:name enum)) (fields ,fields) (length ,length) (asd? ,asd?)))))

(define ((enum-to-string o) enum)
  (let* ((fields ((compose .elements .fields) enum))
         (length (length fields)))
    (snippet 'enum-to-string
             `((scope+name ,(om:scope+name enum)) (scope ,(om:scope enum)) (name ,(om:name enum)) (fields ,fields) (length ,length)))))

(define ((string-to-enum o) enum)
  (let* ((fields ((compose .elements .fields) enum))
         (length (length fields)))
   (snippet 'string-to-enum
            `((scope ,(om:scope enum)) (name ,(om:name enum)) (fields ,fields) (length ,length)))))

(define (declare-integer integer)
  (snippet 'declare-integer `((name int))))

(define (pair->list o) (list (car o) (cdr o)))
(define (ast-cdr? o) ((compose (is? <ast>) cdr) o))

(define ((declare-io model string) event)
  (parameterize ((any->string (cut ->code model <>)))
    (let* ((signature (.signature event))
           (formals (.formals signature))
           (formals (if (calling-context) (make <formals> #:elements (cons (make <formal> #:name 'cc__ #:type (calling-context)) (.elements formals)))
                        formals))
           (signature
            (if (calling-context)
                (make <signature> #:type (.type signature) #:formals formals)
                signature))
           (type (.type signature)))
      (animate string (cons `(name ,(.name event))
                            (map pair->list (filter ast-cdr? (lexicals))))))))

(define ((declare-interface-event model) event)
  ((declare-io model (gulp-snippet 'declare-interface-event)) event))

(define ((define-function model string) function)
  (let* ((signature (.signature function))
         (return-type (code:->code model signature))
         (type (.type signature))
         (scope-return-type (if (not (pair? (om:scope type))) (om:name type)
                                (snippet 'type-scope-enum `((scope-name ,(om:scope+name type)) (scope ,(om:scope type)) (name ,(om:name type))))))
         (name (.name function))
         (formals (.formals signature))
         (formals (if (calling-context) (make <formals> #:elements (cons (make <formal> #:name 'cc__ #:type (calling-context)) (.elements formals)))
                        formals))
         (comma (if (null? (.elements formals)) "" (sep)))
         (comma-space (if (null? (.elements formals)) "" `(,(sep) " ")))
         (statement (.statement function))
         (locals (map (lambda (x) (cons (.name x) x)) (.elements formals)))
         (formals (code:->code model formals))
         (statements (code:->code model statement #f locals 2 #f)))
    (animate string `((name ,name)
                       (return-type ,return-type)
                       (scope-return-type ,scope-return-type)
                       (comma ,comma)
                       (comma-space ,comma-space)
                       (formals ,formals)
                       (statements ,statements)))))

(define ((om:statement-of-type type) statement)
  (and statement
   (eq? (ast-name statement) type)))

(define ((om:statements-of-type type) statement)
  (match statement
    ((? (om:statement-of-type type)) (list statement))
    (($ <compound> (s ...)) (filter identity (apply append (map (om:statements-of-type type) s))))
    (($ <on> triggers statement) (filter identity ((om:statements-of-type type) statement)))
    ((? (is? <statement>)) '())
    (#f '())))

(define (code:formals->name model signature)
  (let ((formals ((compose .elements .formals) signature)))
    ((->join "_")
     (cons*
      ((compose om:type-name (om:type model) .type) signature)
      (if (null? formals) '(void)
          (map
           (lambda (formal)
             (let ((name ((compose om:type-name (om:type model) .type) formal)))
               (if (om:out-or-inout? formal) (symbol-append name 'p)
                   name)))
           formals))))))

(define (x-formal formal)
  (make <formal> #:type (.type formal) #:name (.name formal) #:direction (if (om:out-or-inout? formal) 'out 'in)))

(define ((code:signature-equal? model) a b)
  (and (equal? (->code- model (.type a)) (->code- model (.type b)))
       (om:equal? (map x-formal ((compose .elements .formals) a))
               (map x-formal ((compose .elements .formals) b)))))

(define* ((type-equal? model) a b)
  (or (om:equal? a b)
      (and (om:enum model a) (om:enum model b))))

(define ((code:signature-types-equal? model) a b)
  (and ((type-equal? model) (.type a) (.type b))
       (om:equal? (map om:out-or-inout? ((compose .elements .formals) a))
               (map om:out-or-inout? ((compose .elements .formals) b)))
       (every (type-equal? model)
              (map .type ((compose .elements .formals) a))
              (map .type ((compose .elements .formals) b)))))

(define ((define-helper model port string) signature)
  (let* ((formals ((compose .elements .formals) signature))
         (formal-list (map (lambda (x) (code:->code model x)) formals))
         (formal-types (map (lambda (formal)
                              (snippet 'formal-type `((type ,(->code model (.type formal))) (out? ,(member (.direction formal) '(inout out))))))
                            formals))
         (formal-numbered-list (map (lambda (type number) (list type " _" number)) formal-types (iota (length formal-types))))
         (return-type (->code- model (.type signature))))
    (animate string `((argument-list ,(map .name formals))
                      (comma ,(if (pair? formals) (sep) ""))
                      (formal-list ,formal-list)
                      (formal-numbered-list ,formal-numbered-list)
                      (formal-types ,formal-types)
                      (port ,(and=> port .name))
                      (signature-name ,(code:formals->name model signature))
                      (return-type ,return-type))
             signature)))

(define (transform-signature signature on)
  (define (rename-formal formal name)
    (make <formal> #:name name #:type (.type formal) #:direction (.direction formal)))
  (if (not on)
      signature
      (let* ((formals (map .name ((compose .elements .formals car .elements .triggers) on)))
             (formals (map rename-formal ((compose .elements .formals) signature) formals)))
        (make <signature> #:type (.type signature) #:formals (make <formals> #:elements formals)))))

(define ((define-on+ model port string) event)
  (let* ((behaviour (and=> (as model <component>) .behaviour))
         (ons (if (not behaviour) '()
                  ((compose .elements .statement) behaviour)))
         (ons (filter (is-trigger? port event) ons))
         (on (and (pair? ons) (car ons)))
         (signature (.signature event))
         (signature (transform-signature signature on))
         (signature-name (code:formals->name model signature))
         (formals (.formals signature))
         (formal-objects (.elements formals))
         (formal-objects (if (calling-context)
                              (cons (make <formal> #:name 'cc__ #:type (calling-context)) formal-objects)
                              formal-objects))
         (formals (make <formals> #:elements formal-objects))
         (signature
          (if (calling-context)
              (make <signature> #:type (.type signature) #:formals formals)
              signature))
         (type (.type signature))
         (type-type ((om:type model) type))
         (interface (.type port))
         (interface-name (.name interface))
         (return-type (return-type model event))
         (return-type-name (om:type-name type-type))
         (in-formals (filter om:in? ((compose .elements .formals) signature)))
         (capture-list (comma-join (append (list "&") (map .name in-formals))))
         (formals ((compose .elements .formals) signature))
         (argument-list (map .name formals))
         (number (number->string (length argument-list)))
         (arguments (comma-join argument-list))
         (locals (let loop ((formals formals) (locals '()))
                   (if (null? formals)
                       locals
                       (loop (cdr formals)
                             (acons (.name (car formals)) (car formals) locals)))))
         (comma (if (pair? formals) (sep) ""))
         (comma-space (if (pair? formals) (sep) ""))
         (formal-types (map (lambda (formal)
                                 (snippet 'formal-type `((type ,(->code model (.type formal))) (out? ,(member (.direction formal) '(inout out))))))
                            formals))
         (formal-list (map (lambda (x) (code:->code model x)) formals))
         (formals (code:->code model (make <formals> #:elements formals)))
         (reply-type (ast-name ((om:type model) type)))
         (reply-name (if (is-a? type-type <int>) 'int (om:name type)))
         (reply-scope (om:scope type-type))
         (reply-scope-name (om:scope+name type-type))
         (system (as model <system>))
         (bind (and system (om:port-bind system port)))
         (instance-binding (and bind (om:instance-binding? bind)))
         (instance (and instance-binding (.instance instance-binding)))
         (instance-port (and instance-binding (.port.name instance-binding)))
         (blocking? #f)
         (space "    ")
         (statement
          (cond
           ((and behaviour (is-a? model <component>))
            (parameterize ((statements.port port)
                           (statements.event event))
              (if on
                  (code:->code model on blocking? locals 2 #f)
                  (snippet 'illegal `((space ,space))))))
           (else ""))))
    (animate string `((port ,(.name port))
                       (event ,(.name event))
                       (argument-list ,argument-list)
                       (arguments ,arguments)
                       (direction ,(.direction event))
                       (capture-list ,capture-list)
                       (comma ,comma)
                       (comma-space ,comma-space)
                       (type-type ,type-type)
                       (signature-name ,signature-name)
                       (interface ,interface)
                       (interface-name ,interface-name)
                       (number ,number)
                       (formals ,formals)
                       (formal-list ,formal-list)
                       (formal-objects ,formal-objects)
                       (formal-types ,formal-types)
                       (reply-name ,reply-name)
                       (reply-type ,reply-type)
                       (reply-scope ,reply-scope)
                       (reply-scope-name ,reply-scope-name)
                       (return-type ,return-type)
                       (return-type-name ,return-type-name)
                       (instance ,(and instance (.name instance)))
                       (instance-port ,instance-port)
                       (statement ,statement)
                       (type ,(.name type))))))

(define ((define-on model port string) event)
  (let* ((behaviour (and=> (as model <component>) .behaviour))
         (ons (if (not behaviour) '()
                  ((compose .elements .statement) behaviour)))
         (ons (filter (is-trigger? port event) ons))
         (on (and (pair? ons) (car ons)))
         (signature (.signature event))
         (signature (transform-signature signature on))
         (signature-name (code:formals->name model signature))
         (formals (.formals signature))
         (formal-objects (.elements formals))
         (formal-objects (if (calling-context)
                              (cons (make <formal> #:name 'cc__ #:type (calling-context)) formal-objects)
                              formal-objects))
         (formals (make <formals> #:elements formal-objects))
         (signature
          (if (calling-context)
              (make <signature> #:type (.type signature) #:formals formals)
              signature))
         (type (.type signature))
         (type-type ((om:type model) type))
         (interface (.type port))
         (return-type (return-type model event))
         (return-type-name (om:type-name type-type))
         (in-formals (filter om:in? ((compose .elements .formals) signature)))
         (capture-list (comma-join (append (list "&") (map .name in-formals))))
         (formals ((compose .elements .formals) signature))
         (argument-list (map .name formals))
         (number (number->string (length argument-list)))
         (arguments (comma-join argument-list))
         (locals (let loop ((formals formals) (locals '()))
                   (if (null? formals)
                       locals
                       (loop (cdr formals)
                             (acons (.name (car formals)) (car formals) locals)))))
         (comma (if (pair? formals) (sep) ""))
         (comma-space (if (pair? formals) (sep) ""))
         (formal-types (map (lambda (formal)
                                 (snippet 'formal-type `((type ,(->code model (.type formal))) (out? ,(member (.direction formal) '(inout out))))))
                            formals))
         (formal-list (map (lambda (x) (code:->code model x)) formals))
         (formals (code:->code model (make <formals> #:elements formals)))
         (reply-type (ast-name ((om:type model) type)))
         (reply-name (if (eq? reply-type 'int) 'int (om:name type)))
         (reply-scope (om:scope type-type))
         (reply-scope-name (om:scope+name type-type))
         (system (as model <system>))
         (bind (and system (om:port-bind system port)))
         (instance-binding (and bind (om:instance-binding? bind)))
         (instance (and instance-binding (.instance instance-binding)))
         (instance-port (and instance-binding (.port instance-binding)))
         (blocking? #f)
         (space "    "))
    (animate string `((port ,(.name port))
                       (event ,(.name event))
                       (argument-list ,argument-list)
                       (arguments ,arguments)
                       (direction ,(.direction event))
                       (capture-list ,capture-list)
                       (comma ,comma)
                       (comma-space ,comma-space)
                       (type-type ,type-type)
                       (signature-name ,signature-name)
                       (interface ,interface)
                       (number ,number)
                       (formals ,formals)
                       (formal-list ,formal-list)
                       (formal-objects ,formal-objects)
                       (formal-types ,formal-types)
                       (reply-name ,reply-name)
                       (reply-type ,reply-type)
                       (reply-scope ,reply-scope)
                       (reply-scope-name ,reply-scope-name)
                       (return-type ,return-type)
                       (return-type-name ,return-type-name)
                       (signature ,signature)
                       (instance ,(and instance (.name instance)))
                       (instance-port ,(and instance-port (.name instance-port)))
                       (type ,(.name type))))))

(define ((init-bind model string) bind)
  (let* ((left (.left bind))
         (left-port (.port left))
         (left-port-name (.port.name left))
         (right (.right bind))
         (right-port-name (.port.name right))
         (right-port (.port right))
         (port (and (om:port-bind? bind)
                    (if (not (.instance left)) left-port right-port)))
         (port-name (and (om:port-bind? bind)
                    (if (not (.instance left)) left-port-name right-port-name)))
         (instance-port (and (om:port-bind? bind)
                             (if (not (.instance left)) right-port left-port)))
         (instance-port-name (and (om:port-bind? bind)
                             (if (not (.instance left)) right-port-name left-port-name)))
         (injected? (and (eq? port-name '*) port-name))
         (direction (or injected? (.direction port)))
         (edir (or injected? (if (eq? direction 'provides) 'out 'in)))
         (interface (if (not injected?) port
                        (if left-port left-port
                            right-port)))
         (interface (.type interface))
         (instance (and (om:port-bind? bind)  ;; FIXME: actually: binding-name
                        (if (not (.instance left))
                            (binding-name model right)
                            (binding-name model left)))))
    (animate string `((port ,port-name) (direction ,direction) (edir ,edir) (injected? ,injected?) (instance ,instance)
                      (instance-port ,(.name instance-port)) (interface ,(.name interface))))))

(define ((init-instance model string) instance)
  (let* ((component (.type instance))
         (name (.name instance))
         (bindings (injected-bindings model))
         (injected-instance-names (map injected-instance-name bindings))
         (injected? (member (.name instance) injected-instance-names))
         (injected-ports (if injected? (map injected-instance-port bindings) '())))
    (animate string `((component ,component)
                      (injected? ,injected?)
                      (injected-ports ,injected-ports)
                      (name ,name)))))

(define ((include-component string) instance)
  (let ((component ((om:scope-name) instance)))
    (animate string `((component ,component)))))

(define ((include-interface string) port)
  (let ((interface ((om:scope-name) (.type port))))
    (animate string `((interface ,interface)))))

(define ((init-member model string) variable)
  (let* ((name (.name variable))
         (type (.type variable))
         (expression (expression->string model (.expression variable)))
         (expression (if (and (string? expression)
                              (not (string-null? expression))) expression))
         (type (code:->code model type)))
    (animate string `((name ,name) (type ,type) (expression ,expression)))))

(define ((init-port string) port)
  (animate string `((scope ,om:scope)
                    (name ,.name)
                    (direction ,.direction)
                    (external? ,.external)
                    (injected? ,.injected)
                    (interface ,om:scope+name)
                    (port ,port))
           port))

(define ((init-async-port model string) port)
  (let* ((signature (.signature (car (om:events port))))
         (type (->code model (.type signature)))
         (formals ((compose .elements .formals) signature))
         (formal-types (map (lambda (formal)
                              (snippet 'formal-type `((type ,(->code model (.type formal))) (out? ,(member (.direction formal) '(inout out))))))
                            formals)))
   (animate string `((scope ,om:scope)
                     (name ,.name)
                     (direction ,.direction)
                     (external? ,.external)
                     (injected? ,.injected)
                     (interface ,om:scope+name)
                     (port ,port)
                     (signature ,signature)
                     (formal-types ,formal-types)
                     (type ,type))
            port)))

(define (declare-replies o)
  (map (lambda (x)
         (let ((s (match x
                    (($ <bool>) 'declare-reply-bool)
                    (($ <enum>) 'declare-reply-enum)
                    (($ <int>) 'declare-reply-int))))
           (snippet s `((scope ,(om:scope x))
                        (scope-name ,(om:scope+name x))
                        (name ,(om:name x))))))
       (om:reply-types o)))

(define ((define-reply string) type)
  (animate string `((scope ,(om:scope type))
                    (scope-name ,(om:scope+name type))
                    (name ,(om:name type)))
           type))

(define (return-type model event)
  (let ((type ((compose .type .signature) event)))
    (->code- model type)))

(define (binding-name model bind)
  (let ((instance (om:instance model bind))
        (port (.port bind)))
    (snippet 'binding
               `((instance ,(match instance
                                (($ <instance>) (.name instance))
                                (($ <interface>) (.name instance))))
                 (port ,(match port
                            (($ <port>) (.name port))
                            (($ <interface>) (list "x" (.name port)))))))))

(define (injected-binding? binding)
  (or (eq? '* (.port.name (.left binding)))
      (eq? '* (.port.name (.right binding)))))

(define (injected-binding binding)
  (cond ((eq? '* (.port.name (.left binding))) (.right binding))
        ((eq? '* (.port.name (.right binding))) (.left binding))
        (else #f)))

(define (injected-bindings model)
  (filter injected-binding? ((compose .elements .bindings) model)))

(define (injected-instance-name binding)
  (or (.instance.name (.left binding)) (.instance.name (.right binding))))

(define (injected-instance-port binding)
  (.port.name (if (.instance (.left binding)) (.left binding) (.right binding))))

(define (injected-instance-type model binding)
  (.type (om:instance model (if (.instance (.left binding))
                                      (.left binding)
                                      (.right binding)))))

(define (injected-instance-interface model binding)
  (.type (om:port (injected-instance-type model binding))))

(define (injected-instances model)
  (let ((injected-instance-names (map injected-instance-name (injected-bindings model))))
    (filter (lambda (instance) (member (.name instance) injected-instance-names))
            ((compose .elements .instances) model))))

(define (non-injected-instances model)
  (let ((injected-instance-names (map injected-instance-name (injected-bindings model))))
    (filter (lambda (instance) (not (member (.name instance) injected-instance-names)))
            ((compose .elements .instances) model))))

(define (code:identifier? name)
  (let* ((name (->string name))
         (first (car (string->list (->string name)))))
    (and (or (char-alphabetic? first)
             (eq? first #\_))
         (string-every (char-set-adjoin char-set:letter+digit #\_) name))))

(define-syntax string-if
  (syntax-rules ()
    ((_ condition then)
     (animate-string (if (null-is-#f condition) then "") (current-module)))
    ((_ condition then else)
     (animate-string (if (null-is-#f condition) then else) (current-module)))))

(define* (pairs->module key-procedure-pairs #:optional (parameter #f))
  (let ((module (code:module (and=> (module-variable (current-module) 'model)
                                    variable-ref))))
    (populate-module module key-procedure-pairs parameter)))

(define* ((animate-pairs pairs string) #:optional parameter)
  (animate string (pairs->module pairs parameter)))

(define (debug . x) #t)
;;(define debug stderr)

(define (calling-context)
  (let ((type (command-line:get 'calling-context #f)))
    (if type (make <type> #:name (make <scope.name> #:scope '() #:name (string->symbol type))) #f)))

(define (dump-header)
  (and-let* ((header (template-file `(header ,(code:extension (make <component>)))))
             (header (components->file-name header))
             ((file-exists? header)))
            (dump-string (basename header) (gulp-file header))))

(define (code:animate-file file-name module)
  (ast:set-model-scope
   (module-ref module 'model)
   ;; use old animate+component.js.scm for
   ;; services/scripts/verification.dzn, daemon/lib/Controller.dzn
   ;; until regression test passes
   (cond  ((member file-name '(component.cc.scm component.js.scm))
           (x:pand 'source-component (module-ref module 'model) module))
          ((member file-name '(component.hh.scm))
           (x:pand 'header-component (module-ref module 'model) module))
          ((member file-name '(interface.js.scm))
           (x:pand 'source-interface (module-ref module 'model) module))
          ((member file-name '(interface.hh.scm))
           (x:pand 'header-interface (module-ref module 'model) module))
          ((member file-name '(system.cc.scm system.js.scm))
           (x:pand 'source-system (module-ref module 'model) module))
          ((member file-name '(system.hh.scm))
           (x:pand 'header-system (module-ref module 'model) module))
          ((member file-name '(shell.hh.scm))
           (x:pand 'header-shell-system (module-ref module 'model) module))
          ((member file-name '(shell.cc.scm))
           (x:pand 'source-shell-system (module-ref module 'model) module))
          ((member file-name '(foreign.hh.scm))
           (x:pand 'foreign-header-component (module-ref module 'model) module))
          ((member file-name '(foreign.cc.scm))
           (x:pand 'foreign-source-component (module-ref module 'model) module))
          ((member file-name '(main.hh.scm))
           #t)
          ((member file-name '(main.cc.scm main.js.scm))
           (x:pand 'main-component (module-ref module 'model) module))
          ((member file-name '(glue-bottom-component.cc.scm))
           (x:pand 'glue-bottom-source-component (module-ref module 'model) module))
          ((member file-name '(glue-bottom-component.hh.scm))
           (x:pand 'glue-bottom-header-component (module-ref module 'model) module))
          ((member file-name '(glue-top-system.hh.scm))
           (x:pand 'glue-top-header-system (module-ref module 'model) module))
          ((member file-name '(glue-top-system.cc.scm))
           (x:pand 'glue-top-source-glue-system (module-ref module 'model) module))
          (else (animate-file file-name module)))))
