#! /bin/sh

# Dezyne --- Dezyne command line tools
#
# Copyright © 2021 Jan (janneke) Nieuwenhuizen <janneke@gnu.org>
#
# This file is part of Dezyne.
#
# Dezyne is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Dezyne is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with Dezyne.  If not, see <http://www.gnu.org/licenses/>.
#
# Commentary:
#
# Code:

set -e
set -x
mkdir -p test/all/state-diagram/out

dzn graph -b state test/all/state-diagram/state-diagram.dzn \
    | tee test/all/state-diagram/out/default.dot
diff -u test/all/state-diagram/default.dot test/all/state-diagram/out/default.dot

dzn graph -b state --remove=ports test/all/state-diagram/state-diagram.dzn \
    | tee test/all/state-diagram/out/remove-ports.dot
diff -u test/all/state-diagram/remove-ports.dot test/all/state-diagram/out/remove-ports.dot

dzn graph -b state --remove=extended test/all/state-diagram/state-diagram.dzn \
    | tee test/all/state-diagram/out/remove-extended.dot
diff -u test/all/state-diagram/remove-extended.dot test/all/state-diagram/out/remove-extended.dot

dzn graph -b state --remove=extended --hide=actions test/all/state-diagram/state-diagram.dzn \
    | tee test/all/state-diagram/out/hide-actions.dot
diff -u test/all/state-diagram/hide-actions.dot test/all/state-diagram/out/hide-actions.dot

dzn graph -b state --remove=extended --hide=labels test/all/state-diagram/state-diagram.dzn \
    | tee test/all/state-diagram/out/hide-labels.dot
diff -u test/all/state-diagram/hide-labels.dot test/all/state-diagram/out/hide-labels.dot
