// Generated by dzn code from test/all/shell_injected/shell_injected.dzn
#include <dzn/container.hh>

#include "shell_injected.hh"

#include <algorithm>
#include <cstring>

int to_int(std::string s){return std::stoi (s);}
bool to_bool(std::string s){return s == "true";}
void to_void(std::string){}

void
connect_ports (dzn::container< shell_injected, std::function<void()>>& c)
{
  c.system.r.in.e = [&] () {
    dzn::trace(std::clog, c.system.r.meta, "e");
    c.match("r.e");
    std::string tmp = c.match_return();
    dzn::trace_out(std::clog, c.system.r.meta, tmp.substr(tmp.rfind('.')+1).c_str());
    return to_void(tmp.substr(tmp.rfind('.')+1));
  };c.system.p.out.f = [&] () {
    c.match("p.f");
    return dzn::call_out(&c, [&]{
      if(c.flush) c.dzn_rt.queue(&c).push([&]{
        if(c.dzn_rt.queue(&c).empty()) {
          std::clog << "p.<flush>" << std::endl;
          c.match("p.<flush>");
        }
      });}, c.system.p.meta, "f");};}

std::map<std::string,std::function<void()> >
event_map (dzn::container< shell_injected, std::function<void()>>& c)
{
  c.system.p.meta.require.address = &c;
  c.system.p.meta.require.meta = &c.meta;
  c.system.p.meta.require.port = "p";
  c.system.r.meta.provide.address = &c;
  c.system.r.meta.provide.meta = &c.meta;
  c.system.r.meta.provide.port = "r";

  return {{"illegal", []{std::clog << "illegal" << std::endl;}}
    ,{"error", []{std::clog << "sut.error -> sut.error" << std::endl; std::exit(0);}}
    , {"p.e",[&]{
        c.system.p.in.e();
        c.match("p.return");
      }}
    , {"r.f",[&]{
        std::this_thread::sleep_for(std::chrono::milliseconds(1000));
        c.system.r.out.f();
      }}
    , {"r.<flush>",[&]{
        std::clog << "r.<flush>" << std::endl;
        c.dzn_rt.flush(&c);
      }}};
}

int
main(int argc, char* argv[])
{
  bool flush = argv + argc != std::find_if(argv + 1, argv + argc, [](const char* s){return std::strcmp(s,"--flush") == 0;});
  if(argv + argc != std::find_if(argv + 1, argv + argc, [](const char* s){return std::strcmp(s,"--debug") == 0;})) dzn::debug.rdbuf(std::clog.rdbuf());
  dzn::container< shell_injected, std::function<void()>> c(flush);

  connect_ports (c);
  c(event_map (c), {"r"});
}
//version: 2.12.0.rc2.8-3d547
