#!/bin/bash
cd "$(dirname "$0")"
status=0
mkdir -p ../../out/viewrace
cp outcome.ok.json ../../out/viewrace/outcome.json
for i in {0..9}
do
  dzn view -I ../LegoBallSorter viewrace.dzn 2> log
  diff log expected
  status=$?
  if [ $status -eq 1 ] 
  then
    mkdir -p ../../out/viewrace
    cp outcome.failed.json ../../out/viewrace/outcome.json
    break  
  fi
done
exit $status

