// Generated by dzn code from test/all/async_shell/async_shell.dzn
// -*-java-*-
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading;

class main {

  static void connect_ports (dzn.container<async_shell> c)
  {
    c.system.h.outport.world = () => {
      Thread.Sleep(100);
      c.match("h.world");
      c.dzn_runtime.call_out(c, () => {
        if(c.flush) c.dzn_runtime.queue(c).Enqueue(() => {
          if(c.dzn_runtime.queue(c).Count == 0) {
            Console.Error.WriteLine("h.<flush>");
            c.match("h.<flush>");
          }
        });
      }, c.system.h.dzn_meta, "world");
    };
  }

  static Dictionary<String, Action> event_map (dzn.container<async_shell> c)
  {
    c.system.h.dzn_meta.requires.component = c;
    c.system.h.dzn_meta.requires.meta = c.dzn_meta;
    c.system.h.dzn_meta.requires.name = "h";

    Dictionary<String, Action> lookup = new Dictionary<String, Action>();
    lookup.Add("illegal",()=>{Console.Error.WriteLine("illegal"); Environment.Exit(0);});
    lookup.Add("h.hello",()=>{c.system.h.inport.hello(); c.match("h.return");});

    return lookup;
  }

  public static void Main(String[] args)
  {
    if(Array.Exists(args, s => s == "--debug")) {
      Debug.Listeners.Add(new TextWriterTraceListener(Console.Error));
      Debug.AutoFlush = true;
    }
    bool flush = Array.Exists(args, s => s == "--flush");
    using(dzn.container<async_shell> c = new dzn.container<async_shell>((loc,name)=>{return new async_shell(loc,name);}, flush)) {
      connect_ports (c);
      c.run(event_map (c), new List<String> {});
    }
  }
}
//version: 2.12.0.rc2.8-3d547
