#! /bin/sh
# -*- scheme -*-
exec guile -L .. -e main -s $0 "$@"
!#
;; This file is part of Gaiag, Guile in Asd In Asd in Guile.
;;
;; Copyright (C) 2014  Jan Nieuwenhuizen <janneke@gnu.org>
;; Copyright (C) 2014  "Mu Lei" known as "NalaGinrut" <NalaGinrut@gmail.com>
;;
;; Gaiag is free software: you can redistribute it and/or modify
;; it under the terms of the GNU Affero General Public License as
;; published by the Free Software Foundation, either version 3 of the
;; License, or (at your option) any later version.
;;
;; Gaiag is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU Affero General Public License for more details.
;;
;; You should have received a copy of the GNU Affero General Public License
;; along with Gaiag.  If not, see <http://www.gnu.org/licenses/>.

(read-set! keywords 'prefix)

(define (main . args)
  (eval '(main (command-line)) (resolve-module '(language asd asdgen))))

(define-module (language asd asdgen)
  :use-module (system base language)
  :use-module (language asd asd)
  :use-module (language asd tokenize)
  :use-module (language asd misc)
  :use-module (language asd pretty)
  :use-module (language asd cpp)
  :use-module (ice-9 getopt-long))

(define (read-and-parse lang port cenv)
  (let ((exp ((language-reader lang) port cenv)))
    (cond
     ((eof-object? exp) exp)
     ((language-parser lang) => (lambda (parse) (parse exp)))
     (else exp))))

(define (asd-reader port env)
  ((make-parser) (make-tokenizer port) error))

(define (read-asd file-name)
  (asd-reader (open-file file-name "r") (current-module)))

(define (parse-opts args)
  (let* ((option-spec
	  '((help (single-char #\h))
            (language (single-char #\l) (value #t))
	    (version (single-char #\v))))
	 (options (getopt-long (command-line) option-spec
		   :stop-at-first-non-option #t))
	 (help? (option-ref options 'help #f))
	 (files (option-ref options '() '()))
	 (usage? (and (not help?) (null? files)))
	 (version? (option-ref options 'version #f)))
    (or
     (and version?
	  (stdout "0.1\n")
	  (exit 0))
      (and (or help? usage?)
	   ((or (and usage? stderr) stdout) "\
Usage: asdgen [OPTION]... FILE
  -h, --help           display this help
  -l, --language=LANG  generate output for language=LANG [asd]
  -v, --version       display version
")
	   (exit (or (and usage? 2) 0)))
     options)))

(define (asd ast)
  (format #t "~a\n" (asd->string ast)))

(define pretty asd)

(define (cpp ast)
  (asd->cpp ast))

(define (main args)
  (let* ((options (parse-opts args))
	 (file-name (car (option-ref options '() '())))
         (ast (read-asd file-name))
         (language (eval (string->symbol (option-ref options 'language "pretty")) (current-module))))
    (language ast)))
