#! /bin/bash

sed -r\
    -e 's@([^+=()*& ]*)\(@(\1 @g' \
    -e 's@if \(@(if @g' \
    -e 's@\{@(@g' \
    -e 's@\}@)@g' \
    -e 's@ *[*&] *@ @g' \
    -e 's@\( +@(@g' \
    -e 's@ +\)@)@g' \
    -e 's@\("([^\"]+)\", @(\1 . @g' \
    -e 's@ *, *@ @g' \
    -e 's@ +\)@)@g' \
    -e 's@ *const *@ @g' \
    -e 's@port->getName@port-name component@g' \
    -e 's@gulp_file@gulp-snippet@g' \
    -e 's@\(format::FormatDict\)@@g' \
    -e 's@format::FormatString@format-keys@g' \
    -e 's@comp[.]getName@component-name component@g' \
    -e 's@comp[.]getPorts@component-get-ports component@g' \
    -e 's@port->getName@port-name component@g' \
    -e 's@port->getInterface@port-get-interface component@g' \
    -e 's@[(]([.]get-declaration|[.]as-interface-declaration|->get-name)[)]@@g' \
    -e 's@([a-z])([A-Z])@\1-\L\2@g' \
    -e 's@[a-zA-Z0-9_]+::@@g' \
    -e 's@;@@g' \
    $1

#    -e 's@ port@ (compontent-get-port component)@g' \
