#! /bin/sh
# -*- scheme -*-
exec guile -L ../.. -e main -s $0 "$@"
!#
;; This file is part of Gaiag, Guile in Asd In Asd in Guile.
;;
;; Copyright (C) 2014  Jan Nieuwenhuizen <janneke@gnu.org>
;; Copyright (C) 2014  "Mu Lei" known as "NalaGinrut" <NalaGinrut@gmail.com>
;;
;; Gaiag is free software: you can redistribute it and/or modify
;; it under the terms of the GNU Affero General Public License as
;; published by the Free Software Foundation, either version 3 of the
;; License, or (at your option) any later version.
;;
;; Gaiag is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU Affero General Public License for more details.
;;
;; You should have received a copy of the GNU Affero General Public License
;; along with Gaiag.  If not, see <http://www.gnu.org/licenses/>.

(read-set! keywords 'prefix)

(define (main . args)
  (eval '(main (command-line)) (resolve-module '(language asd gaiag))))

(define-module (language asd gaiag)
  :use-module (ice-9 getopt-long)

  :use-module (system repl error-handling)

;;  :use-module (language asd tokenize)
  :use-module (language asd misc)
  :use-module (language asd reader)

  :use-module (language asd c++)
  :use-module (language asd csp)
  :use-module (language asd pretty)
  :use-module (language asd scheme)
  :use-module (language asd simulate)
  :use-module (language asd wfc))

(define (parse-opts args)
  (let* ((option-spec
	  '((debug (single-char #\d))
            (help (single-char #\h))
            (language (single-char #\l) (value #t))
	    (version (single-char #\v))))
	 (options (getopt-long (command-line) option-spec
		   :stop-at-first-non-option #t))
	 (help? (option-ref options 'help #f))
	 (files (option-ref options '() '()))
	 (usage? (and (not help?) (null? files)))
	 (version? (option-ref options 'version #f)))
    (or
     (and version?
	  (stdout "0.1\n")
	  (exit 0))
      (and (or help? usage?)
	   ((or (and usage? stderr) stdout) "\
Usage: gaiag [OPTION]... FILE
  -d, --debug          run with debugging
  -h, --help           display this help
  -l, --language=LANG  generate output for language=LANG [scheme]
  -v, --version        display version

Languages: asd c++ scheme
")
	   (exit (or (and usage? 2) 0)))
     options)))

(define (file->lang file-name language)
  (display ((module-ref (resolve-module `(language asd ,language)) 'asd->) (read-asd file-name))))

(define (main args)
  (let* ((options (parse-opts args))
         (debug? (option-ref options 'debug #f))
	 (file-name (car (option-ref options '() '())))
         (language (string->symbol (option-ref options 'language "scheme"))))
    (call-with-error-handling (lambda () (file->lang file-name language)) :on-error (if debug? 'debug 'backtrace))))
