#! /bin/sh
# -*- scheme -*-
exec guile -L $(dirname $0)/../.. -L $(dirname $0) -e main -s $0 "$@"
!#

(read-set! keywords 'prefix)

(define (main . args)
  (eval '(main (command-line)) (resolve-module '(language asd json2scm))))

(define-module (language asd json2scm)
  :use-module (system repl error-handling)
  :use-module (ice-9 getopt-long)
  :use-module (ice-9 match)
  :use-module (ice-9 pretty-print)

  :use-module (json)
  :use-module (language asd misc)
  :export (json->symbol-scm))

(define (parse-opts args)
  (let* ((option-spec
	  '((debug (single-char #\d))
            (help (single-char #\h))
	    (version (single-char #\v))))
	 (options (getopt-long (command-line) option-spec
                               :stop-at-first-non-option #t))
	 (help? (option-ref options 'help #f))
	 (files (option-ref options '() '()))
	 (usage? (and (not help?) (>1 (length files))))
	 (version? (option-ref options 'version #f)))
    (or
     (and version?
	  (stdout "0.1\n")
	  (exit 0))
      (and (or help? usage?)
	   ((or (and usage? stderr) stdout) "\
Usage: scm2json [OPTION]... FILE
Convert JSON in FILE or standard input, to scheme-AST on standard output
  -d, --debug          run with debugging
  -h, --help           display this help
  -v, --version        display version

Examples:
  ./gaiag -a \"$(cat examples/assert.json | ./json2scm)\" -l csp examples/Alarm.asd
")
	   (exit (or (and usage? 2) 0)))
     options)))

(define (json->symbol-scm src)
  (match src
    ((? string?) (string->symbol src))
    ((h ...) (map json->symbol-scm src))
    (_ src)))

(define (->scm files)
  (json->symbol-scm
   (json->scm 
    (if (null? files) 
	(current-input-port)
	(open-input-file (car files))))))

(define (script files)
  (pretty-print (->scm files)))

(define (main args)
  (let* ((options (parse-opts args))
         (debug? (option-ref options 'debug #f))
	 (files (option-ref options '() '())))
    (call-with-error-handling (lambda () (script files)) :on-error (if debug? 'debug 'backtrace))))
