;;; Dezyne --- Dezyne command line tools
;;;
;;; Copyright © 2016, 2018 Jan Nieuwenhuizen <janneke@gnu.org>
;;; Copyright © 2018 Rob Wieringa <Rob.Wieringa@verum.com>
;;; Copyright © 2018 Henk Katerberg <henk.katerberg@verum.com>
;;; Copyright © 2018 Rutger van Beusekom <rutger.van.beusekom@verum.com>
;;; Copyright © 2018 Paul Hoogendijk <paul.hoogendijk@verum.com>
;;; Copyright © 2017, 2018 Johri van Eerd <johri.van.eerd@verum.com>
;;;
;;; This file is part of Dezyne.
;;;
;;; Dezyne is free software: you can redistribute it and/or modify it
;;; under the terms of the GNU Affero General Public License as
;;; published by the Free Software Foundation, either version 3 of the
;;; License, or (at your option) any later version.
;;;
;;; Dezyne is distributed in the hope that it will be useful, but
;;; WITHOUT ANY WARRANTY; without even the implied warranty of
;;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
;;; Affero General Public License for more details.
;;;
;;; You should have received a copy of the GNU Affero General Public
;;; License along with Dezyne.  If not, see <http://www.gnu.org/licenses/>.
;;; 
;;; Commentary:
;;; 
;;; Code:

(define-module (scmcrl2 verification)

  #:use-module (ice-9 curried-definitions)
  #:use-module (ice-9 match)
  #:use-module (ice-9 popen)
  #:use-module (ice-9 rdelim)
  #:use-module (ice-9 receive)
  #:use-module (ice-9 regex)
  #:use-module (srfi srfi-1)
  #:use-module (srfi srfi-26)

  #:use-module ((oop goops) #:renamer (lambda (x) (if (member x '(<port> <foreign>)) (symbol-append 'goops: x) x)))

  #:use-module (gaiag command-line)
  #:use-module (gaiag config)
  #:use-module (gaiag goops)
  #:use-module (gaiag deprecated om)
  #:use-module (gaiag util)
  #:use-module (gaiag mcrl2)
  #:use-module (gaiag misc)
  #:use-module (gaiag resolve)
  #:use-module (scmcrl2 traces)
  #:use-module (gash job)
  #:use-module (gash pipe)
  #:use-module (json)

  #:export (mcrl2:verify
            verify:scope-name))

(define x:interface-init (@@ (gaiag mcrl2) x:interface-init))
(define x:interface-lts-init (@@ (gaiag mcrl2) x:interface-init))
(define x:component-init (@@ (gaiag mcrl2) x:component-init))
(define x:compliance-init (@@ (gaiag mcrl2) x:compliance-init))
(define x:determinism-init (@@ (gaiag mcrl2) x:determinism-init))
(define x:component-deadlock-init (@@ (gaiag mcrl2) x:component-deadlock-init))

(define (verify:scope-name o)
  ((om:scope-name '.) o))

(define (compliance-hidden-actions)
  (list "return" "optional" "inevitable" "event" "flush"))

(define (livelock-hidden-actions)
  (list "return" "event" "flush"))

(define (find-taus component model-name hidden-actions)
  (let ((req-ports (if component (map (lambda (r) (.name r)) (om:required component))
                       '())))
    (string-join (append-map (lambda (p)
			       (let ((portname (symbol->string p)))
				 (map (lambda (h)
					(string-append portname "'" h) )
				      hidden-actions)))
			     req-ports)
		 "," 'infix)))

;; debugx0r
;; (define pipeline->string- pipeline->string)
;; (define (pipeline->string . commands)
;;   (stderr "commands:~s\n" commands)
;;   (apply pipeline->string- commands))

;; (define pipeline- pipeline)
;; (define (pipeline fg? . commands)
;;   (stderr "commands:~s\n" commands)
;;   (apply pipeline- (cons fg? commands)))

;; (define pipeline+- pipeline+)
;; (define (pipeline+ fg? open? . commands)
;;   (stderr "commands:~s\n" commands)
;;   (apply pipeline+- (cons* fg? open? commands)))

;;(define cppflag "-rjittyc")
(define cppflag "")

(define (mcrl2:verify-interface dir file-name interface verbose? all?)
  (let* ((asserts (list (mcrl2:verify-interface-deadlock interface)
                        (mcrl2:verify-interface-livelock interface))))
    (let loop ((asserts asserts))
      (if (null? asserts) #f
          (let* ((assert (car asserts))
                 (fail? (apply assert (list dir file-name interface verbose? all?))))
            (if (or (not fail?) all?) (or (loop (cdr asserts)) fail?)
                fail?))))))

(define (mcrl2:verify-component dir file-name model-name ast verbose? all?)
  (let* ((component (find (lambda (x) (equal? (symbol->string (verify:scope-name x)) model-name)) (filter (is? <component>) (.elements ast))))
         (interfaces (delete-duplicates (map .type (om:ports component))))
         (asserts (append
                   (append-map
                    (lambda (i) (list
                                 (mcrl2:verify-interface-deadlock i)
                                 (mcrl2:verify-interface-livelock i)))
                    interfaces)
                   (list
                    (mcrl2:verify-component-deterministic component)
                    (mcrl2:verify-component-illegal component)
                    (mcrl2:verify-component-deadlock component)
                    (mcrl2:verify-component-livelock component)
                    (mcrl2:verify-component-refinement component)))))
    (let loop ((asserts asserts))
      (if (null? asserts) #f
          (let* ((assert (car asserts))
                 (fail? (apply assert (list dir file-name ast verbose? all?))))
            (if (or (not fail?) all?) (or (loop (cdr asserts)) fail?)
                fail?))))))

(define* (display-binary string #:optional (port (current-output-port)))
  (set-port-encoding! port "ISO-8859-1")
  (display string port))

(define (handle-error job error)
  (let ((status (wait job)))
    (when (not (zero? status))
      (stderr "~a" error)
      (exit status))
    status))

(define ((mcrl2:verify-interface-deadlock model) dir file-name ast verbose? all?)
  (let* ((model-name ((compose ->string verify:scope-name) model))
 	 (foo (assert-start 'interface model-name 'deadlock verbose?))
         (commands `(,(cut x:interface-init model)
                     ("cat" "verify.mcrl2" "-")
                     ("mcrl22lps" "-b")
                     ("lpsconstelm" "-st")
                     ("lpsparelm")
                     ("lps2lts" "--deadlock" "-t1" "--cached" "-v" "--out-deadlock=-")
                     ))
         (trace (receive (job ports)
                    (apply pipeline+ #f commands)
                  (set-port-encoding! (car ports) "ISO-8859-1")
                  (let* ((trace (read-string (car ports)))
                         (error (read-string (cadr ports)))
                         (status (handle-error job error)))
                    (and (string-contains error "deadlock-detect: deadlock found") trace))))
         (trace (and trace (pipeline->string (cut display-binary trace) '("tracepp"))))
         (trace (and trace (rename-lts-actions trace))))
    (if (number? trace) (exit trace)
        (check-deadlock trace dir file-name 'interface model-name verbose?))))

(define ((mcrl2:verify-interface-livelock model) dir file-name ast verbose? all?)
  (let* ((model-name ((compose ->string verify:scope-name) model))
 	 (foo (assert-start 'interface model-name 'livelock verbose?))
         (taus "")
         (commands `(,(cut x:interface-init model)
                     ("cat" "verify.mcrl2" "-")
                     ("mcrl22lps" "-b")
                     ("lpsconstelm" "-st")
                     ("lpsparelm")
                     ("lps2lts" "--divergence" "-t1" "-v" "--cached" ,(string-append "--tau=" taus) "--out-divergence=-")))
         (trace (receive (job ports)
                    (apply pipeline+ #f commands)
                  (set-port-encoding! (car ports) "ISO-8859-1")
                  (let* ((trace (read-string (car ports)))
                         (error (read-string (cadr ports)))
                         (status (handle-error job error)))
                    (and (string-contains error "Trace to the divergencing state") trace))))
         (trace (and trace (pipeline->string (cut display-binary trace) '("tracepp"))))
         (trace (and trace (rename-lts-actions trace)))
         (loop (and trace (mcrl2-trace-file->dzn-trace "_divergence_loop0.trc")))
         (trace (and trace (string-append trace "\n" loop))))
    (if (number? trace) (exit trace)
        (check-livelock trace dir file-name 'interface model-name verbose?))))

(define ((mcrl2:verify-component-deterministic model) dir file-name ast verbose? all?)
  (let* ((model-name ((compose ->string verify:scope-name) model))
 	 (foo (assert-start 'component model-name 'deadlock verbose?))
         (commands `(,(cut x:determinism-init model)
                     ("cat" "verify.mcrl2" "-")
                     ("tee" "0.mcrll2")
                     ("mcrl22lps" "-b")
                     ("lpsconstelm" "-st")
                     ("lpsparelm")
                     ("lps2lts" "--nondeterminism" "--cached" "--trace" "--out-nondeterminism=-")))
         (trace (receive (job ports)
                    (apply pipeline+ #f commands)
                  (set-port-encoding! (car ports) "ISO-8859-1")
                  (let* ((trace (read-string (car ports)))
                         (error (read-string (cadr ports)))
                         (status (handle-error job error)))
                    (and (string-contains error "Nondeterministic state found") trace))))
         (trace (and trace (pipeline->string (cut display-binary trace) '("tracepp"))))
         (trace (and trace (rename-lts-actions trace))))
    (if (number? trace) (exit trace)
        (check-deterministic trace dir file-name 'component model-name verbose?))))

(define ((mcrl2:verify-component-illegal model) dir file-name ast verbose? all?)
  (let* ((model-name ((compose ->string verify:scope-name) model))
 	 (foo (assert-start 'component model-name 'illegal verbose?))
         (commands `(,(cut x:component-init ast)
                     ("cat" "verify.mcrl2" "-")
                     ("tee" "0.mcrll2")
                     ("mcrl22lps" "-b")
                     ("lpsconstelm" "-st")
                     ("lpsparelm" )
                     ("lps2lts" "-aillegal" "-t1" "-v" "--cached" "--out-action=-")))
         (trace (receive (job ports)
                    (apply pipeline+ #f commands)
                  (set-port-encoding! (car ports) "ISO-8859-1")
                  (let* ((trace (read-string (car ports)))
                         (error (read-string (cadr ports)))
                         (status (handle-error job error)))
                    (and (string-contains error "Detected action 'illegal'") trace))))
         (trace (and trace (pipeline->string (cut display-binary trace) '("tracepp"))))
         (trace (and trace (rename-lts-actions trace))))
    (if (number? trace) (exit trace)
        (check-illegal trace dir file-name 'component model-name verbose?))))

(define ((mcrl2:verify-component-deadlock model) dir file-name ast verbose? all?)
  (let* ((model-name ((compose ->string verify:scope-name) model))
 	 (foo (assert-start 'component model-name 'deadlock verbose?))
         (commands `(,(cut x:component-deadlock-init ast)
                     ("cat" "-" "verify.mcrl2")
                     ("mcrl22lps" "-b")
                     ("lpsconstelm" "-st")
                     ("lpsparelm")
                     ("lps2lts" "--deadlock" "-t1" "--cached" "-v" "--out-deadlock=-")))
         (trace (receive (job ports)
                    (apply pipeline+ #f commands)
                  (set-port-encoding! (car ports) "ISO-8859-1")
                  (let* ((trace (read-string (car ports)))
                         (error (read-string (cadr ports)))
                         (status (handle-error job error)))
                    (and (string-contains error "deadlock-detect: deadlock found") trace))))
         (trace (and trace (pipeline->string (cut display-binary trace) '("tracepp"))))
         (trace (and trace (rename-lts-actions trace))))
    (if (number? trace) (exit trace)
        (check-deadlock trace dir file-name 'component model-name verbose?))))

(define ((mcrl2:verify-component-livelock model) dir file-name ast verbose? all?)
  (let* ((model-name ((compose ->string verify:scope-name) model))
 	 (foo (assert-start 'component model-name 'livelock verbose?))
         (taus (find-taus model model-name (livelock-hidden-actions)))
         (commands `(,(cut x:component-init ast)
                     ("cat" "verify.mcrl2" "-")
                     ("mcrl22lps" "-b")
                     ("lpsconstelm" "-st")
                     ("lpsparelm")
                     ("lps2lts" "--divergence" "-t1" "-v" "--cached" ,(string-append "--tau=" taus) "--out-divergence=-")))
         (trace (receive (job ports)
                    (apply pipeline+ #f commands)
                  (set-port-encoding! (car ports) "ISO-8859-1")
                  (let* ((trace (read-string (car ports)))
                         (error (read-string (cadr ports)))
                         (status (handle-error job error)))
                    (and (string-contains error "Trace to the divergencing state") trace))))
         (trace (and trace (pipeline->string (cut display-binary trace) '("tracepp"))))
         (trace (and trace (rename-lts-actions trace)))
         (loop (and trace (mcrl2-trace-file->dzn-trace "_divergence_loop0.trc")))
         (trace (and trace (string-append trace "\n" loop))))
    (if (number? trace) (exit trace)
        (check-livelock trace dir file-name 'component model-name verbose?))))

(define ((mcrl2:verify-component-refinement-start model) ast verbose?)
  (let* ((model-name ((compose ->string verify:scope-name) model))
 	 (foo (assert-start 'component model-name 'compliance verbose?))
         ;;(provided-lps (create-lps "verify.mcrl2" 'provided ast))
         (commands `(,(cut x:compliance-init ast)
                     ("cat" "verify.mcrl2" "-")
                     ("mcrl22lps" "-b")
                     ("lpsconstelm" "-st")
                     ("lpsparelm")
                     ("lps2lts" "--cached" "--out=lts")
                     ("ltsconvert" "-edpbranching-bisim" "--in=lts" "--out=aut")
                     ("sed" "-e" "s/\"illegal\"/\"dillegal\"/g")
                     ("bash" "-c" "cat > provided"))) ;; FIXME
         (result (apply pipeline->string commands))
         (taus (find-taus model model-name (compliance-hidden-actions)))
         (commands `(,(cut x:component-init ast)
                     ("cat" "verify.mcrl2" "-")
                     ("mcrl22lps" "-b")
                     ("lpsconstelm" "-st")
                     ("lpsparelm")
                     ("lps2lts" "--cached" "--out=lts")
                     ("ltsconvert" "-edpbranching-bisim" "--in=lts" "--out=aut")
                     ("ltscompare" "-v" "-c" "-pweak-failures" ,(string-append "--tau=" taus) "--in1=aut" "--in2=aut" "/dev/stdin" "provided"))))
    (apply pipeline+ #f commands)))

(define ((mcrl2:verify-component-refinement-finish job ports) model dir file-name verbose?)
  (set-port-encoding! (car ports) "ISO-8859-1")
  (let* ((model-name ((compose ->string verify:scope-name) model))
         (trace (read-string (car ports)))
         (error (read-string (cadr ports)))
         (status (handle-error job error))
         (trace (and (string-contains error "is not included in the LTS")
                     (read-string (open-input-file "counter_example_weak_failures_refinement.trc" #:binary #t))))
         (trace (and trace (pipeline->string (cut display-binary trace) '("tracepp"))))
         (trace (and trace (rename-lts-actions trace))))
    (if (number? trace) (exit trace)
      (check-compliance error trace dir file-name 'component model-name verbose?))))

(define ((mcrl2:verify-component-refinement model) dir file-name ast verbose? all?)
  (receive (job ports) ((mcrl2:verify-component-refinement-start model) ast verbose?)
    ((mcrl2:verify-component-refinement-finish job ports) model dir file-name verbose?)))

;; (define ((mcrl2:verify-component-refinement model) dir file-name ast verbose? all?)
;;   (let* ((model-name ((compose ->string verify:scope-name) model))
;;  	 (foo (assert-start 'component model-name 'compliance verbose?))
;;          ;;(provided-lps (create-lps "verify.mcrl2" 'provided ast))
;;          (commands `(,(cut display (mcrl2:init ast "compliance-init@ast"))
;;                      ("cat" "verify.mcrl2" "-")
;;                      ("mcrl22lps" "-b")
;;                      ("lpsconstelm" "-st")
;;                      ("lpsparelm")
;;                      ("lps2lts" "--cached" "--out=lts")
;;                      ("ltsconvert" "-edpbranching-bisim" "--in=lts" "--out=aut")
;;                      ("sed" "-e" "s/\"illegal\"/\"dillegal\"/g")
;;                      ("bash" "-c" "cat > provided"))) ;; FIXME
;;          (result (apply pipeline->string commands))
;;          (taus (find-taus model model-name (compliance-hidden-actions)))
;;          (commands `(,(cut display (mcrl2:init ast "component-init@ast"))
;;                      ("cat" "verify.mcrl2" "-")
;;                      ("mcrl22lps" "-b")
;;                      ("lpsconstelm" "-st")
;;                      ("lpsparelm")
;;                      ("lps2lts" "--cached" "--out=lts")
;;                      ("ltsconvert" "-edpbranching-bisim" "--in=lts" "--out=aut")
;;                      ("ltscompare" "-v" "-c" "-pweak-failures" ,(string-append "--tau=" taus) "--in1=aut" "--in2=aut" "/dev/stdin" "provided"))))
;;     (receive (trace error)
;;         (receive (job ports)
;;             (apply pipeline+ #f commands)
;;           (set-port-encoding! (car ports) "ISO-8859-1")
;;           (let* ((trace (read-string (car ports)))
;;                  (error (read-string (cadr ports)))
;;                  (status (handle-error job error)))
;;             (values (and (string-contains error "is not included in the LTS")
;;                          (read-string (open-input-file "counter_example_weak_failures_refinement.trc" #:binary #t)))
;;                     error)))
;;       (let* ((trace (and trace (pipeline->string (cut display-binary trace) '("tracepp"))))
;;              (trace (and trace (rename-lts-actions trace))))
;;         (if (number? trace) (exit trace)
;;             (check-compliance error trace dir file-name 'component model-name verbose?))))))

(define (mcrl2:verify dir file-name model-name ast verbose? all?)
  (if model-name
      (let ((model (find (lambda (x) (equal? (symbol->string (verify:scope-name x)) model-name)) (filter (is? <model>) (.elements ast)))))
        (if (is-a? model <component>)
            (mcrl2:verify-component dir file-name model-name ast verbose? all?)
            (mcrl2:verify-interface dir file-name model verbose? all?)))
      (let ((components (filter (is? <component>) (.elements ast))))
        (pair? (filter-map (lambda (c) (mcrl2:verify-component dir file-name (->string (verify:scope-name c)) ast verbose? all?)) components)))))

(define (assert-start model-type model-name assert verbose?)
  (when verbose?
    (if (gdzn:command-line:get 'json)
        (format #t "~a\n"
                (scm->json-string `(((model . ,model-name)
                                     (type . ,model-type)
                                     (assert . ,assert)
                                     (first . "true")
                                     (status . "assert")))))))
  #f)

(define (assert-ok model-type model-name assert verbose?)
  (when verbose?
    (if (not (gdzn:command-line:get 'json))
        (stdout "verify: ~a: check: ~a: ok\n" model-name assert)
        (format #t "~a\n"
                (scm->json-string `(((model . ,model-name)
                                     (type . ,model-type)
                                     (assert . ,assert)
                                     (result . ok)
                                     (trace . ,`())
                                     (status . "done")))))))
  #f)

(define (sequence->error sequence)
  (let* ((ecneuqes (reverse sequence))
         (error (car ecneuqes))
         (message (and=> (assoc-ref error 'message) symbol->string))
         (location (find (lambda (e) (and=> (assoc-ref (cdr e) 'selection)
                                            (compose (cut assoc-ref <> 'file) car)))
                         ecneuqes))
         (location (and=> (assoc-ref location 'selection) car))
         (file-name (assoc-ref location 'file))
         (line (assoc-ref location 'line))
         (column (assoc-ref location 'column))
         (index (assoc-ref location 'index)))
    (format #f "~a:~a:~a:i~a: ~a\n" file-name line column index message)))

(define ((sequence->trail model-name illegal?) sequence)
  (let* ((model-name (last (string-split model-name #\.))) ;; FIXME namespace from seqdiag
         (model-name (string->symbol model-name)))
    (map
     (lambda (o) (or (assoc-ref o 'synchronization) 'illegal))
     (filter (lambda (o)
               (or (and (eq? (assoc-ref o 'instance) model-name)
                        (assoc-ref o 'synchronization))
                   (and illegal?
                        (eq? (assoc-ref o 'kind) 'Error)
                        (string-contains (symbol->string (assoc-ref o 'message)) "(implicitly) illegal"))))
             sequence))))

(define (assert-fail dir file-name model-type model-name assert trace message interface-trace)
  (read-hash-extend #\{ #f)
  (when interface-trace (with-output-to-file "interface-trace.txt" (cut display interface-trace)))
  (let* ((interface-trace-file (and interface-trace (canonicalize-path "interface-trace.txt")))
         (verbose? (gdzn:command-line:get 'verbose))
         (message (or message (format #f "~a in model ~a" assert model-name)))
         (trace-list (filter (negate string-null?) (string-split trace #\newline)))
         (last-el (and (pair? trace-list) (last trace-list)))
         (second-last (and (pair? trace-list) (pair? (drop-right trace-list 1)) (last (drop-right trace-list 1))))
         (last last-el)
         (message (cond
                   ((equal? last "range_error") (format #f "integer range error in model ~a" model-name))
                   ((equal? last "type_error") (format #f "type error in model ~a" model-name))
                   ((equal? last "double_reply_error") (format #f "error double reply in model ~a" model-name))
                   ((equal? last "no_reply_error") (format #f "error missing reply in model ~a" model-name))
                   ((equal? last "incomplete") (format #f "model ~a is incomplete: event '~a' not handled" model-name second-last))
                   ((find (cut equal? "queue_full" <>) trace-list) "queue full")
                   (else message)))
         (trace (if (member last '("range_error" "type_error" "double_reply_error" "no_reply_error" "incomplete"))
                    (string-join (drop-right trace-list (if (equal? last "incomplete") 2 1)) "\n")
                    (string-join (take-while (negate (cut equal? "queue_full" <>)) trace-list) "\n"))))
    (let* ((cwd (getcwd))
           (foo (chdir dir))
           (commands (list
                      (cut display trace)
                      `("seqdiag" ,(if (eq? assert 'deterministic) "-u" "") "-m" ,model-name "-e" ,message
                        ,@(if interface-trace `("-s" ,interface-trace-file) '())
                        ,file-name)))
           (commands (if (gdzn:command-line:get 'json) commands
                         (append commands (list (list "json2scm"))))))
      (receive (job ports)
          (apply pipeline+ #f commands)
        (let ((port (car ports)))
          (if (not (gdzn:command-line:get 'json))
              (let* ((output (read port))
                     (error  (read-string (cadr ports)))
                     (status (handle-error job error))
                     (trace ((sequence->trail model-name #f) output))
                     (trace (string-join (map symbol->string trace) "\n"))
                     (trace (if (string-null? trace) trace (string-append trace "\n"))))
                (chdir cwd)
                (stderr "~a" (sequence->error output))
                (stdout "verify: ~a: check: ~a: fail\n~a" model-name assert trace))
              (let* ((output (read-string port))
                     (error  (read-string (cadr ports)))
                     (status (handle-error job error))
                     (trace (string-trim-right trace)))
                (chdir cwd)
                (format #t "~a\n"
                        (scm->json-string `(((model . ,model-name)
                                             (type . ,model-type)
                                             (assert . ,assert)
                                             (sequence . ,(json-string->scm output))
                                             (trace . ,(string-split trace #\newline))
                                             (result . fail)
                                             (status . done)))))))))))
  #t)

(define (check-deterministic trace dir file-name model-type model-name verbose?)
  (let ((assert 'deterministic))
    (if (not trace) (assert-ok model-type model-name assert verbose?)
        (let ((message (format #f "Component ~a is non-deterministic due to overlapping guards" model-name)))
          (assert-fail dir file-name model-type model-name assert trace message #f)))))

(define (check-illegal trace dir file-name model-type model-name verbose?)
  (let ((assert 'illegal))
    (if (not trace) (assert-ok model-type model-name assert verbose?)
        (let ((message "illegal"))
          (assert-fail dir file-name model-type model-name assert trace message #f)))))

(define (check-deadlock trace dir file-name model-type model-name verbose?)
  (let ((assert 'deadlock))
    (if (not trace) (assert-ok model-type model-name assert verbose?)
        (let ((message #f))
          (assert-fail dir file-name model-type model-name assert trace message #f)))))

(define (check-livelock trace dir file-name model-type model-name verbose?)
  (let ((assert 'livelock))
    (if (not trace) (assert-ok model-type model-name assert verbose?)
        (let ((message #f))
          (assert-fail dir file-name model-type model-name assert trace message #f)))))

(define (check-compliance error trace dir file-name model-type model-name verbose?)
  (let ((assert 'compliance))
    (if (not trace) (assert-ok model-type model-name assert verbose?)
        (let* ((trace (string-trim-right trace))
               (trace (if (string-null? trace) trace (string-append trace "\n")))
               (component-accepts (cond ((string-match "The acceptance of the left process is empty." error) #f)
                                        ((string-match "A stable acceptance set of the left process is:\n([^\n]*)\n" error) => (cut match:substring <> 1))
                                        ((string-match "is not included in the LTS in" error) "")
                                        (else (stderr "other string:~s\n" error))))
               (component-accepts (and component-accepts (rename-lts-actions component-accepts)))
               (component-trace (if component-accepts (string-append trace component-accepts "\n")
                                    trace))
               (component-trace-file "component-trace.txt")
               (interface-accepts (cond ((string-match "The process at the right has no acceptance sets" error) #f)
                                        ((string-match "An acceptance set of the right process is:\n([^\n]*)\n" error) =>  (cut match:substring <> 1))
                                        ((string-match "is not included in the LTS in" error) "")
                                        (else (stderr "other string:~s\n" error))))
               (interface-accepts (and interface-accepts (rename-lts-actions interface-accepts)))
               (interface-trace (if interface-accepts (string-append trace interface-accepts "\n")
                                    trace))
               (interface-trace-file "interface-trace.txt")
               (message (format #f "Component ~a is non-compliant with interface of provided port" model-name)))
          (assert-fail dir file-name model-type model-name assert component-trace message interface-trace)))))
