// /////////////////////////////////////////////////////////////////////////////
// 
// File generated by   : Verum ASD:Suite Release 4, version 9.2.6.52369
// Language            : cpp
// 
// Model name          : AlarmSystem
// Model file          : AlarmSystem.dm
// Model last updated  : 2014-Aug-20 12:06:37
// Model fingerprint   : A6B50F5A
// 
// Version             : 1.0
// Project             : 
// Author              : Peter van de Velde
// Component type      : Multiple
// Execution model     : Single-threaded
// Broadcasting        : No
// 
// /////////////////////////////////////////////////////////////////////////////
// 
// Verification result  : outdated
// 
// /////////////////////////////////////////////////////////////////////////////
// 
// TAGS:
// 
// tag: Tag
// Description
// 
// /////////////////////////////////////////////////////////////////////////////



#include "AlarmSystemComponent.h"
#include "WindowSensorComponent.h"
#include "SirenComponent.h"
#include "TimerComponent.h"

#include "asdSingleThreaded.h"
#include "asdUsedServiceRef.h"
#include "asdDiagnostics.h"

#include <boost/bind.hpp>
#include <vector>
#include <set>

using namespace asd_52369;

namespace AlarmSystemImplScope
{
  class Context;
  class IAlarmSystemProxy: public IAlarmSystem
  {
    Context& m_Context;

  public:
    IAlarmSystemProxy(Context& context);
    virtual IAlarmSystem::PseudoStimulus SwitchOn();
    virtual void SwitchOff();

  private:
    IAlarmSystemProxy& operator = (const IAlarmSystemProxy& other);
    IAlarmSystemProxy(const IAlarmSystemProxy& other);
  };

  class SensorAdapter
  {
  public:
    SensorAdapter(const boost::shared_ptr<SensorInterface>& service): m_asd_Interface(service)
    {
      m_asd_Interface->GetAPI(&m_ISensor);
    }

    const boost::shared_ptr<ISensor>& GetISensor() const
    {
      return m_ISensor;
    }

    // ISensor_NI
    void RegisterCB(boost::shared_ptr<ISensor_NI> cb)
    {
      m_asd_Interface->RegisterCB(cb);
      m_ISensor_NI = cb;
    }

    void RegisterCB(boost::shared_ptr<asd::channels::ISingleThreaded> cb)
    {
      m_asd_Interface->RegisterCB(cb);
    }

  private:
    boost::shared_ptr<SensorInterface> m_asd_Interface;
    boost::shared_ptr<ISensor> m_ISensor;
    boost::shared_ptr<ISensor_NI> m_ISensor_NI;
  };

  class SirenAdapter
  {
  public:
    SirenAdapter(const boost::shared_ptr<SirenInterface>& service): m_asd_Interface(service)
    {
      m_asd_Interface->GetAPI(&m_ISiren);
    }

    const boost::shared_ptr<ISiren>& GetISiren() const
    {
      return m_ISiren;
    }

  private:
    boost::shared_ptr<SirenInterface> m_asd_Interface;
    boost::shared_ptr<ISiren> m_ISiren;
  };

  class TimerAdapter
  {
  public:
    TimerAdapter(const boost::shared_ptr<TimerInterface>& service): m_asd_Interface(service)
    {
      m_asd_Interface->GetAPI(&m_Timer);
    }

    const boost::shared_ptr<Timer>& GetTimer() const
    {
      return m_Timer;
    }

    // TimerCB
    void RegisterCB(boost::shared_ptr<TimerCB> cb)
    {
      m_asd_Interface->RegisterCB(cb);
      m_TimerCB = cb;
    }

    void RegisterCB(boost::shared_ptr<asd::channels::ISingleThreaded> cb)
    {
      m_asd_Interface->RegisterCB(cb);
    }

  private:
    boost::shared_ptr<TimerInterface> m_asd_Interface;
    boost::shared_ptr<Timer> m_Timer;
    boost::shared_ptr<TimerCB> m_TimerCB;
  };

  struct asd_Resource
  {
    asd_Resource ()
    : WindowSensor(1)
    , Siren(1)
    , timer(1)
    {}

    std::vector<boost::shared_ptr<SensorAdapter> > WindowSensor;
    std::vector<boost::shared_ptr<SirenAdapter> > Siren;
    std::vector<boost::shared_ptr<TimerAdapter> > timer;
  };

  struct asd_UCV
  {
    asd_UCV (const asd_Resource& asd_resource)
    : WindowSensor(&asd_resource.WindowSensor[0], &asd_resource.WindowSensor[0] + asd_resource.WindowSensor.size())
    , Siren(&asd_resource.Siren[0], &asd_resource.Siren[0] + asd_resource.Siren.size())
    , timer(&asd_resource.timer[0], &asd_resource.timer[0] + asd_resource.timer.size())
    {}

    fixed_ucv<SensorAdapter> WindowSensor;

    fixed_ucv<SirenAdapter> Siren;

    fixed_ucv<TimerAdapter> timer;
  };

  class State;
  class Context: public asd_52369::SingleThreadedContext
  {
  public: 
    asd_Resource m_Resource;
    asd_UCV m_Ucv;
    boost::shared_ptr<IAlarmSystem_NI> m_IAlarmSystem_NI;
    IAlarmSystem::PseudoStimulus m_IAlarmSystemPseudoStimulus;
    State* m_CurrentGlobal;
    State* m_Current;

  public:
    
    Context* Self() { return this; }

  private:
    Context(const Context&);
    Context& operator = (const Context&);

  public:
    Context();
    virtual ~Context();
    const fixed_ucv<SensorAdapter>& GetWindowSensor() const;
    const fixed_ucv<SirenAdapter>& GetSiren() const;
    const fixed_ucv<TimerAdapter>& Gettimer() const;
    void Set(const boost::shared_ptr<IAlarmSystem_NI>&);
    IAlarmSystem_NI& GetIAlarmSystem_NI() const;
    IAlarmSystem::PseudoStimulus GetIAlarmSystemPseudoStimulus() const;
    void SetIAlarmSystemPseudoStimulus(IAlarmSystem::PseudoStimulus);
    State& CurrentGlobal();
    void UpdateLocal(State&);
    State& CurrentLocal();
  };

  class State
  {
  protected:
    const char* const name;
  public:
    State(const char*);
    virtual ~State() {}
    void ProcessPseudoStimulus(Context& context, ISensor::PseudoStimulus stimulus, const variable_ucv<SensorAdapter>&);
    void ProcessPseudoStimulus(Context& context, ISiren::PseudoStimulus stimulus, const variable_ucv<SirenAdapter>&);
    void ProcessPseudoStimulus(Context& context, Timer::PseudoStimulus stimulus, const variable_ucv<TimerAdapter>&);
    virtual void IAlarmSystemSwitchOn(Context& context);
    virtual void IAlarmSystemSwitchOff(Context& context);
    virtual void WindowSensorISensor_NIDetectedMovement(Context& context, const variable_ucv<SensorAdapter>& that);
    virtual void WindowSensorISensor_NIDeactivated(Context& context, const variable_ucv<SensorAdapter>& that);
    virtual void timerTimerCBtimeout(Context& context, const variable_ucv<TimerAdapter>& that);

  protected:
    std::string m_TypeName;

  private:
    State& operator = (const State& other);
    State(const State& other);
  };

  class NotActivated: public State
  {
  public:
    static State& instance();
    virtual void IAlarmSystemSwitchOn(Context& context);

  private:
    NotActivated();
    NotActivated& operator = (const NotActivated& other);
    NotActivated(const NotActivated& other);
  };

  class Activated_Idle: public State
  {
  public:
    static State& instance();
    virtual void IAlarmSystemSwitchOff(Context& context);
    virtual void WindowSensorISensor_NIDetectedMovement(Context& context, const variable_ucv<SensorAdapter>& that);

  private:
    Activated_Idle();
    Activated_Idle& operator = (const Activated_Idle& other);
    Activated_Idle(const Activated_Idle& other);
  };

  class Activated_AlarmMode: public State
  {
  public:
    static State& instance();
    virtual void IAlarmSystemSwitchOff(Context& context);

  private:
    Activated_AlarmMode();
    Activated_AlarmMode& operator = (const Activated_AlarmMode& other);
    Activated_AlarmMode(const Activated_AlarmMode& other);
  };

  class Deactivating: public State
  {
  public:
    static State& instance();
    virtual void WindowSensorISensor_NIDeactivated(Context& context, const variable_ucv<SensorAdapter>& that);

  private:
    Deactivating();
    Deactivating& operator = (const Deactivating& other);
    Deactivating(const Deactivating& other);
  };

  class Activated_Tripped: public State
  {
  public:
    static State& instance();
    virtual void IAlarmSystemSwitchOff(Context& context);
    virtual void timerTimerCBtimeout(Context& context, const variable_ucv<TimerAdapter>& that);

  private:
    Activated_Tripped();
    Activated_Tripped& operator = (const Activated_Tripped& other);
    Activated_Tripped(const Activated_Tripped& other);
  };

  class Component: public AlarmSystemComponent
  {
  private:
    Context m_Context;
    boost::shared_ptr<IAlarmSystemProxy> m_IAlarmSystemProxy;
    Component(const Component&);
    Component& operator = (const Component&);

  public:
    Component();
    ~Component();

    virtual void GetAPI(boost::shared_ptr<IAlarmSystem>* api);
    virtual void RegisterCB(boost::shared_ptr<IAlarmSystem_NI> cb);
    virtual void RegisterCB(boost::shared_ptr<asd::channels::ISingleThreaded> cb);
  };

  IAlarmSystemProxy::IAlarmSystemProxy(Context& context)
  : m_Context(context)
  {
  }

  IAlarmSystem::PseudoStimulus IAlarmSystemProxy::SwitchOn()
  {
    m_Context.block();
    m_Context.CurrentGlobal().IAlarmSystemSwitchOn(m_Context);
    m_Context.awaitUnblock();
    return m_Context.GetIAlarmSystemPseudoStimulus();
  }

  void IAlarmSystemProxy::SwitchOff()
  {
    m_Context.block();
    m_Context.CurrentGlobal().IAlarmSystemSwitchOff(m_Context);
    m_Context.awaitUnblock();
  }

  class WindowSensorISensor_NIProxy: public ISensor_NI
  {
    Context& m_Context;
    variable_ucv<SensorAdapter> m_That;

  public:
    WindowSensorISensor_NIProxy(Context& context,  const variable_ucv<SensorAdapter>& that)
    : m_Context(context)
    , m_That(that)
    {}

    virtual void DetectedMovement()
    {
      m_Context.defer(boost::bind(&State::WindowSensorISensor_NIDetectedMovement,
                      boost::bind(&Context::CurrentGlobal, &m_Context),
                      boost::ref(m_Context), boost::cref(m_That)));
    }

    virtual void Deactivated()
    {
      m_Context.defer(boost::bind(&State::WindowSensorISensor_NIDeactivated,
                      boost::bind(&Context::CurrentGlobal, &m_Context),
                      boost::ref(m_Context), boost::cref(m_That)));
    }

  private:
    WindowSensorISensor_NIProxy& operator = (const WindowSensorISensor_NIProxy& other);
    WindowSensorISensor_NIProxy(const WindowSensorISensor_NIProxy& other);
  };

  class timerTimerCBProxy: public TimerCB
  {
    Context& m_Context;
    variable_ucv<TimerAdapter> m_That;

  public:
    timerTimerCBProxy(Context& context,  const variable_ucv<TimerAdapter>& that)
    : m_Context(context)
    , m_That(that)
    {}

    virtual void timeout()
    {
      m_Context.defer(boost::bind(&State::timerTimerCBtimeout,
                      boost::bind(&Context::CurrentGlobal, &m_Context),
                      boost::ref(m_Context), boost::cref(m_That)));
    }

  private:
    timerTimerCBProxy& operator = (const timerTimerCBProxy& other);
    timerTimerCBProxy(const timerTimerCBProxy& other);
  };

  Context::Context()
  : asd_52369::SingleThreadedContext()
  , m_Resource()
  , m_Ucv(m_Resource)
  {
    std::vector<boost::shared_ptr<SensorInterface> > WindowSensor;
    WindowSensor.push_back(WindowSensorComponent::GetInstance());
    m_Resource.WindowSensor[0].reset(new SensorAdapter(WindowSensor[0]));
    std::vector<boost::shared_ptr<SirenInterface> > Siren;
    Siren.push_back(SirenComponent::GetInstance());
    m_Resource.Siren[0].reset(new SirenAdapter(Siren[0]));
    std::vector<boost::shared_ptr<TimerInterface> > timer;
    timer.push_back(TimerComponent::GetInstance());
    m_Resource.timer[0].reset(new TimerAdapter(timer[0]));
    for (unsigned int asd_i = 1; asd_i <= m_Ucv.WindowSensor.size(); ++asd_i)
    {
      m_Ucv.WindowSensor[asd_i].begin()->RegisterCB(boost::shared_ptr<asd::channels::ISingleThreaded>(new asd_52369::SingleThreadedProxy(*Self())));
    }
    for (unsigned int asd_i = 1; asd_i <= m_Ucv.WindowSensor.size(); ++asd_i)
    {
      m_Ucv.WindowSensor[asd_i].begin()->RegisterCB(boost::shared_ptr<ISensor_NI>(new WindowSensorISensor_NIProxy(*Self(), m_Ucv.WindowSensor[asd_i])));
    }
    for (unsigned int asd_i = 1; asd_i <= m_Ucv.timer.size(); ++asd_i)
    {
      m_Ucv.timer[asd_i].begin()->RegisterCB(boost::shared_ptr<asd::channels::ISingleThreaded>(new asd_52369::SingleThreadedProxy(*Self())));
    }
    for (unsigned int asd_i = 1; asd_i <= m_Ucv.timer.size(); ++asd_i)
    {
      m_Ucv.timer[asd_i].begin()->RegisterCB(boost::shared_ptr<TimerCB>(new timerTimerCBProxy(*Self(), m_Ucv.timer[asd_i])));
    }
  }

  Context::~Context()
  {
    for (unsigned int asd_i = 0; asd_i < m_Resource.WindowSensor.size(); ++asd_i)
    {
      m_Resource.WindowSensor[asd_i].reset();
      WindowSensorComponent::ReleaseInstance();
    }
    for (unsigned int asd_i = 0; asd_i < m_Resource.Siren.size(); ++asd_i)
    {
      m_Resource.Siren[asd_i].reset();
      SirenComponent::ReleaseInstance();
    }
    for (unsigned int asd_i = 0; asd_i < m_Resource.timer.size(); ++asd_i)
    {
      m_Resource.timer[asd_i].reset();
      TimerComponent::ReleaseInstance();
    }
  }

  State& Context::CurrentGlobal()
  {
    assert(m_CurrentGlobal);
    return *m_CurrentGlobal;
  }

  void Context::UpdateLocal(State& s)
  {
    m_Current = &s;
    m_CurrentGlobal = &s;
  }

  State& Context::CurrentLocal()
  {
    assert(m_Current);
    m_CurrentGlobal = m_Current;
    return *m_Current;
  }

  void Context::Set(const boost::shared_ptr<IAlarmSystem_NI>& cb)
  {
    if (m_IAlarmSystem_NI && cb)
    {
      ASD_ILLEGAL("AlarmSystem", "", "IAlarmSystem_NI", "");
    }
    m_IAlarmSystem_NI = cb;
  }

  const fixed_ucv<SensorAdapter>& Context::GetWindowSensor() const
  {
    return m_Ucv.WindowSensor;
  }

  const fixed_ucv<SirenAdapter>& Context::GetSiren() const
  {
    return m_Ucv.Siren;
  }

  const fixed_ucv<TimerAdapter>& Context::Gettimer() const
  {
    return m_Ucv.timer;
  }

  IAlarmSystem_NI& Context::GetIAlarmSystem_NI() const
  {
    return *m_IAlarmSystem_NI;
  }

  IAlarmSystem::PseudoStimulus Context::GetIAlarmSystemPseudoStimulus() const
  {
    return m_IAlarmSystemPseudoStimulus;
  }

  void Context::SetIAlarmSystemPseudoStimulus(IAlarmSystem::PseudoStimulus value)
  {
    m_IAlarmSystemPseudoStimulus = value;
    unblock();
  }

  
  Component::Component()
  : m_Context()
  , m_IAlarmSystemProxy(new IAlarmSystemProxy(m_Context))
  
  {
    ASD_TRACE_ENTER("AlarmSystem", "", "", "");

    m_Context.UpdateLocal(NotActivated::instance());

    ASD_TRACE_EXIT("AlarmSystem", "", "", "");
  }

  Component::~Component()
  {
    ASD_TRACE_ENTER("AlarmSystem", "", "", "");

    ASD_TRACE_EXIT("AlarmSystem", "", "", "");
  }

  void Component::GetAPI(boost::shared_ptr<IAlarmSystem>* api)
  {
    *api = m_IAlarmSystemProxy;
  }

  void Component::RegisterCB(boost::shared_ptr<IAlarmSystem_NI> cb)
  {
    m_Context.Set(cb);
  }

  void Component::RegisterCB(boost::shared_ptr<asd::channels::ISingleThreaded> cb)
  {
    m_Context.setISingleThreaded(cb);
  }

  void State::ProcessPseudoStimulus(Context& context, ISensor::PseudoStimulus /* stimulus */, const variable_ucv<SensorAdapter>& that)
  {
    if (that.in(context.GetWindowSensor()))
    {
      ASD_ILLEGAL("AlarmSystem", name, "ISensor", "PseudoStimulus");
    }
  }

  void State::ProcessPseudoStimulus(Context& context, ISiren::PseudoStimulus /* stimulus */, const variable_ucv<SirenAdapter>& that)
  {
    if (that.in(context.GetSiren()))
    {
      ASD_ILLEGAL("AlarmSystem", name, "ISiren", "PseudoStimulus");
    }
  }

  void State::ProcessPseudoStimulus(Context& context, Timer::PseudoStimulus /* stimulus */, const variable_ucv<TimerAdapter>& that)
  {
    if (that.in(context.Gettimer()))
    {
      ASD_ILLEGAL("AlarmSystem", name, "Timer", "PseudoStimulus");
    }
  }

  State::State(const char* n)
  : name(n)
  {}
  void State::IAlarmSystemSwitchOn(Context&)
  {
    ASD_TRACE_ENTER("AlarmSystem", name, "IAlarmSystem", "SwitchOn");

    ASD_ILLEGAL("AlarmSystem", name, "IAlarmSystem", "SwitchOn");
  }

  void State::IAlarmSystemSwitchOff(Context&)
  {
    ASD_TRACE_ENTER("AlarmSystem", name, "IAlarmSystem", "SwitchOff");

    ASD_ILLEGAL("AlarmSystem", name, "IAlarmSystem", "SwitchOff");
  }

  void State::WindowSensorISensor_NIDetectedMovement(Context&, const variable_ucv<SensorAdapter>&)
  {
    ASD_TRACE_ENTER("AlarmSystem", name, "ISensor_NI", "DetectedMovement");

    ASD_ILLEGAL("AlarmSystem", name, "ISensor_NI", "DetectedMovement");
  }

  void State::WindowSensorISensor_NIDeactivated(Context&, const variable_ucv<SensorAdapter>&)
  {
    ASD_TRACE_ENTER("AlarmSystem", name, "ISensor_NI", "Deactivated");

    ASD_ILLEGAL("AlarmSystem", name, "ISensor_NI", "Deactivated");
  }

  void State::timerTimerCBtimeout(Context&, const variable_ucv<TimerAdapter>&)
  {
    ASD_TRACE_ENTER("AlarmSystem", name, "TimerCB", "timeout");

    ASD_ILLEGAL("AlarmSystem", name, "TimerCB", "timeout");
  }

  NotActivated::NotActivated()
  : State("NotActivated")
  {}
  State& NotActivated::instance()
  {
    static NotActivated inst;
    return inst;
  }

  void NotActivated::IAlarmSystemSwitchOn(Context& context)
  {
    ASD_TRACE_ENTER("AlarmSystem", name, "IAlarmSystem", "SwitchOn");

    // Rulecase line number: 4
    // 
    // Activate sensor
    context.GetWindowSensor().begin()->GetISensor()->Activate();
    context.SetIAlarmSystemPseudoStimulus(IAlarmSystem::Ok);
    context.UpdateLocal(Activated_Idle::instance());

    ASD_TRACE_EXIT("AlarmSystem", name, "IAlarmSystem", "SwitchOn");
  }

  Activated_Idle::Activated_Idle()
  : State("Activated_Idle")
  {}
  State& Activated_Idle::instance()
  {
    static Activated_Idle inst;
    return inst;
  }

  void Activated_Idle::IAlarmSystemSwitchOff(Context& context)
  {
    ASD_TRACE_ENTER("AlarmSystem", name, "IAlarmSystem", "SwitchOff");

    // Rulecase line number: 13
    // 
    // Deactivate sensor
    context.GetWindowSensor().begin()->GetISensor()->Deactivate();
    context.SetIAlarmSystemPseudoStimulus(IAlarmSystem::VoidReply);
    context.UpdateLocal(Deactivating::instance());

    ASD_TRACE_EXIT("AlarmSystem", name, "IAlarmSystem", "SwitchOff");
  }

  void Activated_Idle::WindowSensorISensor_NIDetectedMovement(Context& context, const variable_ucv<SensorAdapter>& /* that */)
  {
    ASD_TRACE_ENTER("AlarmSystem", name, "ISensor_NI", "DetectedMovement");

    // Rulecase line number: 14
    // 
    // Sensor dectected movement - start timer
    context.GetIAlarmSystem_NI().Tripped();
    context.Gettimer().begin()->GetTimer()->create();
    context.UpdateLocal(Activated_Tripped::instance());

    ASD_TRACE_EXIT("AlarmSystem", name, "ISensor_NI", "DetectedMovement");
  }

  Activated_AlarmMode::Activated_AlarmMode()
  : State("Activated_AlarmMode")
  {}
  State& Activated_AlarmMode::instance()
  {
    static Activated_AlarmMode inst;
    return inst;
  }

  void Activated_AlarmMode::IAlarmSystemSwitchOff(Context& context)
  {
    ASD_TRACE_ENTER("AlarmSystem", name, "IAlarmSystem", "SwitchOff");

    // Rulecase line number: 37
    // 
    // Turn siren off, deactive sensor
    context.GetSiren().begin()->GetISiren()->TurnOff();
    context.GetWindowSensor().begin()->GetISensor()->Deactivate();
    context.SetIAlarmSystemPseudoStimulus(IAlarmSystem::VoidReply);
    context.UpdateLocal(Deactivating::instance());

    ASD_TRACE_EXIT("AlarmSystem", name, "IAlarmSystem", "SwitchOff");
  }

  Deactivating::Deactivating()
  : State("Deactivating")
  {}
  State& Deactivating::instance()
  {
    static Deactivating inst;
    return inst;
  }

  void Deactivating::WindowSensorISensor_NIDeactivated(Context& context, const variable_ucv<SensorAdapter>& /* that */)
  {
    ASD_TRACE_ENTER("AlarmSystem", name, "ISensor_NI", "Deactivated");

    // Rulecase line number: 23
    // 
    // Sensor deactivated - alarm system switched off
    context.GetIAlarmSystem_NI().SwitchedOff();
    context.UpdateLocal(NotActivated::instance());

    ASD_TRACE_EXIT("AlarmSystem", name, "ISensor_NI", "Deactivated");
  }

  Activated_Tripped::Activated_Tripped()
  : State("Activated_Tripped")
  {}
  State& Activated_Tripped::instance()
  {
    static Activated_Tripped inst;
    return inst;
  }

  void Activated_Tripped::IAlarmSystemSwitchOff(Context& context)
  {
    ASD_TRACE_ENTER("AlarmSystem", name, "IAlarmSystem", "SwitchOff");

    // Rulecase line number: 29
    // 
    // Cancel timer, deactive sensor
    context.Gettimer().begin()->GetTimer()->cancel();
    context.GetWindowSensor().begin()->GetISensor()->Deactivate();
    context.SetIAlarmSystemPseudoStimulus(IAlarmSystem::VoidReply);
    context.UpdateLocal(Deactivating::instance());

    ASD_TRACE_EXIT("AlarmSystem", name, "IAlarmSystem", "SwitchOff");
  }

  void Activated_Tripped::timerTimerCBtimeout(Context& context, const variable_ucv<TimerAdapter>& /* that */)
  {
    ASD_TRACE_ENTER("AlarmSystem", name, "TimerCB", "timeout");

    // Rulecase line number: 32
    context.GetSiren().begin()->GetISiren()->TurnOn();
    context.UpdateLocal(Activated_AlarmMode::instance());

    ASD_TRACE_EXIT("AlarmSystem", name, "TimerCB", "timeout");
  }
}

boost::shared_ptr<AlarmSystemInterface> AlarmSystemComponent::GetInstance()
{
  return boost::shared_ptr<AlarmSystemInterface>(new AlarmSystemImplScope::Component());
}

void AlarmSystemComponent::ReleaseInstance()
{
}

// /////////////////////////////////////////////////////////////////////////////
// 
// Verum audit trail signature : UoWkSM+CMpvpX0pBo40Yf2saXioMP+XF1k9JpymAF3wc5QuEM6bbP8B7aT8Q1/cSNn6g8M7CycHc80IEN6AkpRgHziQ1qPNDzjMDZioLOPtYmt9CmvSD3JgJ/fqXQczaJG47WjF09IsvjO9JZeWDSONw9DFyc8kOqycRy4/erj6YmVHKMheDcQq5YlaWJxc4DFNdNv6PBTtEoFN7mgzidJFg5fKzzftr2Yz9IjiGUtPph8lr9fFBkea1jvnoi2zALUN9LvRFFCUGA7PVJ7pf1LNsoOnY/ecncggoA41fKma4TrGnSJYOU1oEQq7NO5qupMtOjpPCjWosDmxQ0H0Tpg==
// 
// /////////////////////////////////////////////////////////////////////////////
// 
// ---------- End of file ------------------------------------------------------
// 
// /////////////////////////////////////////////////////////////////////////////
