// Gaiag --- Guile in Asd In Asd in Guile.
//
// This file is part of Gaiag.
//
// Copyright © 2014 Rutger van Beusekom <rutger.van.beusekom@verum.com>
//
// Gaiag is free software: you can redistribute it and/or modify it
// under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// Gaiag is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public
// License along with Gaiag.  If not, see <http://www.gnu.org/licenses/>.
//
// Commentary:
//
// Code:

// /////////////////////////////////////////////////////////////////////////////
// 
// File generated by   : Verum ASD:Suite Release 4, version 9.2.6.52369
// Language            : cpp
// 
// Model name          : AlarmSystem
// Model file          : AlarmSystem.dm
// Model last updated  : 2014-Aug-20 12:06:37
// Model fingerprint   : A6B50F5A
// 
// Version             : 1.0
// Project             : 
// Author              : Peter van de Velde
// Component type      : Multiple
// Execution model     : Single-threaded
// Broadcasting        : No
// 
// /////////////////////////////////////////////////////////////////////////////
// 
// Verification result  : passed
// 
// /////////////////////////////////////////////////////////////////////////////
// 
// TAGS:
// 
// tag: Tag
// Description
// 
// /////////////////////////////////////////////////////////////////////////////


#ifndef __ALARMSYSTEM_COMPONENT_H__
#define __ALARMSYSTEM_COMPONENT_H__

#include "AlarmSystemInterface.h"

class AlarmSystemComponent: public AlarmSystemInterface
{
public:
  static boost::shared_ptr<AlarmSystemInterface> GetInstance();
  static void ReleaseInstance();
};

#endif

// /////////////////////////////////////////////////////////////////////////////
// 
// Verum audit trail signature : I3Q5CLaTE1t8k9m30gi/2mSmeT09dqXQkJ5cexONHEaTMbAYjdcPTfV9KnZkQka9hnntpXdp3d+aHEp67N28C7ssqo6m4hFQrwbGFP/u+VnqFtx/ftl8KjIs3gQ3I0OO9TLShqhVK8ZAat4Snc1s44xCVN89SsdkEGX0u5wWQ3WM+triUC0WJRX368V+uWdleF/USTw+mdDhdqE1pZZsh3jzUjjY22VhTHoOlxC2KKMhmR3iAd4dvWSilfnWY4maL2orWSWMCFf160s91im4iRdbzQ0/rCFphYrRvxfLf5aFQAroa9Xfx0EJAZez5eqMo+5k2/41brG4A5DT3Wrkag==
// 
// /////////////////////////////////////////////////////////////////////////////
// 
// ---------- End of file ------------------------------------------------------
// 
// /////////////////////////////////////////////////////////////////////////////
