// Gaiag --- Guile in Asd In Asd in Guile.
//
// This file is part of Gaiag.
//
// Copyright © 2014 Rutger van Beusekom <rutger.van.beusekom@verum.com>
//
// Gaiag is free software: you can redistribute it and/or modify it
// under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// Gaiag is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public
// License along with Gaiag.  If not, see <http://www.gnu.org/licenses/>.
//
// Commentary:
//
// Code:

// /////////////////////////////////////////////////////////////////////////////
// 
// File generated by   : Verum ASD:Suite Release 4, version 9.2.6.52369
// Language            : cpp
// 
// Model name          : Sensor
// Model file          : Sensor.im
// Model last updated  : 2014-Aug-20 12:34:15
// Model fingerprint   : 6E8BC61A
// 
// Version             : 1.0
// Project             : 
// Author              : Peter van de Velde
// Execution model     : Single-threaded
// Broadcasting        : No
// 
// /////////////////////////////////////////////////////////////////////////////
// 
// Verification result  : outdated
// 
// /////////////////////////////////////////////////////////////////////////////
// 
// TAGS:
// 
// tag: Tag
// Description
// 
// /////////////////////////////////////////////////////////////////////////////


#ifndef __SENSOR_INTERFACE_H__
#define __SENSOR_INTERFACE_H__

#include <boost/shared_ptr.hpp>

#ifdef ASD_HAVE_CONFIG_H
  #include "asdConfig.h"
#else
  #include "asdDefConfig.h"
#endif

#include "asdPassByValue.h"
#include "asdInterfaces.h"



class ISensor
{
public:
  enum PseudoStimulus {
    
    /// <summary>
    /// The VoidReply event indicates that the processing of the API call has been completed
    /// and the call can return when appropriate.
    /// </summary>
    VoidReply
  };
  virtual ~ISensor() {}

  /// <summary>
  /// Activate the sensor
  /// </summary>
  virtual void Activate() = 0;

  /// <summary>
  /// Deactivate the sensor; asynchronous: Deactivated notifies completion
  /// </summary>
  virtual void Deactivate() = 0;
protected:
  ISensor() {}
private:
  ISensor& operator = (const ISensor& other);
  ISensor(const ISensor& other);
};

class ISensor_NI
{
public:
  virtual ~ISensor_NI() {}

  /// <summary>
  /// Sensor has detected movement
  /// </summary>
  virtual void DetectedMovement() = 0;

  /// <summary>
  /// Notification that Deactive has completed
  /// </summary>
  virtual void Deactivated() = 0;
protected:
  ISensor_NI() {}
private:
  ISensor_NI& operator = (const ISensor_NI& other);
  ISensor_NI(const ISensor_NI& other);
};

class SensorInterface
{
public:
  virtual ~SensorInterface() {}
  virtual void GetAPI(boost::shared_ptr<ISensor>* api) = 0;
  virtual void RegisterCB(boost::shared_ptr<ISensor_NI> cb) = 0;
  virtual void RegisterCB(boost::shared_ptr<asd::channels::ISingleThreaded> cb) = 0;
protected:
  SensorInterface() {}
private:
  SensorInterface& operator = (const SensorInterface& other);
  SensorInterface(const SensorInterface& other);
};

#endif

// /////////////////////////////////////////////////////////////////////////////
// 
// Verum audit trail signature : LpYQ7bXvSy2s2KBesbCXpDeQL7lzOmzHhR3Yf3g6Vpd1QFp30eFuxJR8WJORk1B+k+3fSxPpqahd/Svzk/Amn2+Q5JUp5iiA2ZAOB3miz7hGEVrtQez6YoihLoekQjjhdESB676Ynytl6H6Jc8UdjwY1yxAjNQ9GWy3q/y8jjl0421KXe+HWOYlJUdNAqAL30bQI3vDnl2zB0HGUU6r1kwKqsJLdIX6EtHMKrwIA7l77W6xL52310zqQ0VJN6JN/Du2UDqVCyzIXD9CpPiANiad6vKFO+dLVVBzm22avjgNsNhVZgizRwDRRfmD3CNOXA7hCNPySsnAVtwbPGDHS2Q==
// 
// /////////////////////////////////////////////////////////////////////////////
// 
// ---------- End of file ------------------------------------------------------
// 
// /////////////////////////////////////////////////////////////////////////////
