// Gaiag --- Guile in Asd In Asd in Guile.
//
// This file is part of Gaiag.
//
// Copyright © 2014 Rutger van Beusekom <rutger.van.beusekom@verum.com>
//
// Gaiag is free software: you can redistribute it and/or modify it
// under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// Gaiag is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public
// License along with Gaiag.  If not, see <http://www.gnu.org/licenses/>.
//
// Commentary:
//
// Code:

// /////////////////////////////////////////////////////////////////////////////
// 
// File generated by   : Verum ASD:Suite Release 4, version 9.2.6.52369
// Language            : cpp
// 
// Model name          : Siren
// Model file          : Siren.im
// Model last updated  : 2014-Aug-20 12:34:02
// Model fingerprint   : DD0BC54E
// 
// Version             : 1.0
// Project             : 
// Author              : Peter van de Velde
// Execution model     : Single-threaded
// Broadcasting        : No
// 
// /////////////////////////////////////////////////////////////////////////////
// 
// Verification result  : outdated
// 
// /////////////////////////////////////////////////////////////////////////////
// 
// TAGS:
// 
// tag: Tag
// Description
// 
// /////////////////////////////////////////////////////////////////////////////


#ifndef __SIREN_INTERFACE_H__
#define __SIREN_INTERFACE_H__

#include <boost/shared_ptr.hpp>

#ifdef ASD_HAVE_CONFIG_H
  #include "asdConfig.h"
#else
  #include "asdDefConfig.h"
#endif

#include "asdPassByValue.h"
#include "asdInterfaces.h"



class ISiren
{
public:
  enum PseudoStimulus {
    
    /// <summary>
    /// The VoidReply event indicates that the processing of the API call has been completed
    /// and the call can return when appropriate.
    /// </summary>
    VoidReply
  };
  virtual ~ISiren() {}

  /// <summary>
  /// Turn the siren on
  /// </summary>
  virtual void TurnOn() = 0;

  /// <summary>
  /// Turn the siren off
  /// </summary>
  virtual void TurnOff() = 0;
protected:
  ISiren() {}
private:
  ISiren& operator = (const ISiren& other);
  ISiren(const ISiren& other);
};

class SirenInterface
{
public:
  virtual ~SirenInterface() {}
  virtual void GetAPI(boost::shared_ptr<ISiren>* api) = 0;
protected:
  SirenInterface() {}
private:
  SirenInterface& operator = (const SirenInterface& other);
  SirenInterface(const SirenInterface& other);
};

#endif

// /////////////////////////////////////////////////////////////////////////////
// 
// Verum audit trail signature : JqFRiAtTl5MBzAQvdOqe2hDvmQ9MkxpO/XQk01H+/VX5ZqgOY/zQmfAnwUeuQDWZEkZz9T9/O6IuzehPGLzFGMoqxM/iJz1MkhBG4mWdOW1cFu0UTQ4Cc8d3kpUiiqZPPzXYmT/eSbTPlrzN99fiJQlInC72Bj1BCXEmKAiX+OBuNjx2OzpWCj3gxtnuustx6w0E+fA2w7LlKNX01WeGtjkEphnwMSa70D0KPdKtDEAv1nEGpLOeGEwpW728zVGgzS4Ydaz+RkeYFdinMNbBRMK1gvz9+SOD5JOFDBHmIuDrMEVI4szb01U7zu7DkH3hayEcuGlBCoBKjVQRE5bsOw==
// 
// /////////////////////////////////////////////////////////////////////////////
// 
// ---------- End of file ------------------------------------------------------
// 
// /////////////////////////////////////////////////////////////////////////////
