// Gaiag --- Guile in Asd In Asd in Guile.
//
// This file is part of Gaiag.
//
// Copyright © 2014 Rutger van Beusekom <rutger.van.beusekom@verum.com>
//
// Gaiag is free software: you can redistribute it and/or modify it
// under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// Gaiag is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public
// License along with Gaiag.  If not, see <http://www.gnu.org/licenses/>.
//
// Commentary:
//
// Code:

// /////////////////////////////////////////////////////////////////////////////
// 
// File generated by   : Verum ASD:Suite Release 4, version 9.2.6.52369
// Language            : cpp
// 
// Model name          : Timer
// Model file          : Timer.im
// Model last updated  : 2014-Aug-20 12:54:27
// Model fingerprint   : C73013AB
// 
// Version             : 1.0
// Project             : 
// Author              : 
// Execution model     : Single-threaded
// Broadcasting        : No
// 
// /////////////////////////////////////////////////////////////////////////////
// 
// Verification result  : outdated
// 
// /////////////////////////////////////////////////////////////////////////////


#ifndef __TIMER_INTERFACE_H__
#define __TIMER_INTERFACE_H__

#include <boost/shared_ptr.hpp>

#ifdef ASD_HAVE_CONFIG_H
  #include "asdConfig.h"
#else
  #include "asdDefConfig.h"
#endif

#include "asdPassByValue.h"
#include "asdInterfaces.h"



class Timer
{
public:
  enum PseudoStimulus {
    
    /// <summary>
    /// The VoidReply event indicates that the processing of the API call has been completed
    /// and the call can return when appropriate.
    /// </summary>
    VoidReply
  };
  virtual ~Timer() {}
  virtual void create() = 0;
  virtual void cancel() = 0;
protected:
  Timer() {}
private:
  Timer& operator = (const Timer& other);
  Timer(const Timer& other);
};

class TimerCB
{
public:
  virtual ~TimerCB() {}
  virtual void timeout() = 0;
protected:
  TimerCB() {}
private:
  TimerCB& operator = (const TimerCB& other);
  TimerCB(const TimerCB& other);
};

class TimerInterface
{
public:
  virtual ~TimerInterface() {}
  virtual void GetAPI(boost::shared_ptr<Timer>* api) = 0;
  virtual void RegisterCB(boost::shared_ptr<TimerCB> cb) = 0;
  virtual void RegisterCB(boost::shared_ptr<asd::channels::ISingleThreaded> cb) = 0;
protected:
  TimerInterface() {}
private:
  TimerInterface& operator = (const TimerInterface& other);
  TimerInterface(const TimerInterface& other);
};

#endif

// /////////////////////////////////////////////////////////////////////////////
// 
// Verum audit trail signature : nLySiDoayAS8LrKCFG1ukk1g3kJYY4laiwLjtDzHp38B6RMQqcocckOOIRWvbpv2Z8e8/zyhnu/qRQzKyTAiKFQ4nT+YRBuAJPTKyqKmsKOVSAww/S9t2jw1KvLOWKJUr0QuiHpBSD7OMu/xmdBywga5rhvvOpsUXFSDo7RjBUPpiL1+1qGSQtSpn6jWuUhkLUnT2n7+4wnWLP4q1ArmorCmd5xWAmxdrc7hm2ACne//EiS5puNjoFeCC7ERggYnBOBra6qPc1uiRo27tm9ljbMrjLCalmna798k4bpkoI5Rj8C/OAj/3TvEov9nyzCu3eyuV347YIBLrflGEUNgFw==
// 
// /////////////////////////////////////////////////////////////////////////////
// 
// ---------- End of file ------------------------------------------------------
// 
// /////////////////////////////////////////////////////////////////////////////
